@echo off
pushd "%~dp0"

set SLUG_INITIALIZED_ENVIRONMENT=1
set SLUG_MSBUILD_PATH="C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe"
set SLUG_REPOGITORY_ROOT_PATH=%~dp0
set SLUG_ENGINE_ROOT_PATH=%~dp0engine\
set SLUG_TOOLS_ROOT_PATH=%SLUG_ENGINE_ROOT_PATH%tools\
set SLUG_ENGINE_WORKSPACE_PATH=%SLUG_ENGINE_ROOT_PATH%_workspace\
set SLUG_ENGINE_BUILD_PATH=%SLUG_ENGINE_WORKSPACE_PATH%build\
set SLUG_ENGINE_SOLUTION_PATH=%SLUG_ENGINE_BUILD_PATH%SlugEngine.sln

echo "SLUG_MSBUILD_PATH=%MSBUILD_PATH%"
echo "SLUG_REPOGITORY_ROOT_PATH=%SLUG_REPOGITORY_ROOT_PATH%"
echo "SLUG_ENGINE_ROOT_PATH=%SLUG_ENGINE_ROOT_PATH%"
echo "SLUG_TOOLS_ROOT_PATH=%SLUG_TOOLS_ROOT_PATH%"
echo "SLUG_ENGINE_WORKSPACE_PATH=%SLUG_ENGINE_WORKSPACE_PATH%"
echo "SLUG_ENGINE_BUILD_PATH=%SLUG_ENGINE_BUILD_PATH%"
echo "SLUG_ENGINE_SOLUTION_PATH=%SLUG_ENGINE_SOLUTION_PATH%"
echo 

popd