// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct AABB : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
        public AABB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.Vector3 Max { get { return (new slug.fbs.srtf.Vector3()).__assign(__p.bb_pos + 0, __p.bb); } }
        public slug.fbs.srtf.Vector3 Min { get { return (new slug.fbs.srtf.Vector3()).__assign(__p.bb_pos + 12, __p.bb); } }

        public static Offset<slug.fbs.srtf.AABB> CreateAABB(FlatBufferBuilder builder, float max_X, float max_Y, float max_Z, float min_X, float min_Y, float min_Z)
        {
            builder.Prep(4, 24);
            builder.Prep(4, 12);
            builder.PutFloat(min_Z);
            builder.PutFloat(min_Y);
            builder.PutFloat(min_X);
            builder.Prep(4, 12);
            builder.PutFloat(max_Z);
            builder.PutFloat(max_Y);
            builder.PutFloat(max_X);
            return new Offset<slug.fbs.srtf.AABB>(builder.Offset);
        }
        public AABBT UnPack()
        {
            var _o = new AABBT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(AABBT _o)
        {
            _o.Max = this.Max.UnPack();
            _o.Min = this.Min.UnPack();
        }
        public static Offset<slug.fbs.srtf.AABB> Pack(FlatBufferBuilder builder, AABBT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.AABB>);
            var _max_x = _o.Max.X;
            var _max_y = _o.Max.Y;
            var _max_z = _o.Max.Z;
            var _min_x = _o.Min.X;
            var _min_y = _o.Min.Y;
            var _min_z = _o.Min.Z;
            return CreateAABB(
              builder,
              _max_x,
              _max_y,
              _max_z,
              _min_x,
              _min_y,
              _min_z);
        }
    }

    public class AABBT
    {
        public slug.fbs.srtf.Vector3T Max { get; set; }
        public slug.fbs.srtf.Vector3T Min { get; set; }

        public AABBT()
        {
            this.Max = new slug.fbs.srtf.Vector3T();
            this.Min = new slug.fbs.srtf.Vector3T();
        }
    }


}
