// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct BinormalLayer : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
        public BinormalLayer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public byte Name(int j) { return __p.bb.Get(__p.bb_pos + 0 + j * 1); }
        public void MutateName(int j, byte name) { __p.bb.Put(__p.bb_pos + 0 + j * 1, name); }
        public slug.fbs.srtf.Vector3 Binormal { get { return (new slug.fbs.srtf.Vector3()).__assign(__p.bb_pos + 64, __p.bb); } }

        public static Offset<slug.fbs.srtf.BinormalLayer> CreateBinormalLayer(FlatBufferBuilder builder, byte[] Name, float binormal_X, float binormal_Y, float binormal_Z)
        {
            builder.Prep(4, 76);
            builder.Prep(4, 12);
            builder.PutFloat(binormal_Z);
            builder.PutFloat(binormal_Y);
            builder.PutFloat(binormal_X);
            for (int _idx0 = 64; _idx0 > 0; _idx0--)
            {
                builder.PutByte(Name[_idx0 - 1]);
            }
            return new Offset<slug.fbs.srtf.BinormalLayer>(builder.Offset);
        }
        public BinormalLayerT UnPack()
        {
            var _o = new BinormalLayerT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(BinormalLayerT _o)
        {
            _o.Name = new byte[64];
            for (var _j = 0; _j < 64; ++_j) { _o.Name[_j] = this.Name(_j); }
            _o.Binormal = this.Binormal.UnPack();
        }
        public static Offset<slug.fbs.srtf.BinormalLayer> Pack(FlatBufferBuilder builder, BinormalLayerT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.BinormalLayer>);
            var _name = _o.Name;
            var _binormal_x = _o.Binormal.X;
            var _binormal_y = _o.Binormal.Y;
            var _binormal_z = _o.Binormal.Z;
            return CreateBinormalLayer(
              builder,
              _name,
              _binormal_x,
              _binormal_y,
              _binormal_z);
        }
    }

    public class BinormalLayerT
    {
        public byte[] Name { get; set; }
        public slug.fbs.srtf.Vector3T Binormal { get; set; }

        public BinormalLayerT()
        {
            this.Name = new byte[64];
            this.Binormal = new slug.fbs.srtf.Vector3T();
        }
    }


}
