// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace slug.fbs.srtf
{

    public enum BlendOptions : byte
    {
        Opaque = 0,
        Mask = 1,
        Transparent = 2,
        Addtive = 3,
        Modulate = 4,
    };


}
