// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct BoneLayer : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
        public BoneLayer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public byte Name(int j) { return __p.bb.Get(__p.bb_pos + 0 + j * 1); }
        public void MutateName(int j, byte name) { __p.bb.Put(__p.bb_pos + 0 + j * 1, name); }
        public int Id { get { return __p.bb.GetInt(__p.bb_pos + 64); } }
        public void MutateId(int id) { __p.bb.PutInt(__p.bb_pos + 64, id); }
        public float Weight { get { return __p.bb.GetFloat(__p.bb_pos + 68); } }
        public void MutateWeight(float weight) { __p.bb.PutFloat(__p.bb_pos + 68, weight); }

        public static Offset<slug.fbs.srtf.BoneLayer> CreateBoneLayer(FlatBufferBuilder builder, byte[] Name, int Id, float Weight)
        {
            builder.Prep(4, 72);
            builder.PutFloat(Weight);
            builder.PutInt(Id);
            for (int _idx0 = 64; _idx0 > 0; _idx0--)
            {
                builder.PutByte(Name[_idx0 - 1]);
            }
            return new Offset<slug.fbs.srtf.BoneLayer>(builder.Offset);
        }
        public BoneLayerT UnPack()
        {
            var _o = new BoneLayerT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(BoneLayerT _o)
        {
            _o.Name = new byte[64];
            for (var _j = 0; _j < 64; ++_j) { _o.Name[_j] = this.Name(_j); }
            _o.Id = this.Id;
            _o.Weight = this.Weight;
        }
        public static Offset<slug.fbs.srtf.BoneLayer> Pack(FlatBufferBuilder builder, BoneLayerT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.BoneLayer>);
            var _name = _o.Name;
            return CreateBoneLayer(
              builder,
              _name,
              _o.Id,
              _o.Weight);
        }
    }

    public class BoneLayerT
    {
        public byte[] Name { get; set; }
        public int Id { get; set; }
        public float Weight { get; set; }

        public BoneLayerT()
        {
            this.Name = new byte[64];
            this.Id = 0;
            this.Weight = 0.0f;
        }
    }


}
