// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct BoolParameter : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static BoolParameter GetRootAsBoolParameter(ByteBuffer _bb) { return GetRootAsBoolParameter(_bb, new BoolParameter()); }
        public static BoolParameter GetRootAsBoolParameter(ByteBuffer _bb, BoolParameter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public BoolParameter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public bool Value { get { int o = __p.__offset(6); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }
        public bool MutateValue(bool value) { int o = __p.__offset(6); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(value ? 1 : 0)); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.BoolParameter> CreateBoolParameter(FlatBufferBuilder builder,
            StringOffset nameOffset = default(StringOffset),
            bool value = false)
        {
            builder.StartTable(2);
            BoolParameter.AddName(builder, nameOffset);
            BoolParameter.AddValue(builder, value);
            return BoolParameter.EndBoolParameter(builder);
        }

        public static void StartBoolParameter(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
        public static void AddValue(FlatBufferBuilder builder, bool value) { builder.AddBool(1, value, false); }
        public static Offset<slug.fbs.srtf.BoolParameter> EndBoolParameter(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.BoolParameter>(o);
        }
        public BoolParameterT UnPack()
        {
            var _o = new BoolParameterT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(BoolParameterT _o)
        {
            _o.Name = this.Name;
            _o.Value = this.Value;
        }
        public static Offset<slug.fbs.srtf.BoolParameter> Pack(FlatBufferBuilder builder, BoolParameterT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.BoolParameter>);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            return CreateBoolParameter(
              builder,
              _name,
              _o.Value);
        }
    }

    public class BoolParameterT
    {
        public string Name { get; set; }
        public bool Value { get; set; }

        public BoolParameterT()
        {
            this.Name = null;
            this.Value = false;
        }
    }


    static public class BoolParameterVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Name*/, false)
              && verifier.VerifyField(tablePos, 6 /*Value*/, 1 /*bool*/, 1, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
