// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct ColorLayer : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
        public ColorLayer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public byte Name(int j) { return __p.bb.Get(__p.bb_pos + 0 + j * 1); }
        public void MutateName(int j, byte name) { __p.bb.Put(__p.bb_pos + 0 + j * 1, name); }
        public slug.fbs.srtf.Vector4 Color { get { return (new slug.fbs.srtf.Vector4()).__assign(__p.bb_pos + 64, __p.bb); } }

        public static Offset<slug.fbs.srtf.ColorLayer> CreateColorLayer(FlatBufferBuilder builder, byte[] Name, float color_X, float color_Y, float color_Z, float color_W)
        {
            builder.Prep(4, 80);
            builder.Prep(4, 16);
            builder.PutFloat(color_W);
            builder.PutFloat(color_Z);
            builder.PutFloat(color_Y);
            builder.PutFloat(color_X);
            for (int _idx0 = 64; _idx0 > 0; _idx0--)
            {
                builder.PutByte(Name[_idx0 - 1]);
            }
            return new Offset<slug.fbs.srtf.ColorLayer>(builder.Offset);
        }
        public ColorLayerT UnPack()
        {
            var _o = new ColorLayerT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(ColorLayerT _o)
        {
            _o.Name = new byte[64];
            for (var _j = 0; _j < 64; ++_j) { _o.Name[_j] = this.Name(_j); }
            _o.Color = this.Color.UnPack();
        }
        public static Offset<slug.fbs.srtf.ColorLayer> Pack(FlatBufferBuilder builder, ColorLayerT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.ColorLayer>);
            var _name = _o.Name;
            var _color_x = _o.Color.X;
            var _color_y = _o.Color.Y;
            var _color_z = _o.Color.Z;
            var _color_w = _o.Color.W;
            return CreateColorLayer(
              builder,
              _name,
              _color_x,
              _color_y,
              _color_z,
              _color_w);
        }
    }

    public class ColorLayerT
    {
        public byte[] Name { get; set; }
        public slug.fbs.srtf.Vector4T Color { get; set; }

        public ColorLayerT()
        {
            this.Name = new byte[64];
            this.Color = new slug.fbs.srtf.Vector4T();
        }
    }


}
