// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace slug.fbs.srtf
{

    public enum ConstantParameterType : byte
    {
        Bool = 0,
        Float = 1,
        FloatArray = 2,
        Vector2 = 3,
        Vector3 = 4,
        Vector4 = 5,
        Matrix3x3 = 6,
        Matrix4x4 = 7,
    };


}
