// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct ConstantParameter : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static ConstantParameter GetRootAsConstantParameter(ByteBuffer _bb) { return GetRootAsConstantParameter(_bb, new ConstantParameter()); }
        public static ConstantParameter GetRootAsConstantParameter(ByteBuffer _bb, ConstantParameter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public ConstantParameter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.ConstantBufferLayout? Layouts(int j) { int o = __p.__offset(4); return o != 0 ? (slug.fbs.srtf.ConstantBufferLayout?)(new slug.fbs.srtf.ConstantBufferLayout()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int LayoutsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.BoolParameter? BoolParameters(int j) { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.BoolParameter?)(new slug.fbs.srtf.BoolParameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int BoolParametersLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.FloatParameter? FloatParameters(int j) { int o = __p.__offset(8); return o != 0 ? (slug.fbs.srtf.FloatParameter?)(new slug.fbs.srtf.FloatParameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int FloatParametersLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.FloatArrayParameter? FloatArrayParameters(int j) { int o = __p.__offset(10); return o != 0 ? (slug.fbs.srtf.FloatArrayParameter?)(new slug.fbs.srtf.FloatArrayParameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int FloatArrayParametersLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.Vector2Parameter? Vector2Parameters(int j) { int o = __p.__offset(12); return o != 0 ? (slug.fbs.srtf.Vector2Parameter?)(new slug.fbs.srtf.Vector2Parameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int Vector2ParametersLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.Vector3Parameter? Vector3Parameters(int j) { int o = __p.__offset(14); return o != 0 ? (slug.fbs.srtf.Vector3Parameter?)(new slug.fbs.srtf.Vector3Parameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int Vector3ParametersLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.Vector4Parameter? Vector4Parameters(int j) { int o = __p.__offset(16); return o != 0 ? (slug.fbs.srtf.Vector4Parameter?)(new slug.fbs.srtf.Vector4Parameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int Vector4ParametersLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.Matrix3x3Parameter? Matrix3x3Parameters(int j) { int o = __p.__offset(18); return o != 0 ? (slug.fbs.srtf.Matrix3x3Parameter?)(new slug.fbs.srtf.Matrix3x3Parameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int Matrix3x3ParametersLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.Matrix4x4Parameter? Matrix4x4Parameters(int j) { int o = __p.__offset(20); return o != 0 ? (slug.fbs.srtf.Matrix4x4Parameter?)(new slug.fbs.srtf.Matrix4x4Parameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int Matrix4x4ParametersLength { get { int o = __p.__offset(20); return o != 0 ? __p.__vector_len(o) : 0; } }

        public static Offset<slug.fbs.srtf.ConstantParameter> CreateConstantParameter(FlatBufferBuilder builder,
            VectorOffset layoutsOffset = default(VectorOffset),
            VectorOffset bool_parametersOffset = default(VectorOffset),
            VectorOffset float_parametersOffset = default(VectorOffset),
            VectorOffset float_array_parametersOffset = default(VectorOffset),
            VectorOffset vector2_parametersOffset = default(VectorOffset),
            VectorOffset vector3_parametersOffset = default(VectorOffset),
            VectorOffset vector4_parametersOffset = default(VectorOffset),
            VectorOffset matrix3x3_parametersOffset = default(VectorOffset),
            VectorOffset matrix4x4_parametersOffset = default(VectorOffset))
        {
            builder.StartTable(9);
            ConstantParameter.AddMatrix4x4Parameters(builder, matrix4x4_parametersOffset);
            ConstantParameter.AddMatrix3x3Parameters(builder, matrix3x3_parametersOffset);
            ConstantParameter.AddVector4Parameters(builder, vector4_parametersOffset);
            ConstantParameter.AddVector3Parameters(builder, vector3_parametersOffset);
            ConstantParameter.AddVector2Parameters(builder, vector2_parametersOffset);
            ConstantParameter.AddFloatArrayParameters(builder, float_array_parametersOffset);
            ConstantParameter.AddFloatParameters(builder, float_parametersOffset);
            ConstantParameter.AddBoolParameters(builder, bool_parametersOffset);
            ConstantParameter.AddLayouts(builder, layoutsOffset);
            return ConstantParameter.EndConstantParameter(builder);
        }

        public static void StartConstantParameter(FlatBufferBuilder builder) { builder.StartTable(9); }
        public static void AddLayouts(FlatBufferBuilder builder, VectorOffset layoutsOffset) { builder.AddOffset(0, layoutsOffset.Value, 0); }
        public static VectorOffset CreateLayoutsVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ConstantBufferLayout>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateLayoutsVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ConstantBufferLayout>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateLayoutsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.ConstantBufferLayout>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateLayoutsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.ConstantBufferLayout>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartLayoutsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddBoolParameters(FlatBufferBuilder builder, VectorOffset boolParametersOffset) { builder.AddOffset(1, boolParametersOffset.Value, 0); }
        public static VectorOffset CreateBoolParametersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.BoolParameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateBoolParametersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.BoolParameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateBoolParametersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.BoolParameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateBoolParametersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.BoolParameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartBoolParametersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddFloatParameters(FlatBufferBuilder builder, VectorOffset floatParametersOffset) { builder.AddOffset(2, floatParametersOffset.Value, 0); }
        public static VectorOffset CreateFloatParametersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.FloatParameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateFloatParametersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.FloatParameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateFloatParametersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.FloatParameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateFloatParametersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.FloatParameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartFloatParametersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddFloatArrayParameters(FlatBufferBuilder builder, VectorOffset floatArrayParametersOffset) { builder.AddOffset(3, floatArrayParametersOffset.Value, 0); }
        public static VectorOffset CreateFloatArrayParametersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.FloatArrayParameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateFloatArrayParametersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.FloatArrayParameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateFloatArrayParametersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.FloatArrayParameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateFloatArrayParametersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.FloatArrayParameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartFloatArrayParametersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddVector2Parameters(FlatBufferBuilder builder, VectorOffset vector2ParametersOffset) { builder.AddOffset(4, vector2ParametersOffset.Value, 0); }
        public static VectorOffset CreateVector2ParametersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Vector2Parameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateVector2ParametersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Vector2Parameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVector2ParametersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.Vector2Parameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVector2ParametersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.Vector2Parameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartVector2ParametersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddVector3Parameters(FlatBufferBuilder builder, VectorOffset vector3ParametersOffset) { builder.AddOffset(5, vector3ParametersOffset.Value, 0); }
        public static VectorOffset CreateVector3ParametersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Vector3Parameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateVector3ParametersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Vector3Parameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVector3ParametersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.Vector3Parameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVector3ParametersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.Vector3Parameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartVector3ParametersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddVector4Parameters(FlatBufferBuilder builder, VectorOffset vector4ParametersOffset) { builder.AddOffset(6, vector4ParametersOffset.Value, 0); }
        public static VectorOffset CreateVector4ParametersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Vector4Parameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateVector4ParametersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Vector4Parameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVector4ParametersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.Vector4Parameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVector4ParametersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.Vector4Parameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartVector4ParametersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddMatrix3x3Parameters(FlatBufferBuilder builder, VectorOffset matrix3x3ParametersOffset) { builder.AddOffset(7, matrix3x3ParametersOffset.Value, 0); }
        public static VectorOffset CreateMatrix3x3ParametersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Matrix3x3Parameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateMatrix3x3ParametersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Matrix3x3Parameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateMatrix3x3ParametersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.Matrix3x3Parameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateMatrix3x3ParametersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.Matrix3x3Parameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartMatrix3x3ParametersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddMatrix4x4Parameters(FlatBufferBuilder builder, VectorOffset matrix4x4ParametersOffset) { builder.AddOffset(8, matrix4x4ParametersOffset.Value, 0); }
        public static VectorOffset CreateMatrix4x4ParametersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Matrix4x4Parameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateMatrix4x4ParametersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Matrix4x4Parameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateMatrix4x4ParametersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.Matrix4x4Parameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateMatrix4x4ParametersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.Matrix4x4Parameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartMatrix4x4ParametersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<slug.fbs.srtf.ConstantParameter> EndConstantParameter(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.ConstantParameter>(o);
        }
        public ConstantParameterT UnPack()
        {
            var _o = new ConstantParameterT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(ConstantParameterT _o)
        {
            _o.Layouts = new List<slug.fbs.srtf.ConstantBufferLayoutT>();
            for (var _j = 0; _j < this.LayoutsLength; ++_j) { _o.Layouts.Add(this.Layouts(_j).HasValue ? this.Layouts(_j).Value.UnPack() : null); }
            _o.BoolParameters = new List<slug.fbs.srtf.BoolParameterT>();
            for (var _j = 0; _j < this.BoolParametersLength; ++_j) { _o.BoolParameters.Add(this.BoolParameters(_j).HasValue ? this.BoolParameters(_j).Value.UnPack() : null); }
            _o.FloatParameters = new List<slug.fbs.srtf.FloatParameterT>();
            for (var _j = 0; _j < this.FloatParametersLength; ++_j) { _o.FloatParameters.Add(this.FloatParameters(_j).HasValue ? this.FloatParameters(_j).Value.UnPack() : null); }
            _o.FloatArrayParameters = new List<slug.fbs.srtf.FloatArrayParameterT>();
            for (var _j = 0; _j < this.FloatArrayParametersLength; ++_j) { _o.FloatArrayParameters.Add(this.FloatArrayParameters(_j).HasValue ? this.FloatArrayParameters(_j).Value.UnPack() : null); }
            _o.Vector2Parameters = new List<slug.fbs.srtf.Vector2ParameterT>();
            for (var _j = 0; _j < this.Vector2ParametersLength; ++_j) { _o.Vector2Parameters.Add(this.Vector2Parameters(_j).HasValue ? this.Vector2Parameters(_j).Value.UnPack() : null); }
            _o.Vector3Parameters = new List<slug.fbs.srtf.Vector3ParameterT>();
            for (var _j = 0; _j < this.Vector3ParametersLength; ++_j) { _o.Vector3Parameters.Add(this.Vector3Parameters(_j).HasValue ? this.Vector3Parameters(_j).Value.UnPack() : null); }
            _o.Vector4Parameters = new List<slug.fbs.srtf.Vector4ParameterT>();
            for (var _j = 0; _j < this.Vector4ParametersLength; ++_j) { _o.Vector4Parameters.Add(this.Vector4Parameters(_j).HasValue ? this.Vector4Parameters(_j).Value.UnPack() : null); }
            _o.Matrix3x3Parameters = new List<slug.fbs.srtf.Matrix3x3ParameterT>();
            for (var _j = 0; _j < this.Matrix3x3ParametersLength; ++_j) { _o.Matrix3x3Parameters.Add(this.Matrix3x3Parameters(_j).HasValue ? this.Matrix3x3Parameters(_j).Value.UnPack() : null); }
            _o.Matrix4x4Parameters = new List<slug.fbs.srtf.Matrix4x4ParameterT>();
            for (var _j = 0; _j < this.Matrix4x4ParametersLength; ++_j) { _o.Matrix4x4Parameters.Add(this.Matrix4x4Parameters(_j).HasValue ? this.Matrix4x4Parameters(_j).Value.UnPack() : null); }
        }
        public static Offset<slug.fbs.srtf.ConstantParameter> Pack(FlatBufferBuilder builder, ConstantParameterT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.ConstantParameter>);
            var _layouts = default(VectorOffset);
            if (_o.Layouts != null)
            {
                var __layouts = new Offset<slug.fbs.srtf.ConstantBufferLayout>[_o.Layouts.Count];
                for (var _j = 0; _j < __layouts.Length; ++_j) { __layouts[_j] = slug.fbs.srtf.ConstantBufferLayout.Pack(builder, _o.Layouts[_j]); }
                _layouts = CreateLayoutsVector(builder, __layouts);
            }
            var _bool_parameters = default(VectorOffset);
            if (_o.BoolParameters != null)
            {
                var __bool_parameters = new Offset<slug.fbs.srtf.BoolParameter>[_o.BoolParameters.Count];
                for (var _j = 0; _j < __bool_parameters.Length; ++_j) { __bool_parameters[_j] = slug.fbs.srtf.BoolParameter.Pack(builder, _o.BoolParameters[_j]); }
                _bool_parameters = CreateBoolParametersVector(builder, __bool_parameters);
            }
            var _float_parameters = default(VectorOffset);
            if (_o.FloatParameters != null)
            {
                var __float_parameters = new Offset<slug.fbs.srtf.FloatParameter>[_o.FloatParameters.Count];
                for (var _j = 0; _j < __float_parameters.Length; ++_j) { __float_parameters[_j] = slug.fbs.srtf.FloatParameter.Pack(builder, _o.FloatParameters[_j]); }
                _float_parameters = CreateFloatParametersVector(builder, __float_parameters);
            }
            var _float_array_parameters = default(VectorOffset);
            if (_o.FloatArrayParameters != null)
            {
                var __float_array_parameters = new Offset<slug.fbs.srtf.FloatArrayParameter>[_o.FloatArrayParameters.Count];
                for (var _j = 0; _j < __float_array_parameters.Length; ++_j) { __float_array_parameters[_j] = slug.fbs.srtf.FloatArrayParameter.Pack(builder, _o.FloatArrayParameters[_j]); }
                _float_array_parameters = CreateFloatArrayParametersVector(builder, __float_array_parameters);
            }
            var _vector2_parameters = default(VectorOffset);
            if (_o.Vector2Parameters != null)
            {
                var __vector2_parameters = new Offset<slug.fbs.srtf.Vector2Parameter>[_o.Vector2Parameters.Count];
                for (var _j = 0; _j < __vector2_parameters.Length; ++_j) { __vector2_parameters[_j] = slug.fbs.srtf.Vector2Parameter.Pack(builder, _o.Vector2Parameters[_j]); }
                _vector2_parameters = CreateVector2ParametersVector(builder, __vector2_parameters);
            }
            var _vector3_parameters = default(VectorOffset);
            if (_o.Vector3Parameters != null)
            {
                var __vector3_parameters = new Offset<slug.fbs.srtf.Vector3Parameter>[_o.Vector3Parameters.Count];
                for (var _j = 0; _j < __vector3_parameters.Length; ++_j) { __vector3_parameters[_j] = slug.fbs.srtf.Vector3Parameter.Pack(builder, _o.Vector3Parameters[_j]); }
                _vector3_parameters = CreateVector3ParametersVector(builder, __vector3_parameters);
            }
            var _vector4_parameters = default(VectorOffset);
            if (_o.Vector4Parameters != null)
            {
                var __vector4_parameters = new Offset<slug.fbs.srtf.Vector4Parameter>[_o.Vector4Parameters.Count];
                for (var _j = 0; _j < __vector4_parameters.Length; ++_j) { __vector4_parameters[_j] = slug.fbs.srtf.Vector4Parameter.Pack(builder, _o.Vector4Parameters[_j]); }
                _vector4_parameters = CreateVector4ParametersVector(builder, __vector4_parameters);
            }
            var _matrix3x3_parameters = default(VectorOffset);
            if (_o.Matrix3x3Parameters != null)
            {
                var __matrix3x3_parameters = new Offset<slug.fbs.srtf.Matrix3x3Parameter>[_o.Matrix3x3Parameters.Count];
                for (var _j = 0; _j < __matrix3x3_parameters.Length; ++_j) { __matrix3x3_parameters[_j] = slug.fbs.srtf.Matrix3x3Parameter.Pack(builder, _o.Matrix3x3Parameters[_j]); }
                _matrix3x3_parameters = CreateMatrix3x3ParametersVector(builder, __matrix3x3_parameters);
            }
            var _matrix4x4_parameters = default(VectorOffset);
            if (_o.Matrix4x4Parameters != null)
            {
                var __matrix4x4_parameters = new Offset<slug.fbs.srtf.Matrix4x4Parameter>[_o.Matrix4x4Parameters.Count];
                for (var _j = 0; _j < __matrix4x4_parameters.Length; ++_j) { __matrix4x4_parameters[_j] = slug.fbs.srtf.Matrix4x4Parameter.Pack(builder, _o.Matrix4x4Parameters[_j]); }
                _matrix4x4_parameters = CreateMatrix4x4ParametersVector(builder, __matrix4x4_parameters);
            }
            return CreateConstantParameter(
              builder,
              _layouts,
              _bool_parameters,
              _float_parameters,
              _float_array_parameters,
              _vector2_parameters,
              _vector3_parameters,
              _vector4_parameters,
              _matrix3x3_parameters,
              _matrix4x4_parameters);
        }
    }

    public class ConstantParameterT
    {
        public List<slug.fbs.srtf.ConstantBufferLayoutT> Layouts { get; set; }
        public List<slug.fbs.srtf.BoolParameterT> BoolParameters { get; set; }
        public List<slug.fbs.srtf.FloatParameterT> FloatParameters { get; set; }
        public List<slug.fbs.srtf.FloatArrayParameterT> FloatArrayParameters { get; set; }
        public List<slug.fbs.srtf.Vector2ParameterT> Vector2Parameters { get; set; }
        public List<slug.fbs.srtf.Vector3ParameterT> Vector3Parameters { get; set; }
        public List<slug.fbs.srtf.Vector4ParameterT> Vector4Parameters { get; set; }
        public List<slug.fbs.srtf.Matrix3x3ParameterT> Matrix3x3Parameters { get; set; }
        public List<slug.fbs.srtf.Matrix4x4ParameterT> Matrix4x4Parameters { get; set; }

        public ConstantParameterT()
        {
            this.Layouts = null;
            this.BoolParameters = null;
            this.FloatParameters = null;
            this.FloatArrayParameters = null;
            this.Vector2Parameters = null;
            this.Vector3Parameters = null;
            this.Vector4Parameters = null;
            this.Matrix3x3Parameters = null;
            this.Matrix4x4Parameters = null;
        }
    }


    static public class ConstantParameterVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyVectorOfTables(tablePos, 4 /*Layouts*/, slug.fbs.srtf.ConstantBufferLayoutVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 6 /*BoolParameters*/, slug.fbs.srtf.BoolParameterVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 8 /*FloatParameters*/, slug.fbs.srtf.FloatParameterVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 10 /*FloatArrayParameters*/, slug.fbs.srtf.FloatArrayParameterVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 12 /*Vector2Parameters*/, slug.fbs.srtf.Vector2ParameterVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 14 /*Vector3Parameters*/, slug.fbs.srtf.Vector3ParameterVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 16 /*Vector4Parameters*/, slug.fbs.srtf.Vector4ParameterVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 18 /*Matrix3x3Parameters*/, slug.fbs.srtf.Matrix3x3ParameterVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 20 /*Matrix4x4Parameters*/, slug.fbs.srtf.Matrix4x4ParameterVerify.Verify, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
