// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct ConstantBufferLayout : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static ConstantBufferLayout GetRootAsConstantBufferLayout(ByteBuffer _bb) { return GetRootAsConstantBufferLayout(_bb, new ConstantBufferLayout()); }
        public static ConstantBufferLayout GetRootAsConstantBufferLayout(ByteBuffer _bb, ConstantBufferLayout obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public ConstantBufferLayout __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string ParameterName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetParameterNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetParameterNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetParameterNameArray() { return __p.__vector_as_array<byte>(4); }
        public slug.fbs.srtf.ConstantParameterType Type { get { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.ConstantParameterType)__p.bb.Get(o + __p.bb_pos) : slug.fbs.srtf.ConstantParameterType.Bool; } }
        public bool MutateType(slug.fbs.srtf.ConstantParameterType type) { int o = __p.__offset(6); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)type); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.ConstantBufferLayout> CreateConstantBufferLayout(FlatBufferBuilder builder,
            StringOffset parameter_nameOffset = default(StringOffset),
            slug.fbs.srtf.ConstantParameterType type = slug.fbs.srtf.ConstantParameterType.Bool)
        {
            builder.StartTable(2);
            ConstantBufferLayout.AddParameterName(builder, parameter_nameOffset);
            ConstantBufferLayout.AddType(builder, type);
            return ConstantBufferLayout.EndConstantBufferLayout(builder);
        }

        public static void StartConstantBufferLayout(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddParameterName(FlatBufferBuilder builder, StringOffset parameterNameOffset) { builder.AddOffset(0, parameterNameOffset.Value, 0); }
        public static void AddType(FlatBufferBuilder builder, slug.fbs.srtf.ConstantParameterType type) { builder.AddByte(1, (byte)type, 0); }
        public static Offset<slug.fbs.srtf.ConstantBufferLayout> EndConstantBufferLayout(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.ConstantBufferLayout>(o);
        }
        public ConstantBufferLayoutT UnPack()
        {
            var _o = new ConstantBufferLayoutT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(ConstantBufferLayoutT _o)
        {
            _o.ParameterName = this.ParameterName;
            _o.Type = this.Type;
        }
        public static Offset<slug.fbs.srtf.ConstantBufferLayout> Pack(FlatBufferBuilder builder, ConstantBufferLayoutT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.ConstantBufferLayout>);
            var _parameter_name = _o.ParameterName == null ? default(StringOffset) : builder.CreateString(_o.ParameterName);
            return CreateConstantBufferLayout(
              builder,
              _parameter_name,
              _o.Type);
        }
    }

    public class ConstantBufferLayoutT
    {
        public string ParameterName { get; set; }
        public slug.fbs.srtf.ConstantParameterType Type { get; set; }

        public ConstantBufferLayoutT()
        {
            this.ParameterName = null;
            this.Type = slug.fbs.srtf.ConstantParameterType.Bool;
        }
    }


    static public class ConstantBufferLayoutVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*ParameterName*/, false)
              && verifier.VerifyField(tablePos, 6 /*Type*/, 1 /*slug.fbs.srtf.ConstantParameterType*/, 1, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
