// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct DrawSettings : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static DrawSettings GetRootAsDrawSettings(ByteBuffer _bb) { return GetRootAsDrawSettings(_bb, new DrawSettings()); }
        public static DrawSettings GetRootAsDrawSettings(ByteBuffer _bb, DrawSettings obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public DrawSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.BlendOptions Blend { get { int o = __p.__offset(4); return o != 0 ? (slug.fbs.srtf.BlendOptions)__p.bb.Get(o + __p.bb_pos) : slug.fbs.srtf.BlendOptions.Opaque; } }
        public bool MutateBlend(slug.fbs.srtf.BlendOptions blend) { int o = __p.__offset(4); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)blend); return true; } else { return false; } }
        public slug.fbs.srtf.ShadingModel? ShadingModel { get { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.ShadingModel?)(new slug.fbs.srtf.ShadingModel()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public slug.fbs.srtf.GiSettings? GiSettings { get { int o = __p.__offset(8); return o != 0 ? (slug.fbs.srtf.GiSettings?)(new slug.fbs.srtf.GiSettings()).__assign(o + __p.bb_pos, __p.bb) : null; } }
        public float AlphaThreshold { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
        public bool MutateAlphaThreshold(float alpha_threshold) { int o = __p.__offset(10); if (o != 0) { __p.bb.PutFloat(o + __p.bb_pos, alpha_threshold); return true; } else { return false; } }
        public int SortPriority { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public bool MutateSortPriority(int sort_priority) { int o = __p.__offset(12); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, sort_priority); return true; } else { return false; } }
        public bool TwoSide { get { int o = __p.__offset(14); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }
        public bool MutateTwoSide(bool two_side) { int o = __p.__offset(14); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(two_side ? 1 : 0)); return true; } else { return false; } }
        public bool AlphaToCoverage { get { int o = __p.__offset(16); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }
        public bool MutateAlphaToCoverage(bool alpha_to_coverage) { int o = __p.__offset(16); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(alpha_to_coverage ? 1 : 0)); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.DrawSettings> CreateDrawSettings(FlatBufferBuilder builder,
            slug.fbs.srtf.BlendOptions blend = slug.fbs.srtf.BlendOptions.Opaque,
            Offset<slug.fbs.srtf.ShadingModel> shading_modelOffset = default(Offset<slug.fbs.srtf.ShadingModel>),
            slug.fbs.srtf.GiSettingsT gi_settings = null,
            float alpha_threshold = 0.0f,
            int sort_priority = 0,
            bool two_side = false,
            bool alpha_to_coverage = false)
        {
            builder.StartTable(7);
            DrawSettings.AddSortPriority(builder, sort_priority);
            DrawSettings.AddAlphaThreshold(builder, alpha_threshold);
            DrawSettings.AddGiSettings(builder, slug.fbs.srtf.GiSettings.Pack(builder, gi_settings));
            DrawSettings.AddShadingModel(builder, shading_modelOffset);
            DrawSettings.AddAlphaToCoverage(builder, alpha_to_coverage);
            DrawSettings.AddTwoSide(builder, two_side);
            DrawSettings.AddBlend(builder, blend);
            return DrawSettings.EndDrawSettings(builder);
        }

        public static void StartDrawSettings(FlatBufferBuilder builder) { builder.StartTable(7); }
        public static void AddBlend(FlatBufferBuilder builder, slug.fbs.srtf.BlendOptions blend) { builder.AddByte(0, (byte)blend, 0); }
        public static void AddShadingModel(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShadingModel> shadingModelOffset) { builder.AddOffset(1, shadingModelOffset.Value, 0); }
        public static void AddGiSettings(FlatBufferBuilder builder, Offset<slug.fbs.srtf.GiSettings> giSettingsOffset) { builder.AddStruct(2, giSettingsOffset.Value, 0); }
        public static void AddAlphaThreshold(FlatBufferBuilder builder, float alphaThreshold) { builder.AddFloat(3, alphaThreshold, 0.0f); }
        public static void AddSortPriority(FlatBufferBuilder builder, int sortPriority) { builder.AddInt(4, sortPriority, 0); }
        public static void AddTwoSide(FlatBufferBuilder builder, bool twoSide) { builder.AddBool(5, twoSide, false); }
        public static void AddAlphaToCoverage(FlatBufferBuilder builder, bool alphaToCoverage) { builder.AddBool(6, alphaToCoverage, false); }
        public static Offset<slug.fbs.srtf.DrawSettings> EndDrawSettings(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.DrawSettings>(o);
        }
        public DrawSettingsT UnPack()
        {
            var _o = new DrawSettingsT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(DrawSettingsT _o)
        {
            _o.Blend = this.Blend;
            _o.ShadingModel = this.ShadingModel.HasValue ? this.ShadingModel.Value.UnPack() : null;
            _o.GiSettings = this.GiSettings.HasValue ? this.GiSettings.Value.UnPack() : null;
            _o.AlphaThreshold = this.AlphaThreshold;
            _o.SortPriority = this.SortPriority;
            _o.TwoSide = this.TwoSide;
            _o.AlphaToCoverage = this.AlphaToCoverage;
        }
        public static Offset<slug.fbs.srtf.DrawSettings> Pack(FlatBufferBuilder builder, DrawSettingsT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.DrawSettings>);
            var _shading_model = _o.ShadingModel == null ? default(Offset<slug.fbs.srtf.ShadingModel>) : slug.fbs.srtf.ShadingModel.Pack(builder, _o.ShadingModel);
            return CreateDrawSettings(
              builder,
              _o.Blend,
              _shading_model,
              _o.GiSettings,
              _o.AlphaThreshold,
              _o.SortPriority,
              _o.TwoSide,
              _o.AlphaToCoverage);
        }
    }

    public class DrawSettingsT
    {
        public slug.fbs.srtf.BlendOptions Blend { get; set; }
        public slug.fbs.srtf.ShadingModelT ShadingModel { get; set; }
        public slug.fbs.srtf.GiSettingsT GiSettings { get; set; }
        public float AlphaThreshold { get; set; }
        public int SortPriority { get; set; }
        public bool TwoSide { get; set; }
        public bool AlphaToCoverage { get; set; }

        public DrawSettingsT()
        {
            this.Blend = slug.fbs.srtf.BlendOptions.Opaque;
            this.ShadingModel = null;
            this.GiSettings = new slug.fbs.srtf.GiSettingsT();
            this.AlphaThreshold = 0.0f;
            this.SortPriority = 0;
            this.TwoSide = false;
            this.AlphaToCoverage = false;
        }
    }


    static public class DrawSettingsVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyField(tablePos, 4 /*Blend*/, 1 /*slug.fbs.srtf.BlendOptions*/, 1, false)
              && verifier.VerifyTable(tablePos, 6 /*ShadingModel*/, slug.fbs.srtf.ShadingModelVerify.Verify, false)
              && verifier.VerifyField(tablePos, 8 /*GiSettings*/, 8 /*slug.fbs.srtf.GiSettings*/, 4, false)
              && verifier.VerifyField(tablePos, 10 /*AlphaThreshold*/, 4 /*float*/, 4, false)
              && verifier.VerifyField(tablePos, 12 /*SortPriority*/, 4 /*int*/, 4, false)
              && verifier.VerifyField(tablePos, 14 /*TwoSide*/, 1 /*bool*/, 1, false)
              && verifier.VerifyField(tablePos, 16 /*AlphaToCoverage*/, 1 /*bool*/, 1, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
