// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct FloatParameter : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static FloatParameter GetRootAsFloatParameter(ByteBuffer _bb) { return GetRootAsFloatParameter(_bb, new FloatParameter()); }
        public static FloatParameter GetRootAsFloatParameter(ByteBuffer _bb, FloatParameter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public FloatParameter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public float Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
        public bool MutateValue(float value) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutFloat(o + __p.bb_pos, value); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.FloatParameter> CreateFloatParameter(FlatBufferBuilder builder,
            StringOffset nameOffset = default(StringOffset),
            float value = 0.0f)
        {
            builder.StartTable(2);
            FloatParameter.AddValue(builder, value);
            FloatParameter.AddName(builder, nameOffset);
            return FloatParameter.EndFloatParameter(builder);
        }

        public static void StartFloatParameter(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
        public static void AddValue(FlatBufferBuilder builder, float value) { builder.AddFloat(1, value, 0.0f); }
        public static Offset<slug.fbs.srtf.FloatParameter> EndFloatParameter(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.FloatParameter>(o);
        }
        public FloatParameterT UnPack()
        {
            var _o = new FloatParameterT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(FloatParameterT _o)
        {
            _o.Name = this.Name;
            _o.Value = this.Value;
        }
        public static Offset<slug.fbs.srtf.FloatParameter> Pack(FlatBufferBuilder builder, FloatParameterT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.FloatParameter>);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            return CreateFloatParameter(
              builder,
              _name,
              _o.Value);
        }
    }

    public class FloatParameterT
    {
        public string Name { get; set; }
        public float Value { get; set; }

        public FloatParameterT()
        {
            this.Name = null;
            this.Value = 0.0f;
        }
    }


    static public class FloatParameterVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Name*/, false)
              && verifier.VerifyField(tablePos, 6 /*Value*/, 4 /*float*/, 4, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
