// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct FloatArrayParameter : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static FloatArrayParameter GetRootAsFloatArrayParameter(ByteBuffer _bb) { return GetRootAsFloatArrayParameter(_bb, new FloatArrayParameter()); }
        public static FloatArrayParameter GetRootAsFloatArrayParameter(ByteBuffer _bb, FloatArrayParameter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public FloatArrayParameter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public float Value(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
        public int ValueLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetValueBytes() { return __p.__vector_as_span<float>(6, 4); }
#else
        public ArraySegment<byte>? GetValueBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public float[] GetValueArray() { return __p.__vector_as_array<float>(6); }
        public bool MutateValue(int j, float value) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutFloat(__p.__vector(o) + j * 4, value); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.FloatArrayParameter> CreateFloatArrayParameter(FlatBufferBuilder builder,
            StringOffset nameOffset = default(StringOffset),
            VectorOffset valueOffset = default(VectorOffset))
        {
            builder.StartTable(2);
            FloatArrayParameter.AddValue(builder, valueOffset);
            FloatArrayParameter.AddName(builder, nameOffset);
            return FloatArrayParameter.EndFloatArrayParameter(builder);
        }

        public static void StartFloatArrayParameter(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
        public static void AddValue(FlatBufferBuilder builder, VectorOffset valueOffset) { builder.AddOffset(1, valueOffset.Value, 0); }
        public static VectorOffset CreateValueVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
        public static VectorOffset CreateValueVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateValueVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateValueVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartValueVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<slug.fbs.srtf.FloatArrayParameter> EndFloatArrayParameter(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.FloatArrayParameter>(o);
        }
        public FloatArrayParameterT UnPack()
        {
            var _o = new FloatArrayParameterT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(FloatArrayParameterT _o)
        {
            _o.Name = this.Name;
            _o.Value = new List<float>();
            for (var _j = 0; _j < this.ValueLength; ++_j) { _o.Value.Add(this.Value(_j)); }
        }
        public static Offset<slug.fbs.srtf.FloatArrayParameter> Pack(FlatBufferBuilder builder, FloatArrayParameterT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.FloatArrayParameter>);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            var _value = default(VectorOffset);
            if (_o.Value != null)
            {
                var __value = _o.Value.ToArray();
                _value = CreateValueVector(builder, __value);
            }
            return CreateFloatArrayParameter(
              builder,
              _name,
              _value);
        }
    }

    public class FloatArrayParameterT
    {
        public string Name { get; set; }
        public List<float> Value { get; set; }

        public FloatArrayParameterT()
        {
            this.Name = null;
            this.Value = null;
        }
    }


    static public class FloatArrayParameterVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Name*/, false)
              && verifier.VerifyVectorOfData(tablePos, 6 /*Value*/, 4 /*float*/, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
