// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct GiSettings : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
        public GiSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public float DiffuseBoost { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
        public void MutateDiffuseBoost(float diffuse_boost) { __p.bb.PutFloat(__p.bb_pos + 0, diffuse_boost); }
        public float EmissiveBoost { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
        public void MutateEmissiveBoost(float emissive_boost) { __p.bb.PutFloat(__p.bb_pos + 4, emissive_boost); }

        public static Offset<slug.fbs.srtf.GiSettings> CreateGiSettings(FlatBufferBuilder builder, float DiffuseBoost, float EmissiveBoost)
        {
            builder.Prep(4, 8);
            builder.PutFloat(EmissiveBoost);
            builder.PutFloat(DiffuseBoost);
            return new Offset<slug.fbs.srtf.GiSettings>(builder.Offset);
        }
        public GiSettingsT UnPack()
        {
            var _o = new GiSettingsT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(GiSettingsT _o)
        {
            _o.DiffuseBoost = this.DiffuseBoost;
            _o.EmissiveBoost = this.EmissiveBoost;
        }
        public static Offset<slug.fbs.srtf.GiSettings> Pack(FlatBufferBuilder builder, GiSettingsT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.GiSettings>);
            return CreateGiSettings(
              builder,
              _o.DiffuseBoost,
              _o.EmissiveBoost);
        }
    }

    public class GiSettingsT
    {
        public float DiffuseBoost { get; set; }
        public float EmissiveBoost { get; set; }

        public GiSettingsT()
        {
            this.DiffuseBoost = 0.0f;
            this.EmissiveBoost = 0.0f;
        }
    }


}
