// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct indexAccessor : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static indexAccessor GetRootAsindexAccessor(ByteBuffer _bb) { return GetRootAsindexAccessor(_bb, new indexAccessor()); }
        public static indexAccessor GetRootAsindexAccessor(ByteBuffer _bb, indexAccessor obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public indexAccessor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.VertexFormat Foramt { get { int o = __p.__offset(4); return o != 0 ? (slug.fbs.srtf.VertexFormat)__p.bb.GetShort(o + __p.bb_pos) : slug.fbs.srtf.VertexFormat.NONE; } }
        public bool MutateForamt(slug.fbs.srtf.VertexFormat foramt) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutShort(o + __p.bb_pos, (short)foramt); return true; } else { return false; } }
        public uint Offset { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateOffset(uint offset) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, offset); return true; } else { return false; } }
        public uint Size { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateSize(uint size) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, size); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.indexAccessor> CreateindexAccessor(FlatBufferBuilder builder,
            slug.fbs.srtf.VertexFormat foramt = slug.fbs.srtf.VertexFormat.NONE,
            uint offset = 0,
            uint size = 0)
        {
            builder.StartTable(3);
            indexAccessor.AddSize(builder, size);
            indexAccessor.AddOffset(builder, offset);
            indexAccessor.AddForamt(builder, foramt);
            return indexAccessor.EndindexAccessor(builder);
        }

        public static void StartindexAccessor(FlatBufferBuilder builder) { builder.StartTable(3); }
        public static void AddForamt(FlatBufferBuilder builder, slug.fbs.srtf.VertexFormat foramt) { builder.AddShort(0, (short)foramt, 0); }
        public static void AddOffset(FlatBufferBuilder builder, uint offset) { builder.AddUint(1, offset, 0); }
        public static void AddSize(FlatBufferBuilder builder, uint size) { builder.AddUint(2, size, 0); }
        public static Offset<slug.fbs.srtf.indexAccessor> EndindexAccessor(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.indexAccessor>(o);
        }
        public indexAccessorT UnPack()
        {
            var _o = new indexAccessorT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(indexAccessorT _o)
        {
            _o.Foramt = this.Foramt;
            _o.Offset = this.Offset;
            _o.Size = this.Size;
        }
        public static Offset<slug.fbs.srtf.indexAccessor> Pack(FlatBufferBuilder builder, indexAccessorT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.indexAccessor>);
            return CreateindexAccessor(
              builder,
              _o.Foramt,
              _o.Offset,
              _o.Size);
        }
    }

    public class indexAccessorT
    {
        public slug.fbs.srtf.VertexFormat Foramt { get; set; }
        public uint Offset { get; set; }
        public uint Size { get; set; }

        public indexAccessorT()
        {
            this.Foramt = slug.fbs.srtf.VertexFormat.NONE;
            this.Offset = 0;
            this.Size = 0;
        }
    }


    static public class indexAccessorVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyField(tablePos, 4 /*Foramt*/, 2 /*slug.fbs.srtf.VertexFormat*/, 2, false)
              && verifier.VerifyField(tablePos, 6 /*Offset*/, 4 /*uint*/, 4, false)
              && verifier.VerifyField(tablePos, 8 /*Size*/, 4 /*uint*/, 4, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
