// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct LodItemSettings : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
        public LodItemSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public float DrawPixelAreaRatio { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
        public void MutateDrawPixelAreaRatio(float draw_pixel_area_ratio) { __p.bb.PutFloat(__p.bb_pos + 0, draw_pixel_area_ratio); }

        public static Offset<slug.fbs.srtf.LodItemSettings> CreateLodItemSettings(FlatBufferBuilder builder, float DrawPixelAreaRatio)
        {
            builder.Prep(4, 4);
            builder.PutFloat(DrawPixelAreaRatio);
            return new Offset<slug.fbs.srtf.LodItemSettings>(builder.Offset);
        }
        public LodItemSettingsT UnPack()
        {
            var _o = new LodItemSettingsT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(LodItemSettingsT _o)
        {
            _o.DrawPixelAreaRatio = this.DrawPixelAreaRatio;
        }
        public static Offset<slug.fbs.srtf.LodItemSettings> Pack(FlatBufferBuilder builder, LodItemSettingsT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.LodItemSettings>);
            return CreateLodItemSettings(
              builder,
              _o.DrawPixelAreaRatio);
        }
    }

    public class LodItemSettingsT
    {
        public float DrawPixelAreaRatio { get; set; }

        public LodItemSettingsT()
        {
            this.DrawPixelAreaRatio = 0.0f;
        }
    }


}
