// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct LodModel : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static LodModel GetRootAsLodModel(ByteBuffer _bb) { return GetRootAsLodModel(_bb, new LodModel()); }
        public static LodModel GetRootAsLodModel(ByteBuffer _bb, LodModel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public LodModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.LodSettings? LodSettings { get { int o = __p.__offset(4); return o != 0 ? (slug.fbs.srtf.LodSettings?)(new slug.fbs.srtf.LodSettings()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public slug.fbs.srtf.SubModel? SubModels(int j) { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.SubModel?)(new slug.fbs.srtf.SubModel()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int SubModelsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

        public static Offset<slug.fbs.srtf.LodModel> CreateLodModel(FlatBufferBuilder builder,
            Offset<slug.fbs.srtf.LodSettings> lod_settingsOffset = default(Offset<slug.fbs.srtf.LodSettings>),
            VectorOffset sub_modelsOffset = default(VectorOffset))
        {
            builder.StartTable(2);
            LodModel.AddSubModels(builder, sub_modelsOffset);
            LodModel.AddLodSettings(builder, lod_settingsOffset);
            return LodModel.EndLodModel(builder);
        }

        public static void StartLodModel(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddLodSettings(FlatBufferBuilder builder, Offset<slug.fbs.srtf.LodSettings> lodSettingsOffset) { builder.AddOffset(0, lodSettingsOffset.Value, 0); }
        public static void AddSubModels(FlatBufferBuilder builder, VectorOffset subModelsOffset) { builder.AddOffset(1, subModelsOffset.Value, 0); }
        public static VectorOffset CreateSubModelsVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.SubModel>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateSubModelsVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.SubModel>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateSubModelsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.SubModel>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateSubModelsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.SubModel>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartSubModelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<slug.fbs.srtf.LodModel> EndLodModel(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.LodModel>(o);
        }
        public LodModelT UnPack()
        {
            var _o = new LodModelT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(LodModelT _o)
        {
            _o.LodSettings = this.LodSettings.HasValue ? this.LodSettings.Value.UnPack() : null;
            _o.SubModels = new List<slug.fbs.srtf.SubModelT>();
            for (var _j = 0; _j < this.SubModelsLength; ++_j) { _o.SubModels.Add(this.SubModels(_j).HasValue ? this.SubModels(_j).Value.UnPack() : null); }
        }
        public static Offset<slug.fbs.srtf.LodModel> Pack(FlatBufferBuilder builder, LodModelT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.LodModel>);
            var _lod_settings = _o.LodSettings == null ? default(Offset<slug.fbs.srtf.LodSettings>) : slug.fbs.srtf.LodSettings.Pack(builder, _o.LodSettings);
            var _sub_models = default(VectorOffset);
            if (_o.SubModels != null)
            {
                var __sub_models = new Offset<slug.fbs.srtf.SubModel>[_o.SubModels.Count];
                for (var _j = 0; _j < __sub_models.Length; ++_j) { __sub_models[_j] = slug.fbs.srtf.SubModel.Pack(builder, _o.SubModels[_j]); }
                _sub_models = CreateSubModelsVector(builder, __sub_models);
            }
            return CreateLodModel(
              builder,
              _lod_settings,
              _sub_models);
        }
    }

    public class LodModelT
    {
        public slug.fbs.srtf.LodSettingsT LodSettings { get; set; }
        public List<slug.fbs.srtf.SubModelT> SubModels { get; set; }

        public LodModelT()
        {
            this.LodSettings = null;
            this.SubModels = null;
        }
    }


    static public class LodModelVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyTable(tablePos, 4 /*LodSettings*/, slug.fbs.srtf.LodSettingsVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 6 /*SubModels*/, slug.fbs.srtf.SubModelVerify.Verify, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
