// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct LodSettings : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static LodSettings GetRootAsLodSettings(ByteBuffer _bb) { return GetRootAsLodSettings(_bb, new LodSettings()); }
        public static LodSettings GetRootAsLodSettings(ByteBuffer _bb, LodSettings obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public LodSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public int OffsetLodIndex { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public bool MutateOffsetLodIndex(int offset_lod_index) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, offset_lod_index); return true; } else { return false; } }
        public slug.fbs.srtf.LodItemSettings? Items(int j) { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.LodItemSettings?)(new slug.fbs.srtf.LodItemSettings()).__assign(__p.__vector(o) + j * 4, __p.bb) : null; }
        public int ItemsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

        public static Offset<slug.fbs.srtf.LodSettings> CreateLodSettings(FlatBufferBuilder builder,
            int offset_lod_index = 0,
            VectorOffset itemsOffset = default(VectorOffset))
        {
            builder.StartTable(2);
            LodSettings.AddItems(builder, itemsOffset);
            LodSettings.AddOffsetLodIndex(builder, offset_lod_index);
            return LodSettings.EndLodSettings(builder);
        }

        public static void StartLodSettings(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddOffsetLodIndex(FlatBufferBuilder builder, int offsetLodIndex) { builder.AddInt(0, offsetLodIndex, 0); }
        public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(1, itemsOffset.Value, 0); }
        public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<slug.fbs.srtf.LodSettings> EndLodSettings(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.LodSettings>(o);
        }
        public LodSettingsT UnPack()
        {
            var _o = new LodSettingsT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(LodSettingsT _o)
        {
            _o.OffsetLodIndex = this.OffsetLodIndex;
            _o.Items = new List<slug.fbs.srtf.LodItemSettingsT>();
            for (var _j = 0; _j < this.ItemsLength; ++_j) { _o.Items.Add(this.Items(_j).HasValue ? this.Items(_j).Value.UnPack() : null); }
        }
        public static Offset<slug.fbs.srtf.LodSettings> Pack(FlatBufferBuilder builder, LodSettingsT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.LodSettings>);
            var _items = default(VectorOffset);
            if (_o.Items != null)
            {
                StartItemsVector(builder, _o.Items.Count);
                for (var _j = _o.Items.Count - 1; _j >= 0; --_j) { slug.fbs.srtf.LodItemSettings.Pack(builder, _o.Items[_j]); }
                _items = builder.EndVector();
            }
            return CreateLodSettings(
              builder,
              _o.OffsetLodIndex,
              _items);
        }
    }

    public class LodSettingsT
    {
        public int OffsetLodIndex { get; set; }
        public List<slug.fbs.srtf.LodItemSettingsT> Items { get; set; }

        public LodSettingsT()
        {
            this.OffsetLodIndex = 0;
            this.Items = null;
        }
    }


    static public class LodSettingsVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyField(tablePos, 4 /*OffsetLodIndex*/, 4 /*int*/, 4, false)
              && verifier.VerifyVectorOfData(tablePos, 6 /*Items*/, 4 /*slug.fbs.srtf.LodItemSettings*/, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
