// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct MaterialSlot : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static MaterialSlot GetRootAsMaterialSlot(ByteBuffer _bb) { return GetRootAsMaterialSlot(_bb, new MaterialSlot()); }
        public static MaterialSlot GetRootAsMaterialSlot(ByteBuffer _bb, MaterialSlot obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public MaterialSlot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Slot { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSlotBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetSlotBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetSlotArray() { return __p.__vector_as_array<byte>(4); }
        public string Material { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMaterialBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
        public ArraySegment<byte>? GetMaterialBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public byte[] GetMaterialArray() { return __p.__vector_as_array<byte>(6); }

        public static Offset<slug.fbs.srtf.MaterialSlot> CreateMaterialSlot(FlatBufferBuilder builder,
            StringOffset slotOffset = default(StringOffset),
            StringOffset materialOffset = default(StringOffset))
        {
            builder.StartTable(2);
            MaterialSlot.AddMaterial(builder, materialOffset);
            MaterialSlot.AddSlot(builder, slotOffset);
            return MaterialSlot.EndMaterialSlot(builder);
        }

        public static void StartMaterialSlot(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddSlot(FlatBufferBuilder builder, StringOffset slotOffset) { builder.AddOffset(0, slotOffset.Value, 0); }
        public static void AddMaterial(FlatBufferBuilder builder, StringOffset materialOffset) { builder.AddOffset(1, materialOffset.Value, 0); }
        public static Offset<slug.fbs.srtf.MaterialSlot> EndMaterialSlot(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.MaterialSlot>(o);
        }
        public MaterialSlotT UnPack()
        {
            var _o = new MaterialSlotT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(MaterialSlotT _o)
        {
            _o.Slot = this.Slot;
            _o.Material = this.Material;
        }
        public static Offset<slug.fbs.srtf.MaterialSlot> Pack(FlatBufferBuilder builder, MaterialSlotT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.MaterialSlot>);
            var _slot = _o.Slot == null ? default(StringOffset) : builder.CreateString(_o.Slot);
            var _material = _o.Material == null ? default(StringOffset) : builder.CreateString(_o.Material);
            return CreateMaterialSlot(
              builder,
              _slot,
              _material);
        }
    }

    public class MaterialSlotT
    {
        public string Slot { get; set; }
        public string Material { get; set; }

        public MaterialSlotT()
        {
            this.Slot = null;
            this.Material = null;
        }
    }


    static public class MaterialSlotVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Slot*/, false)
              && verifier.VerifyString(tablePos, 6 /*Material*/, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
