// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Material : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static Material GetRootAsMaterial(ByteBuffer _bb) { return GetRootAsMaterial(_bb, new Material()); }
        public static Material GetRootAsMaterial(ByteBuffer _bb, Material obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public static bool MaterialBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "MATE"); }
        public static bool VerifyMaterial(ByteBuffer _bb) { Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("MATE", false, MaterialVerify.Verify); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Material __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Shader { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetShaderBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetShaderBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetShaderArray() { return __p.__vector_as_array<byte>(4); }
        public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
        public slug.fbs.srtf.DrawSettings? DrawSettings { get { int o = __p.__offset(8); return o != 0 ? (slug.fbs.srtf.DrawSettings?)(new slug.fbs.srtf.DrawSettings()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public slug.fbs.srtf.TextureParameter? Textuers(int j) { int o = __p.__offset(10); return o != 0 ? (slug.fbs.srtf.TextureParameter?)(new slug.fbs.srtf.TextureParameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int TextuersLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.BoolParameter? StaticSwiches(int j) { int o = __p.__offset(12); return o != 0 ? (slug.fbs.srtf.BoolParameter?)(new slug.fbs.srtf.BoolParameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int StaticSwichesLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.ConstantParameter? ConstantParameter { get { int o = __p.__offset(14); return o != 0 ? (slug.fbs.srtf.ConstantParameter?)(new slug.fbs.srtf.ConstantParameter()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<slug.fbs.srtf.Material> CreateMaterial(FlatBufferBuilder builder,
            StringOffset shaderOffset = default(StringOffset),
            StringOffset nameOffset = default(StringOffset),
            Offset<slug.fbs.srtf.DrawSettings> draw_settingsOffset = default(Offset<slug.fbs.srtf.DrawSettings>),
            VectorOffset textuersOffset = default(VectorOffset),
            VectorOffset static_swichesOffset = default(VectorOffset),
            Offset<slug.fbs.srtf.ConstantParameter> constant_parameterOffset = default(Offset<slug.fbs.srtf.ConstantParameter>))
        {
            builder.StartTable(6);
            Material.AddConstantParameter(builder, constant_parameterOffset);
            Material.AddStaticSwiches(builder, static_swichesOffset);
            Material.AddTextuers(builder, textuersOffset);
            Material.AddDrawSettings(builder, draw_settingsOffset);
            Material.AddName(builder, nameOffset);
            Material.AddShader(builder, shaderOffset);
            return Material.EndMaterial(builder);
        }

        public static void StartMaterial(FlatBufferBuilder builder) { builder.StartTable(6); }
        public static void AddShader(FlatBufferBuilder builder, StringOffset shaderOffset) { builder.AddOffset(0, shaderOffset.Value, 0); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
        public static void AddDrawSettings(FlatBufferBuilder builder, Offset<slug.fbs.srtf.DrawSettings> drawSettingsOffset) { builder.AddOffset(2, drawSettingsOffset.Value, 0); }
        public static void AddTextuers(FlatBufferBuilder builder, VectorOffset textuersOffset) { builder.AddOffset(3, textuersOffset.Value, 0); }
        public static VectorOffset CreateTextuersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.TextureParameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateTextuersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.TextureParameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateTextuersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.TextureParameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateTextuersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.TextureParameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartTextuersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddStaticSwiches(FlatBufferBuilder builder, VectorOffset staticSwichesOffset) { builder.AddOffset(4, staticSwichesOffset.Value, 0); }
        public static VectorOffset CreateStaticSwichesVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.BoolParameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateStaticSwichesVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.BoolParameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateStaticSwichesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.BoolParameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateStaticSwichesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.BoolParameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartStaticSwichesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddConstantParameter(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ConstantParameter> constantParameterOffset) { builder.AddOffset(5, constantParameterOffset.Value, 0); }
        public static Offset<slug.fbs.srtf.Material> EndMaterial(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.Material>(o);
        }
        public static void FinishMaterialBuffer(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Material> offset) { builder.Finish(offset.Value, "MATE"); }
        public static void FinishSizePrefixedMaterialBuffer(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Material> offset) { builder.FinishSizePrefixed(offset.Value, "MATE"); }
        public MaterialT UnPack()
        {
            var _o = new MaterialT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(MaterialT _o)
        {
            _o.Shader = this.Shader;
            _o.Name = this.Name;
            _o.DrawSettings = this.DrawSettings.HasValue ? this.DrawSettings.Value.UnPack() : null;
            _o.Textuers = new List<slug.fbs.srtf.TextureParameterT>();
            for (var _j = 0; _j < this.TextuersLength; ++_j) { _o.Textuers.Add(this.Textuers(_j).HasValue ? this.Textuers(_j).Value.UnPack() : null); }
            _o.StaticSwiches = new List<slug.fbs.srtf.BoolParameterT>();
            for (var _j = 0; _j < this.StaticSwichesLength; ++_j) { _o.StaticSwiches.Add(this.StaticSwiches(_j).HasValue ? this.StaticSwiches(_j).Value.UnPack() : null); }
            _o.ConstantParameter = this.ConstantParameter.HasValue ? this.ConstantParameter.Value.UnPack() : null;
        }
        public static Offset<slug.fbs.srtf.Material> Pack(FlatBufferBuilder builder, MaterialT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Material>);
            var _shader = _o.Shader == null ? default(StringOffset) : builder.CreateString(_o.Shader);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            var _draw_settings = _o.DrawSettings == null ? default(Offset<slug.fbs.srtf.DrawSettings>) : slug.fbs.srtf.DrawSettings.Pack(builder, _o.DrawSettings);
            var _textuers = default(VectorOffset);
            if (_o.Textuers != null)
            {
                var __textuers = new Offset<slug.fbs.srtf.TextureParameter>[_o.Textuers.Count];
                for (var _j = 0; _j < __textuers.Length; ++_j) { __textuers[_j] = slug.fbs.srtf.TextureParameter.Pack(builder, _o.Textuers[_j]); }
                _textuers = CreateTextuersVector(builder, __textuers);
            }
            var _static_swiches = default(VectorOffset);
            if (_o.StaticSwiches != null)
            {
                var __static_swiches = new Offset<slug.fbs.srtf.BoolParameter>[_o.StaticSwiches.Count];
                for (var _j = 0; _j < __static_swiches.Length; ++_j) { __static_swiches[_j] = slug.fbs.srtf.BoolParameter.Pack(builder, _o.StaticSwiches[_j]); }
                _static_swiches = CreateStaticSwichesVector(builder, __static_swiches);
            }
            var _constant_parameter = _o.ConstantParameter == null ? default(Offset<slug.fbs.srtf.ConstantParameter>) : slug.fbs.srtf.ConstantParameter.Pack(builder, _o.ConstantParameter);
            return CreateMaterial(
              builder,
              _shader,
              _name,
              _draw_settings,
              _textuers,
              _static_swiches,
              _constant_parameter);
        }
    }

    public class MaterialT
    {
        public string Shader { get; set; }
        public string Name { get; set; }
        public slug.fbs.srtf.DrawSettingsT DrawSettings { get; set; }
        public List<slug.fbs.srtf.TextureParameterT> Textuers { get; set; }
        public List<slug.fbs.srtf.BoolParameterT> StaticSwiches { get; set; }
        public slug.fbs.srtf.ConstantParameterT ConstantParameter { get; set; }

        public MaterialT()
        {
            this.Shader = null;
            this.Name = null;
            this.DrawSettings = null;
            this.Textuers = null;
            this.StaticSwiches = null;
            this.ConstantParameter = null;
        }
        public static MaterialT DeserializeFromBinary(byte[] fbBuffer)
        {
            return Material.GetRootAsMaterial(new ByteBuffer(fbBuffer)).UnPack();
        }
        public byte[] SerializeToBinary()
        {
            var fbb = new FlatBufferBuilder(0x10000);
            Material.FinishMaterialBuffer(fbb, Material.Pack(fbb, this));
            return fbb.DataBuffer.ToSizedArray();
        }
    }


    static public class MaterialVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Shader*/, false)
              && verifier.VerifyString(tablePos, 6 /*Name*/, false)
              && verifier.VerifyTable(tablePos, 8 /*DrawSettings*/, slug.fbs.srtf.DrawSettingsVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 10 /*Textuers*/, slug.fbs.srtf.TextureParameterVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 12 /*StaticSwiches*/, slug.fbs.srtf.BoolParameterVerify.Verify, false)
              && verifier.VerifyTable(tablePos, 14 /*ConstantParameter*/, slug.fbs.srtf.ConstantParameterVerify.Verify, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
