// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Matrix3x3 : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
        public Matrix3x3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public float M(int j) { return __p.bb.GetFloat(__p.bb_pos + 0 + j * 4); }
        public void MutateM(int j, float m) { __p.bb.PutFloat(__p.bb_pos + 0 + j * 4, m); }

        public static Offset<slug.fbs.srtf.Matrix3x3> CreateMatrix3x3(FlatBufferBuilder builder, float[] M)
        {
            builder.Prep(4, 36);
            for (int _idx0 = 9; _idx0 > 0; _idx0--)
            {
                builder.PutFloat(M[_idx0 - 1]);
            }
            return new Offset<slug.fbs.srtf.Matrix3x3>(builder.Offset);
        }
        public Matrix3x3T UnPack()
        {
            var _o = new Matrix3x3T();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(Matrix3x3T _o)
        {
            _o.M = new float[9];
            for (var _j = 0; _j < 9; ++_j) { _o.M[_j] = this.M(_j); }
        }
        public static Offset<slug.fbs.srtf.Matrix3x3> Pack(FlatBufferBuilder builder, Matrix3x3T _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Matrix3x3>);
            var _m = _o.M;
            return CreateMatrix3x3(
              builder,
              _m);
        }
    }

    public class Matrix3x3T
    {
        public float[] M { get; set; }

        public Matrix3x3T()
        {
            this.M = new float[9];
        }
    }


}
