// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Matrix4x4Parameter : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static Matrix4x4Parameter GetRootAsMatrix4x4Parameter(ByteBuffer _bb) { return GetRootAsMatrix4x4Parameter(_bb, new Matrix4x4Parameter()); }
        public static Matrix4x4Parameter GetRootAsMatrix4x4Parameter(ByteBuffer _bb, Matrix4x4Parameter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Matrix4x4Parameter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public slug.fbs.srtf.Matrix4x4? Value { get { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.Matrix4x4?)(new slug.fbs.srtf.Matrix4x4()).__assign(o + __p.bb_pos, __p.bb) : null; } }

        public static Offset<slug.fbs.srtf.Matrix4x4Parameter> CreateMatrix4x4Parameter(FlatBufferBuilder builder,
            StringOffset nameOffset = default(StringOffset),
            slug.fbs.srtf.Matrix4x4T value = null)
        {
            builder.StartTable(2);
            Matrix4x4Parameter.AddValue(builder, slug.fbs.srtf.Matrix4x4.Pack(builder, value));
            Matrix4x4Parameter.AddName(builder, nameOffset);
            return Matrix4x4Parameter.EndMatrix4x4Parameter(builder);
        }

        public static void StartMatrix4x4Parameter(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
        public static void AddValue(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Matrix4x4> valueOffset) { builder.AddStruct(1, valueOffset.Value, 0); }
        public static Offset<slug.fbs.srtf.Matrix4x4Parameter> EndMatrix4x4Parameter(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.Matrix4x4Parameter>(o);
        }
        public Matrix4x4ParameterT UnPack()
        {
            var _o = new Matrix4x4ParameterT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(Matrix4x4ParameterT _o)
        {
            _o.Name = this.Name;
            _o.Value = this.Value.HasValue ? this.Value.Value.UnPack() : null;
        }
        public static Offset<slug.fbs.srtf.Matrix4x4Parameter> Pack(FlatBufferBuilder builder, Matrix4x4ParameterT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Matrix4x4Parameter>);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            return CreateMatrix4x4Parameter(
              builder,
              _name,
              _o.Value);
        }
    }

    public class Matrix4x4ParameterT
    {
        public string Name { get; set; }
        public slug.fbs.srtf.Matrix4x4T Value { get; set; }

        public Matrix4x4ParameterT()
        {
            this.Name = null;
            this.Value = new slug.fbs.srtf.Matrix4x4T();
        }
    }


    static public class Matrix4x4ParameterVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Name*/, false)
              && verifier.VerifyField(tablePos, 6 /*Value*/, 64 /*slug.fbs.srtf.Matrix4x4*/, 4, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
