// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Matrix4x4 : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
        public Matrix4x4 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public float M(int j) { return __p.bb.GetFloat(__p.bb_pos + 0 + j * 4); }
        public void MutateM(int j, float m) { __p.bb.PutFloat(__p.bb_pos + 0 + j * 4, m); }

        public static Offset<slug.fbs.srtf.Matrix4x4> CreateMatrix4x4(FlatBufferBuilder builder, float[] M)
        {
            builder.Prep(4, 64);
            for (int _idx0 = 16; _idx0 > 0; _idx0--)
            {
                builder.PutFloat(M[_idx0 - 1]);
            }
            return new Offset<slug.fbs.srtf.Matrix4x4>(builder.Offset);
        }
        public Matrix4x4T UnPack()
        {
            var _o = new Matrix4x4T();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(Matrix4x4T _o)
        {
            _o.M = new float[16];
            for (var _j = 0; _j < 16; ++_j) { _o.M[_j] = this.M(_j); }
        }
        public static Offset<slug.fbs.srtf.Matrix4x4> Pack(FlatBufferBuilder builder, Matrix4x4T _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Matrix4x4>);
            var _m = _o.M;
            return CreateMatrix4x4(
              builder,
              _m);
        }
    }

    public class Matrix4x4T
    {
        public float[] M { get; set; }

        public Matrix4x4T()
        {
            this.M = new float[16];
        }
    }


}
