// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Matrix3x3Parameter : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static Matrix3x3Parameter GetRootAsMatrix3x3Parameter(ByteBuffer _bb) { return GetRootAsMatrix3x3Parameter(_bb, new Matrix3x3Parameter()); }
        public static Matrix3x3Parameter GetRootAsMatrix3x3Parameter(ByteBuffer _bb, Matrix3x3Parameter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Matrix3x3Parameter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public slug.fbs.srtf.Matrix3x3? Value { get { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.Matrix3x3?)(new slug.fbs.srtf.Matrix3x3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

        public static Offset<slug.fbs.srtf.Matrix3x3Parameter> CreateMatrix3x3Parameter(FlatBufferBuilder builder,
            StringOffset nameOffset = default(StringOffset),
            slug.fbs.srtf.Matrix3x3T value = null)
        {
            builder.StartTable(2);
            Matrix3x3Parameter.AddValue(builder, slug.fbs.srtf.Matrix3x3.Pack(builder, value));
            Matrix3x3Parameter.AddName(builder, nameOffset);
            return Matrix3x3Parameter.EndMatrix3x3Parameter(builder);
        }

        public static void StartMatrix3x3Parameter(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
        public static void AddValue(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Matrix3x3> valueOffset) { builder.AddStruct(1, valueOffset.Value, 0); }
        public static Offset<slug.fbs.srtf.Matrix3x3Parameter> EndMatrix3x3Parameter(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.Matrix3x3Parameter>(o);
        }
        public Matrix3x3ParameterT UnPack()
        {
            var _o = new Matrix3x3ParameterT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(Matrix3x3ParameterT _o)
        {
            _o.Name = this.Name;
            _o.Value = this.Value.HasValue ? this.Value.Value.UnPack() : null;
        }
        public static Offset<slug.fbs.srtf.Matrix3x3Parameter> Pack(FlatBufferBuilder builder, Matrix3x3ParameterT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Matrix3x3Parameter>);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            return CreateMatrix3x3Parameter(
              builder,
              _name,
              _o.Value);
        }
    }

    public class Matrix3x3ParameterT
    {
        public string Name { get; set; }
        public slug.fbs.srtf.Matrix3x3T Value { get; set; }

        public Matrix3x3ParameterT()
        {
            this.Name = null;
            this.Value = new slug.fbs.srtf.Matrix3x3T();
        }
    }


    static public class Matrix3x3ParameterVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Name*/, false)
              && verifier.VerifyField(tablePos, 6 /*Value*/, 36 /*slug.fbs.srtf.Matrix3x3*/, 4, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
