// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Mesh : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static Mesh GetRootAsMesh(ByteBuffer _bb) { return GetRootAsMesh(_bb, new Mesh()); }
        public static Mesh GetRootAsMesh(ByteBuffer _bb, Mesh obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Mesh __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.Vertex? Vertices(int j) { int o = __p.__offset(4); return o != 0 ? (slug.fbs.srtf.Vertex?)(new slug.fbs.srtf.Vertex()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int VerticesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
        public uint Indices(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
        public int IndicesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetIndicesBytes() { return __p.__vector_as_span<uint>(6, 4); }
#else
        public ArraySegment<byte>? GetIndicesBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public uint[] GetIndicesArray() { return __p.__vector_as_array<uint>(6); }
        public bool MutateIndices(int j, uint indices) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutUint(__p.__vector(o) + j * 4, indices); return true; } else { return false; } }
        public uint Material { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateMaterial(uint material) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, material); return true; } else { return false; } }
        public uint Node { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateNode(uint node) { int o = __p.__offset(10); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, node); return true; } else { return false; } }
        public slug.fbs.srtf.AABB? Aabb { get { int o = __p.__offset(12); return o != 0 ? (slug.fbs.srtf.AABB?)(new slug.fbs.srtf.AABB()).__assign(o + __p.bb_pos, __p.bb) : null; } }

        public static Offset<slug.fbs.srtf.Mesh> CreateMesh(FlatBufferBuilder builder,
            VectorOffset verticesOffset = default(VectorOffset),
            VectorOffset indicesOffset = default(VectorOffset),
            uint material = 0,
            uint node = 0,
            slug.fbs.srtf.AABBT aabb = null)
        {
            builder.StartTable(5);
            Mesh.AddAabb(builder, slug.fbs.srtf.AABB.Pack(builder, aabb));
            Mesh.AddNode(builder, node);
            Mesh.AddMaterial(builder, material);
            Mesh.AddIndices(builder, indicesOffset);
            Mesh.AddVertices(builder, verticesOffset);
            return Mesh.EndMesh(builder);
        }

        public static void StartMesh(FlatBufferBuilder builder) { builder.StartTable(5); }
        public static void AddVertices(FlatBufferBuilder builder, VectorOffset verticesOffset) { builder.AddOffset(0, verticesOffset.Value, 0); }
        public static VectorOffset CreateVerticesVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Vertex>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateVerticesVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Vertex>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVerticesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.Vertex>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVerticesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.Vertex>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartVerticesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddIndices(FlatBufferBuilder builder, VectorOffset indicesOffset) { builder.AddOffset(1, indicesOffset.Value, 0); }
        public static VectorOffset CreateIndicesVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
        public static VectorOffset CreateIndicesVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateIndicesVectorBlock(FlatBufferBuilder builder, ArraySegment<uint> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateIndicesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<uint>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartIndicesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddMaterial(FlatBufferBuilder builder, uint material) { builder.AddUint(2, material, 0); }
        public static void AddNode(FlatBufferBuilder builder, uint node) { builder.AddUint(3, node, 0); }
        public static void AddAabb(FlatBufferBuilder builder, Offset<slug.fbs.srtf.AABB> aabbOffset) { builder.AddStruct(4, aabbOffset.Value, 0); }
        public static Offset<slug.fbs.srtf.Mesh> EndMesh(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.Mesh>(o);
        }
        public MeshT UnPack()
        {
            var _o = new MeshT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(MeshT _o)
        {
            _o.Vertices = new List<slug.fbs.srtf.VertexT>();
            for (var _j = 0; _j < this.VerticesLength; ++_j) { _o.Vertices.Add(this.Vertices(_j).HasValue ? this.Vertices(_j).Value.UnPack() : null); }
            _o.Indices = new List<uint>();
            for (var _j = 0; _j < this.IndicesLength; ++_j) { _o.Indices.Add(this.Indices(_j)); }
            _o.Material = this.Material;
            _o.Node = this.Node;
            _o.Aabb = this.Aabb.HasValue ? this.Aabb.Value.UnPack() : null;
        }
        public static Offset<slug.fbs.srtf.Mesh> Pack(FlatBufferBuilder builder, MeshT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Mesh>);
            var _vertices = default(VectorOffset);
            if (_o.Vertices != null)
            {
                var __vertices = new Offset<slug.fbs.srtf.Vertex>[_o.Vertices.Count];
                for (var _j = 0; _j < __vertices.Length; ++_j) { __vertices[_j] = slug.fbs.srtf.Vertex.Pack(builder, _o.Vertices[_j]); }
                _vertices = CreateVerticesVector(builder, __vertices);
            }
            var _indices = default(VectorOffset);
            if (_o.Indices != null)
            {
                var __indices = _o.Indices.ToArray();
                _indices = CreateIndicesVector(builder, __indices);
            }
            return CreateMesh(
              builder,
              _vertices,
              _indices,
              _o.Material,
              _o.Node,
              _o.Aabb);
        }
    }

    public class MeshT
    {
        public List<slug.fbs.srtf.VertexT> Vertices { get; set; }
        public List<uint> Indices { get; set; }
        public uint Material { get; set; }
        public uint Node { get; set; }
        public slug.fbs.srtf.AABBT Aabb { get; set; }

        public MeshT()
        {
            this.Vertices = null;
            this.Indices = null;
            this.Material = 0;
            this.Node = 0;
            this.Aabb = new slug.fbs.srtf.AABBT();
        }
    }


    static public class MeshVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyVectorOfTables(tablePos, 4 /*Vertices*/, slug.fbs.srtf.VertexVerify.Verify, false)
              && verifier.VerifyVectorOfData(tablePos, 6 /*Indices*/, 4 /*uint*/, false)
              && verifier.VerifyField(tablePos, 8 /*Material*/, 4 /*uint*/, 4, false)
              && verifier.VerifyField(tablePos, 10 /*Node*/, 4 /*uint*/, 4, false)
              && verifier.VerifyField(tablePos, 12 /*Aabb*/, 24 /*slug.fbs.srtf.AABB*/, 4, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
