// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Model : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static Model GetRootAsModel(ByteBuffer _bb) { return GetRootAsModel(_bb, new Model()); }
        public static Model GetRootAsModel(ByteBuffer _bb, Model obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public static bool ModelBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "MODL"); }
        public static bool VerifyModel(ByteBuffer _bb) { Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("MODL", false, ModelVerify.Verify); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Model __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.SubModel? MainModel { get { int o = __p.__offset(4); return o != 0 ? (slug.fbs.srtf.SubModel?)(new slug.fbs.srtf.SubModel()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public slug.fbs.srtf.LodModel? LodModel { get { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.LodModel?)(new slug.fbs.srtf.LodModel()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<slug.fbs.srtf.Model> CreateModel(FlatBufferBuilder builder,
            Offset<slug.fbs.srtf.SubModel> main_modelOffset = default(Offset<slug.fbs.srtf.SubModel>),
            Offset<slug.fbs.srtf.LodModel> lod_modelOffset = default(Offset<slug.fbs.srtf.LodModel>))
        {
            builder.StartTable(2);
            Model.AddLodModel(builder, lod_modelOffset);
            Model.AddMainModel(builder, main_modelOffset);
            return Model.EndModel(builder);
        }

        public static void StartModel(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddMainModel(FlatBufferBuilder builder, Offset<slug.fbs.srtf.SubModel> mainModelOffset) { builder.AddOffset(0, mainModelOffset.Value, 0); }
        public static void AddLodModel(FlatBufferBuilder builder, Offset<slug.fbs.srtf.LodModel> lodModelOffset) { builder.AddOffset(1, lodModelOffset.Value, 0); }
        public static Offset<slug.fbs.srtf.Model> EndModel(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.Model>(o);
        }
        public static void FinishModelBuffer(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Model> offset) { builder.Finish(offset.Value, "MODL"); }
        public static void FinishSizePrefixedModelBuffer(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Model> offset) { builder.FinishSizePrefixed(offset.Value, "MODL"); }
        public ModelT UnPack()
        {
            var _o = new ModelT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(ModelT _o)
        {
            _o.MainModel = this.MainModel.HasValue ? this.MainModel.Value.UnPack() : null;
            _o.LodModel = this.LodModel.HasValue ? this.LodModel.Value.UnPack() : null;
        }
        public static Offset<slug.fbs.srtf.Model> Pack(FlatBufferBuilder builder, ModelT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Model>);
            var _main_model = _o.MainModel == null ? default(Offset<slug.fbs.srtf.SubModel>) : slug.fbs.srtf.SubModel.Pack(builder, _o.MainModel);
            var _lod_model = _o.LodModel == null ? default(Offset<slug.fbs.srtf.LodModel>) : slug.fbs.srtf.LodModel.Pack(builder, _o.LodModel);
            return CreateModel(
              builder,
              _main_model,
              _lod_model);
        }
    }

    public class ModelT
    {
        public slug.fbs.srtf.SubModelT MainModel { get; set; }
        public slug.fbs.srtf.LodModelT LodModel { get; set; }

        public ModelT()
        {
            this.MainModel = null;
            this.LodModel = null;
        }
        public static ModelT DeserializeFromBinary(byte[] fbBuffer)
        {
            return Model.GetRootAsModel(new ByteBuffer(fbBuffer)).UnPack();
        }
        public byte[] SerializeToBinary()
        {
            var fbb = new FlatBufferBuilder(0x10000);
            Model.FinishModelBuffer(fbb, Model.Pack(fbb, this));
            return fbb.DataBuffer.ToSizedArray();
        }
    }


    static public class ModelVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyTable(tablePos, 4 /*MainModel*/, slug.fbs.srtf.SubModelVerify.Verify, false)
              && verifier.VerifyTable(tablePos, 6 /*LodModel*/, slug.fbs.srtf.LodModelVerify.Verify, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
