// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Node : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static Node GetRootAsNode(ByteBuffer _bb) { return GetRootAsNode(_bb, new Node()); }
        public static Node GetRootAsNode(ByteBuffer _bb, Node obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Node __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public int Parent { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public bool MutateParent(int parent) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, parent); return true; } else { return false; } }
        public slug.fbs.srtf.Matrix4x4? Bindpose { get { int o = __p.__offset(8); return o != 0 ? (slug.fbs.srtf.Matrix4x4?)(new slug.fbs.srtf.Matrix4x4()).__assign(o + __p.bb_pos, __p.bb) : null; } }

        public static Offset<slug.fbs.srtf.Node> CreateNode(FlatBufferBuilder builder,
            StringOffset nameOffset = default(StringOffset),
            int parent = 0,
            slug.fbs.srtf.Matrix4x4T bindpose = null)
        {
            builder.StartTable(3);
            Node.AddBindpose(builder, slug.fbs.srtf.Matrix4x4.Pack(builder, bindpose));
            Node.AddParent(builder, parent);
            Node.AddName(builder, nameOffset);
            return Node.EndNode(builder);
        }

        public static void StartNode(FlatBufferBuilder builder) { builder.StartTable(3); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
        public static void AddParent(FlatBufferBuilder builder, int parent) { builder.AddInt(1, parent, 0); }
        public static void AddBindpose(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Matrix4x4> bindposeOffset) { builder.AddStruct(2, bindposeOffset.Value, 0); }
        public static Offset<slug.fbs.srtf.Node> EndNode(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.Node>(o);
        }
        public NodeT UnPack()
        {
            var _o = new NodeT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(NodeT _o)
        {
            _o.Name = this.Name;
            _o.Parent = this.Parent;
            _o.Bindpose = this.Bindpose.HasValue ? this.Bindpose.Value.UnPack() : null;
        }
        public static Offset<slug.fbs.srtf.Node> Pack(FlatBufferBuilder builder, NodeT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Node>);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            return CreateNode(
              builder,
              _name,
              _o.Parent,
              _o.Bindpose);
        }
    }

    public class NodeT
    {
        public string Name { get; set; }
        public int Parent { get; set; }
        public slug.fbs.srtf.Matrix4x4T Bindpose { get; set; }

        public NodeT()
        {
            this.Name = null;
            this.Parent = 0;
            this.Bindpose = new slug.fbs.srtf.Matrix4x4T();
        }
    }


    static public class NodeVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Name*/, false)
              && verifier.VerifyField(tablePos, 6 /*Parent*/, 4 /*int*/, 4, false)
              && verifier.VerifyField(tablePos, 8 /*Bindpose*/, 64 /*slug.fbs.srtf.Matrix4x4*/, 4, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
