// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct OptimizeMeshBuffer : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static OptimizeMeshBuffer GetRootAsOptimizeMeshBuffer(ByteBuffer _bb) { return GetRootAsOptimizeMeshBuffer(_bb, new OptimizeMeshBuffer()); }
        public static OptimizeMeshBuffer GetRootAsOptimizeMeshBuffer(ByteBuffer _bb, OptimizeMeshBuffer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public OptimizeMeshBuffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public sbyte Source(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
        public int SourceLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<sbyte> GetSourceBytes() { return __p.__vector_as_span<sbyte>(6, 1); }
#else
        public ArraySegment<byte>? GetSourceBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public sbyte[] GetSourceArray() { return __p.__vector_as_array<sbyte>(6); }
        public bool MutateSource(int j, sbyte source) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutSbyte(__p.__vector(o) + j * 1, source); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.OptimizeMeshBuffer> CreateOptimizeMeshBuffer(FlatBufferBuilder builder,
            StringOffset nameOffset = default(StringOffset),
            VectorOffset sourceOffset = default(VectorOffset))
        {
            builder.StartTable(2);
            OptimizeMeshBuffer.AddSource(builder, sourceOffset);
            OptimizeMeshBuffer.AddName(builder, nameOffset);
            return OptimizeMeshBuffer.EndOptimizeMeshBuffer(builder);
        }

        public static void StartOptimizeMeshBuffer(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
        public static void AddSource(FlatBufferBuilder builder, VectorOffset sourceOffset) { builder.AddOffset(1, sourceOffset.Value, 0); }
        public static VectorOffset CreateSourceVector(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddSbyte(data[i]); return builder.EndVector(); }
        public static VectorOffset CreateSourceVectorBlock(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateSourceVectorBlock(FlatBufferBuilder builder, ArraySegment<sbyte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateSourceVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<sbyte>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartSourceVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
        public static Offset<slug.fbs.srtf.OptimizeMeshBuffer> EndOptimizeMeshBuffer(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.OptimizeMeshBuffer>(o);
        }
        public OptimizeMeshBufferT UnPack()
        {
            var _o = new OptimizeMeshBufferT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(OptimizeMeshBufferT _o)
        {
            _o.Name = this.Name;
            _o.Source = new List<sbyte>();
            for (var _j = 0; _j < this.SourceLength; ++_j) { _o.Source.Add(this.Source(_j)); }
        }
        public static Offset<slug.fbs.srtf.OptimizeMeshBuffer> Pack(FlatBufferBuilder builder, OptimizeMeshBufferT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.OptimizeMeshBuffer>);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            var _source = default(VectorOffset);
            if (_o.Source != null)
            {
                var __source = _o.Source.ToArray();
                _source = CreateSourceVector(builder, __source);
            }
            return CreateOptimizeMeshBuffer(
              builder,
              _name,
              _source);
        }
    }

    public class OptimizeMeshBufferT
    {
        public string Name { get; set; }
        public List<sbyte> Source { get; set; }

        public OptimizeMeshBufferT()
        {
            this.Name = null;
            this.Source = null;
        }
    }


    static public class OptimizeMeshBufferVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Name*/, false)
              && verifier.VerifyVectorOfData(tablePos, 6 /*Source*/, 1 /*sbyte*/, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
