// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct OptimizeMesh : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static OptimizeMesh GetRootAsOptimizeMesh(ByteBuffer _bb) { return GetRootAsOptimizeMesh(_bb, new OptimizeMesh()); }
        public static OptimizeMesh GetRootAsOptimizeMesh(ByteBuffer _bb, OptimizeMesh obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public OptimizeMesh __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.VertexAccessor? VertexAccessors(int j) { int o = __p.__offset(4); return o != 0 ? (slug.fbs.srtf.VertexAccessor?)(new slug.fbs.srtf.VertexAccessor()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int VertexAccessorsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.indexAccessor? IndexAccessor { get { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.indexAccessor?)(new slug.fbs.srtf.indexAccessor()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public uint VertexCount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateVertexCount(uint vertex_count) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, vertex_count); return true; } else { return false; } }
        public uint VertexByteSize { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateVertexByteSize(uint vertex_byte_size) { int o = __p.__offset(10); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, vertex_byte_size); return true; } else { return false; } }
        public uint IndexCount { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateIndexCount(uint index_count) { int o = __p.__offset(12); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, index_count); return true; } else { return false; } }
        public uint IndexByteSize { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateIndexByteSize(uint index_byte_size) { int o = __p.__offset(14); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, index_byte_size); return true; } else { return false; } }
        public uint Material { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateMaterial(uint material) { int o = __p.__offset(16); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, material); return true; } else { return false; } }
        public uint Node { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateNode(uint node) { int o = __p.__offset(18); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, node); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.OptimizeMesh> CreateOptimizeMesh(FlatBufferBuilder builder,
            VectorOffset vertex_accessorsOffset = default(VectorOffset),
            Offset<slug.fbs.srtf.indexAccessor> index_accessorOffset = default(Offset<slug.fbs.srtf.indexAccessor>),
            uint vertex_count = 0,
            uint vertex_byte_size = 0,
            uint index_count = 0,
            uint index_byte_size = 0,
            uint material = 0,
            uint node = 0)
        {
            builder.StartTable(8);
            OptimizeMesh.AddNode(builder, node);
            OptimizeMesh.AddMaterial(builder, material);
            OptimizeMesh.AddIndexByteSize(builder, index_byte_size);
            OptimizeMesh.AddIndexCount(builder, index_count);
            OptimizeMesh.AddVertexByteSize(builder, vertex_byte_size);
            OptimizeMesh.AddVertexCount(builder, vertex_count);
            OptimizeMesh.AddIndexAccessor(builder, index_accessorOffset);
            OptimizeMesh.AddVertexAccessors(builder, vertex_accessorsOffset);
            return OptimizeMesh.EndOptimizeMesh(builder);
        }

        public static void StartOptimizeMesh(FlatBufferBuilder builder) { builder.StartTable(8); }
        public static void AddVertexAccessors(FlatBufferBuilder builder, VectorOffset vertexAccessorsOffset) { builder.AddOffset(0, vertexAccessorsOffset.Value, 0); }
        public static VectorOffset CreateVertexAccessorsVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.VertexAccessor>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateVertexAccessorsVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.VertexAccessor>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVertexAccessorsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.VertexAccessor>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVertexAccessorsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.VertexAccessor>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartVertexAccessorsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddIndexAccessor(FlatBufferBuilder builder, Offset<slug.fbs.srtf.indexAccessor> indexAccessorOffset) { builder.AddOffset(1, indexAccessorOffset.Value, 0); }
        public static void AddVertexCount(FlatBufferBuilder builder, uint vertexCount) { builder.AddUint(2, vertexCount, 0); }
        public static void AddVertexByteSize(FlatBufferBuilder builder, uint vertexByteSize) { builder.AddUint(3, vertexByteSize, 0); }
        public static void AddIndexCount(FlatBufferBuilder builder, uint indexCount) { builder.AddUint(4, indexCount, 0); }
        public static void AddIndexByteSize(FlatBufferBuilder builder, uint indexByteSize) { builder.AddUint(5, indexByteSize, 0); }
        public static void AddMaterial(FlatBufferBuilder builder, uint material) { builder.AddUint(6, material, 0); }
        public static void AddNode(FlatBufferBuilder builder, uint node) { builder.AddUint(7, node, 0); }
        public static Offset<slug.fbs.srtf.OptimizeMesh> EndOptimizeMesh(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.OptimizeMesh>(o);
        }
        public OptimizeMeshT UnPack()
        {
            var _o = new OptimizeMeshT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(OptimizeMeshT _o)
        {
            _o.VertexAccessors = new List<slug.fbs.srtf.VertexAccessorT>();
            for (var _j = 0; _j < this.VertexAccessorsLength; ++_j) { _o.VertexAccessors.Add(this.VertexAccessors(_j).HasValue ? this.VertexAccessors(_j).Value.UnPack() : null); }
            _o.IndexAccessor = this.IndexAccessor.HasValue ? this.IndexAccessor.Value.UnPack() : null;
            _o.VertexCount = this.VertexCount;
            _o.VertexByteSize = this.VertexByteSize;
            _o.IndexCount = this.IndexCount;
            _o.IndexByteSize = this.IndexByteSize;
            _o.Material = this.Material;
            _o.Node = this.Node;
        }
        public static Offset<slug.fbs.srtf.OptimizeMesh> Pack(FlatBufferBuilder builder, OptimizeMeshT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.OptimizeMesh>);
            var _vertex_accessors = default(VectorOffset);
            if (_o.VertexAccessors != null)
            {
                var __vertex_accessors = new Offset<slug.fbs.srtf.VertexAccessor>[_o.VertexAccessors.Count];
                for (var _j = 0; _j < __vertex_accessors.Length; ++_j) { __vertex_accessors[_j] = slug.fbs.srtf.VertexAccessor.Pack(builder, _o.VertexAccessors[_j]); }
                _vertex_accessors = CreateVertexAccessorsVector(builder, __vertex_accessors);
            }
            var _index_accessor = _o.IndexAccessor == null ? default(Offset<slug.fbs.srtf.indexAccessor>) : slug.fbs.srtf.indexAccessor.Pack(builder, _o.IndexAccessor);
            return CreateOptimizeMesh(
              builder,
              _vertex_accessors,
              _index_accessor,
              _o.VertexCount,
              _o.VertexByteSize,
              _o.IndexCount,
              _o.IndexByteSize,
              _o.Material,
              _o.Node);
        }
    }

    public class OptimizeMeshT
    {
        public List<slug.fbs.srtf.VertexAccessorT> VertexAccessors { get; set; }
        public slug.fbs.srtf.indexAccessorT IndexAccessor { get; set; }
        public uint VertexCount { get; set; }
        public uint VertexByteSize { get; set; }
        public uint IndexCount { get; set; }
        public uint IndexByteSize { get; set; }
        public uint Material { get; set; }
        public uint Node { get; set; }

        public OptimizeMeshT()
        {
            this.VertexAccessors = null;
            this.IndexAccessor = null;
            this.VertexCount = 0;
            this.VertexByteSize = 0;
            this.IndexCount = 0;
            this.IndexByteSize = 0;
            this.Material = 0;
            this.Node = 0;
        }
    }


    static public class OptimizeMeshVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyVectorOfTables(tablePos, 4 /*VertexAccessors*/, slug.fbs.srtf.VertexAccessorVerify.Verify, false)
              && verifier.VerifyTable(tablePos, 6 /*IndexAccessor*/, slug.fbs.srtf.indexAccessorVerify.Verify, false)
              && verifier.VerifyField(tablePos, 8 /*VertexCount*/, 4 /*uint*/, 4, false)
              && verifier.VerifyField(tablePos, 10 /*VertexByteSize*/, 4 /*uint*/, 4, false)
              && verifier.VerifyField(tablePos, 12 /*IndexCount*/, 4 /*uint*/, 4, false)
              && verifier.VerifyField(tablePos, 14 /*IndexByteSize*/, 4 /*uint*/, 4, false)
              && verifier.VerifyField(tablePos, 16 /*Material*/, 4 /*uint*/, 4, false)
              && verifier.VerifyField(tablePos, 18 /*Node*/, 4 /*uint*/, 4, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
