// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Sampler : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
        public Sampler __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.Vector4 Color { get { return (new slug.fbs.srtf.Vector4()).__assign(__p.bb_pos + 0, __p.bb); } }
        public float MaxAnisotropy { get { return __p.bb.GetFloat(__p.bb_pos + 16); } }
        public void MutateMaxAnisotropy(float max_anisotropy) { __p.bb.PutFloat(__p.bb_pos + 16, max_anisotropy); }
        public float MipBias { get { return __p.bb.GetFloat(__p.bb_pos + 20); } }
        public void MutateMipBias(float mip_bias) { __p.bb.PutFloat(__p.bb_pos + 20, mip_bias); }
        public bool MinFilter { get { return 0 != __p.bb.Get(__p.bb_pos + 24); } }
        public void MutateMinFilter(bool min_filter) { __p.bb.Put(__p.bb_pos + 24, (byte)(min_filter ? 1 : 0)); }
        public bool MagFilter { get { return 0 != __p.bb.Get(__p.bb_pos + 25); } }
        public void MutateMagFilter(bool mag_filter) { __p.bb.Put(__p.bb_pos + 25, (byte)(mag_filter ? 1 : 0)); }
        public bool MipFilter { get { return 0 != __p.bb.Get(__p.bb_pos + 26); } }
        public void MutateMipFilter(bool mip_filter) { __p.bb.Put(__p.bb_pos + 26, (byte)(mip_filter ? 1 : 0)); }
        public slug.fbs.srtf.SamplerAddressMode AddressU { get { return (slug.fbs.srtf.SamplerAddressMode)__p.bb.Get(__p.bb_pos + 27); } }
        public void MutateAddressU(slug.fbs.srtf.SamplerAddressMode address_u) { __p.bb.Put(__p.bb_pos + 27, (byte)address_u); }
        public slug.fbs.srtf.SamplerAddressMode AddressV { get { return (slug.fbs.srtf.SamplerAddressMode)__p.bb.Get(__p.bb_pos + 28); } }
        public void MutateAddressV(slug.fbs.srtf.SamplerAddressMode address_v) { __p.bb.Put(__p.bb_pos + 28, (byte)address_v); }
        public slug.fbs.srtf.SamplerAddressMode AddressW { get { return (slug.fbs.srtf.SamplerAddressMode)__p.bb.Get(__p.bb_pos + 29); } }
        public void MutateAddressW(slug.fbs.srtf.SamplerAddressMode address_w) { __p.bb.Put(__p.bb_pos + 29, (byte)address_w); }
        public slug.fbs.srtf.SamplerReductionType ReductionType { get { return (slug.fbs.srtf.SamplerReductionType)__p.bb.Get(__p.bb_pos + 30); } }
        public void MutateReductionType(slug.fbs.srtf.SamplerReductionType reduction_type) { __p.bb.Put(__p.bb_pos + 30, (byte)reduction_type); }

        public static Offset<slug.fbs.srtf.Sampler> CreateSampler(FlatBufferBuilder builder, float color_X, float color_Y, float color_Z, float color_W, float MaxAnisotropy, float MipBias, bool MinFilter, bool MagFilter, bool MipFilter, slug.fbs.srtf.SamplerAddressMode AddressU, slug.fbs.srtf.SamplerAddressMode AddressV, slug.fbs.srtf.SamplerAddressMode AddressW, slug.fbs.srtf.SamplerReductionType ReductionType)
        {
            builder.Prep(4, 32);
            builder.Pad(1);
            builder.PutByte((byte)ReductionType);
            builder.PutByte((byte)AddressW);
            builder.PutByte((byte)AddressV);
            builder.PutByte((byte)AddressU);
            builder.PutBool(MipFilter);
            builder.PutBool(MagFilter);
            builder.PutBool(MinFilter);
            builder.PutFloat(MipBias);
            builder.PutFloat(MaxAnisotropy);
            builder.Prep(4, 16);
            builder.PutFloat(color_W);
            builder.PutFloat(color_Z);
            builder.PutFloat(color_Y);
            builder.PutFloat(color_X);
            return new Offset<slug.fbs.srtf.Sampler>(builder.Offset);
        }
        public SamplerT UnPack()
        {
            var _o = new SamplerT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(SamplerT _o)
        {
            _o.Color = this.Color.UnPack();
            _o.MaxAnisotropy = this.MaxAnisotropy;
            _o.MipBias = this.MipBias;
            _o.MinFilter = this.MinFilter;
            _o.MagFilter = this.MagFilter;
            _o.MipFilter = this.MipFilter;
            _o.AddressU = this.AddressU;
            _o.AddressV = this.AddressV;
            _o.AddressW = this.AddressW;
            _o.ReductionType = this.ReductionType;
        }
        public static Offset<slug.fbs.srtf.Sampler> Pack(FlatBufferBuilder builder, SamplerT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Sampler>);
            var _color_x = _o.Color.X;
            var _color_y = _o.Color.Y;
            var _color_z = _o.Color.Z;
            var _color_w = _o.Color.W;
            return CreateSampler(
              builder,
              _color_x,
              _color_y,
              _color_z,
              _color_w,
              _o.MaxAnisotropy,
              _o.MipBias,
              _o.MinFilter,
              _o.MagFilter,
              _o.MipFilter,
              _o.AddressU,
              _o.AddressV,
              _o.AddressW,
              _o.ReductionType);
        }
    }

    public class SamplerT
    {
        public slug.fbs.srtf.Vector4T Color { get; set; }
        public float MaxAnisotropy { get; set; }
        public float MipBias { get; set; }
        public bool MinFilter { get; set; }
        public bool MagFilter { get; set; }
        public bool MipFilter { get; set; }
        public slug.fbs.srtf.SamplerAddressMode AddressU { get; set; }
        public slug.fbs.srtf.SamplerAddressMode AddressV { get; set; }
        public slug.fbs.srtf.SamplerAddressMode AddressW { get; set; }
        public slug.fbs.srtf.SamplerReductionType ReductionType { get; set; }

        public SamplerT()
        {
            this.Color = new slug.fbs.srtf.Vector4T();
            this.MaxAnisotropy = 0.0f;
            this.MipBias = 0.0f;
            this.MinFilter = false;
            this.MagFilter = false;
            this.MipFilter = false;
            this.AddressU = slug.fbs.srtf.SamplerAddressMode.Clamp;
            this.AddressV = slug.fbs.srtf.SamplerAddressMode.Clamp;
            this.AddressW = slug.fbs.srtf.SamplerAddressMode.Clamp;
            this.ReductionType = slug.fbs.srtf.SamplerReductionType.Standard;
        }
    }


}
