// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace slug.fbs.srtf
{

    public enum SamplerAddressMode : byte
    {
        Clamp = 0,
        Wrap = 1,
        Border = 2,
        Mirror = 3,
    };


}
