// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace slug.fbs.srtf
{

    public enum SamplerReductionType : byte
    {
        Standard = 0,
        Comparison = 1,
        Minimum = 2,
        Maximum = 3,
    };


}
