// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace slug.fbs.srtf
{

    public enum SemanticType : short
    {
        Position = 0,
        Normal = 1,
        Texcoord = 2,
        Tangent = 3,
        Binormal = 4,
        Color = 5,
        BoneIndex = 6,
        BoneWeight = 7,
    };


}
