// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct ShaderItem : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static ShaderItem GetRootAsShaderItem(ByteBuffer _bb) { return GetRootAsShaderItem(_bb, new ShaderItem()); }
        public static ShaderItem GetRootAsShaderItem(ByteBuffer _bb, ShaderItem obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public ShaderItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public byte Code(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
        public int CodeLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCodeBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
        public ArraySegment<byte>? GetCodeBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public byte[] GetCodeArray() { return __p.__vector_as_array<byte>(6); }
        public bool MutateCode(int j, byte code) { int o = __p.__offset(6); if (o != 0) { __p.bb.Put(__p.__vector(o) + j * 1, code); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.ShaderItem> CreateShaderItem(FlatBufferBuilder builder,
            StringOffset nameOffset = default(StringOffset),
            VectorOffset codeOffset = default(VectorOffset))
        {
            builder.StartTable(2);
            ShaderItem.AddCode(builder, codeOffset);
            ShaderItem.AddName(builder, nameOffset);
            return ShaderItem.EndShaderItem(builder);
        }

        public static void StartShaderItem(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
        public static void AddCode(FlatBufferBuilder builder, VectorOffset codeOffset) { builder.AddOffset(1, codeOffset.Value, 0); }
        public static VectorOffset CreateCodeVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
        public static VectorOffset CreateCodeVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateCodeVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateCodeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartCodeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
        public static Offset<slug.fbs.srtf.ShaderItem> EndShaderItem(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.ShaderItem>(o);
        }
        public ShaderItemT UnPack()
        {
            var _o = new ShaderItemT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(ShaderItemT _o)
        {
            _o.Name = this.Name;
            _o.Code = new List<byte>();
            for (var _j = 0; _j < this.CodeLength; ++_j) { _o.Code.Add(this.Code(_j)); }
        }
        public static Offset<slug.fbs.srtf.ShaderItem> Pack(FlatBufferBuilder builder, ShaderItemT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.ShaderItem>);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            var _code = default(VectorOffset);
            if (_o.Code != null)
            {
                var __code = _o.Code.ToArray();
                _code = CreateCodeVector(builder, __code);
            }
            return CreateShaderItem(
              builder,
              _name,
              _code);
        }
    }

    public class ShaderItemT
    {
        public string Name { get; set; }
        public List<byte> Code { get; set; }

        public ShaderItemT()
        {
            this.Name = null;
            this.Code = null;
        }
    }


    static public class ShaderItemVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Name*/, false)
              && verifier.VerifyVectorOfData(tablePos, 6 /*Code*/, 1 /*byte*/, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
