// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Shader : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static Shader GetRootAsShader(ByteBuffer _bb) { return GetRootAsShader(_bb, new Shader()); }
        public static Shader GetRootAsShader(ByteBuffer _bb, Shader obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public static bool ShaderBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "SHAD"); }
        public static bool VerifyShader(ByteBuffer _bb) { Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("SHAD", false, ShaderVerify.Verify); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Shader __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.DrawSettings? DrawSettings { get { int o = __p.__offset(4); return o != 0 ? (slug.fbs.srtf.DrawSettings?)(new slug.fbs.srtf.DrawSettings()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
        public slug.fbs.srtf.TextureParameter? Textuers(int j) { int o = __p.__offset(8); return o != 0 ? (slug.fbs.srtf.TextureParameter?)(new slug.fbs.srtf.TextureParameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int TextuersLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.BoolParameter? StaticSwiches(int j) { int o = __p.__offset(10); return o != 0 ? (slug.fbs.srtf.BoolParameter?)(new slug.fbs.srtf.BoolParameter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int StaticSwichesLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.ConstantParameter? ConstantParameter { get { int o = __p.__offset(12); return o != 0 ? (slug.fbs.srtf.ConstantParameter?)(new slug.fbs.srtf.ConstantParameter()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public slug.fbs.srtf.ShaderItem? VertexShaders(int j) { int o = __p.__offset(14); return o != 0 ? (slug.fbs.srtf.ShaderItem?)(new slug.fbs.srtf.ShaderItem()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int VertexShadersLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.ShaderItem? PixelShaders(int j) { int o = __p.__offset(16); return o != 0 ? (slug.fbs.srtf.ShaderItem?)(new slug.fbs.srtf.ShaderItem()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int PixelShadersLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.ShaderItem? GeometryShaders(int j) { int o = __p.__offset(18); return o != 0 ? (slug.fbs.srtf.ShaderItem?)(new slug.fbs.srtf.ShaderItem()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int GeometryShadersLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.ShaderItem? HullShaders(int j) { int o = __p.__offset(20); return o != 0 ? (slug.fbs.srtf.ShaderItem?)(new slug.fbs.srtf.ShaderItem()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int HullShadersLength { get { int o = __p.__offset(20); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.ShaderItem? DomainShaders(int j) { int o = __p.__offset(22); return o != 0 ? (slug.fbs.srtf.ShaderItem?)(new slug.fbs.srtf.ShaderItem()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int DomainShadersLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.ShaderItem? ComputeShaders(int j) { int o = __p.__offset(24); return o != 0 ? (slug.fbs.srtf.ShaderItem?)(new slug.fbs.srtf.ShaderItem()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int ComputeShadersLength { get { int o = __p.__offset(24); return o != 0 ? __p.__vector_len(o) : 0; } }

        public static Offset<slug.fbs.srtf.Shader> CreateShader(FlatBufferBuilder builder,
            Offset<slug.fbs.srtf.DrawSettings> draw_settingsOffset = default(Offset<slug.fbs.srtf.DrawSettings>),
            StringOffset nameOffset = default(StringOffset),
            VectorOffset textuersOffset = default(VectorOffset),
            VectorOffset static_swichesOffset = default(VectorOffset),
            Offset<slug.fbs.srtf.ConstantParameter> constant_parameterOffset = default(Offset<slug.fbs.srtf.ConstantParameter>),
            VectorOffset vertex_shadersOffset = default(VectorOffset),
            VectorOffset pixel_shadersOffset = default(VectorOffset),
            VectorOffset geometry_shadersOffset = default(VectorOffset),
            VectorOffset hull_shadersOffset = default(VectorOffset),
            VectorOffset domain_shadersOffset = default(VectorOffset),
            VectorOffset compute_shadersOffset = default(VectorOffset))
        {
            builder.StartTable(11);
            Shader.AddComputeShaders(builder, compute_shadersOffset);
            Shader.AddDomainShaders(builder, domain_shadersOffset);
            Shader.AddHullShaders(builder, hull_shadersOffset);
            Shader.AddGeometryShaders(builder, geometry_shadersOffset);
            Shader.AddPixelShaders(builder, pixel_shadersOffset);
            Shader.AddVertexShaders(builder, vertex_shadersOffset);
            Shader.AddConstantParameter(builder, constant_parameterOffset);
            Shader.AddStaticSwiches(builder, static_swichesOffset);
            Shader.AddTextuers(builder, textuersOffset);
            Shader.AddName(builder, nameOffset);
            Shader.AddDrawSettings(builder, draw_settingsOffset);
            return Shader.EndShader(builder);
        }

        public static void StartShader(FlatBufferBuilder builder) { builder.StartTable(11); }
        public static void AddDrawSettings(FlatBufferBuilder builder, Offset<slug.fbs.srtf.DrawSettings> drawSettingsOffset) { builder.AddOffset(0, drawSettingsOffset.Value, 0); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
        public static void AddTextuers(FlatBufferBuilder builder, VectorOffset textuersOffset) { builder.AddOffset(2, textuersOffset.Value, 0); }
        public static VectorOffset CreateTextuersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.TextureParameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateTextuersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.TextureParameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateTextuersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.TextureParameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateTextuersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.TextureParameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartTextuersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddStaticSwiches(FlatBufferBuilder builder, VectorOffset staticSwichesOffset) { builder.AddOffset(3, staticSwichesOffset.Value, 0); }
        public static VectorOffset CreateStaticSwichesVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.BoolParameter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateStaticSwichesVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.BoolParameter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateStaticSwichesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.BoolParameter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateStaticSwichesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.BoolParameter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartStaticSwichesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddConstantParameter(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ConstantParameter> constantParameterOffset) { builder.AddOffset(4, constantParameterOffset.Value, 0); }
        public static void AddVertexShaders(FlatBufferBuilder builder, VectorOffset vertexShadersOffset) { builder.AddOffset(5, vertexShadersOffset.Value, 0); }
        public static VectorOffset CreateVertexShadersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateVertexShadersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVertexShadersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.ShaderItem>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateVertexShadersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.ShaderItem>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartVertexShadersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddPixelShaders(FlatBufferBuilder builder, VectorOffset pixelShadersOffset) { builder.AddOffset(6, pixelShadersOffset.Value, 0); }
        public static VectorOffset CreatePixelShadersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreatePixelShadersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreatePixelShadersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.ShaderItem>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreatePixelShadersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.ShaderItem>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartPixelShadersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddGeometryShaders(FlatBufferBuilder builder, VectorOffset geometryShadersOffset) { builder.AddOffset(7, geometryShadersOffset.Value, 0); }
        public static VectorOffset CreateGeometryShadersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateGeometryShadersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateGeometryShadersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.ShaderItem>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateGeometryShadersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.ShaderItem>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartGeometryShadersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddHullShaders(FlatBufferBuilder builder, VectorOffset hullShadersOffset) { builder.AddOffset(8, hullShadersOffset.Value, 0); }
        public static VectorOffset CreateHullShadersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateHullShadersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateHullShadersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.ShaderItem>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateHullShadersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.ShaderItem>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartHullShadersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddDomainShaders(FlatBufferBuilder builder, VectorOffset domainShadersOffset) { builder.AddOffset(9, domainShadersOffset.Value, 0); }
        public static VectorOffset CreateDomainShadersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateDomainShadersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateDomainShadersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.ShaderItem>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateDomainShadersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.ShaderItem>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartDomainShadersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddComputeShaders(FlatBufferBuilder builder, VectorOffset computeShadersOffset) { builder.AddOffset(10, computeShadersOffset.Value, 0); }
        public static VectorOffset CreateComputeShadersVector(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateComputeShadersVectorBlock(FlatBufferBuilder builder, Offset<slug.fbs.srtf.ShaderItem>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateComputeShadersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<slug.fbs.srtf.ShaderItem>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateComputeShadersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<slug.fbs.srtf.ShaderItem>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartComputeShadersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<slug.fbs.srtf.Shader> EndShader(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.Shader>(o);
        }
        public static void FinishShaderBuffer(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Shader> offset) { builder.Finish(offset.Value, "SHAD"); }
        public static void FinishSizePrefixedShaderBuffer(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Shader> offset) { builder.FinishSizePrefixed(offset.Value, "SHAD"); }
        public ShaderT UnPack()
        {
            var _o = new ShaderT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(ShaderT _o)
        {
            _o.DrawSettings = this.DrawSettings.HasValue ? this.DrawSettings.Value.UnPack() : null;
            _o.Name = this.Name;
            _o.Textuers = new List<slug.fbs.srtf.TextureParameterT>();
            for (var _j = 0; _j < this.TextuersLength; ++_j) { _o.Textuers.Add(this.Textuers(_j).HasValue ? this.Textuers(_j).Value.UnPack() : null); }
            _o.StaticSwiches = new List<slug.fbs.srtf.BoolParameterT>();
            for (var _j = 0; _j < this.StaticSwichesLength; ++_j) { _o.StaticSwiches.Add(this.StaticSwiches(_j).HasValue ? this.StaticSwiches(_j).Value.UnPack() : null); }
            _o.ConstantParameter = this.ConstantParameter.HasValue ? this.ConstantParameter.Value.UnPack() : null;
            _o.VertexShaders = new List<slug.fbs.srtf.ShaderItemT>();
            for (var _j = 0; _j < this.VertexShadersLength; ++_j) { _o.VertexShaders.Add(this.VertexShaders(_j).HasValue ? this.VertexShaders(_j).Value.UnPack() : null); }
            _o.PixelShaders = new List<slug.fbs.srtf.ShaderItemT>();
            for (var _j = 0; _j < this.PixelShadersLength; ++_j) { _o.PixelShaders.Add(this.PixelShaders(_j).HasValue ? this.PixelShaders(_j).Value.UnPack() : null); }
            _o.GeometryShaders = new List<slug.fbs.srtf.ShaderItemT>();
            for (var _j = 0; _j < this.GeometryShadersLength; ++_j) { _o.GeometryShaders.Add(this.GeometryShaders(_j).HasValue ? this.GeometryShaders(_j).Value.UnPack() : null); }
            _o.HullShaders = new List<slug.fbs.srtf.ShaderItemT>();
            for (var _j = 0; _j < this.HullShadersLength; ++_j) { _o.HullShaders.Add(this.HullShaders(_j).HasValue ? this.HullShaders(_j).Value.UnPack() : null); }
            _o.DomainShaders = new List<slug.fbs.srtf.ShaderItemT>();
            for (var _j = 0; _j < this.DomainShadersLength; ++_j) { _o.DomainShaders.Add(this.DomainShaders(_j).HasValue ? this.DomainShaders(_j).Value.UnPack() : null); }
            _o.ComputeShaders = new List<slug.fbs.srtf.ShaderItemT>();
            for (var _j = 0; _j < this.ComputeShadersLength; ++_j) { _o.ComputeShaders.Add(this.ComputeShaders(_j).HasValue ? this.ComputeShaders(_j).Value.UnPack() : null); }
        }
        public static Offset<slug.fbs.srtf.Shader> Pack(FlatBufferBuilder builder, ShaderT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Shader>);
            var _draw_settings = _o.DrawSettings == null ? default(Offset<slug.fbs.srtf.DrawSettings>) : slug.fbs.srtf.DrawSettings.Pack(builder, _o.DrawSettings);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            var _textuers = default(VectorOffset);
            if (_o.Textuers != null)
            {
                var __textuers = new Offset<slug.fbs.srtf.TextureParameter>[_o.Textuers.Count];
                for (var _j = 0; _j < __textuers.Length; ++_j) { __textuers[_j] = slug.fbs.srtf.TextureParameter.Pack(builder, _o.Textuers[_j]); }
                _textuers = CreateTextuersVector(builder, __textuers);
            }
            var _static_swiches = default(VectorOffset);
            if (_o.StaticSwiches != null)
            {
                var __static_swiches = new Offset<slug.fbs.srtf.BoolParameter>[_o.StaticSwiches.Count];
                for (var _j = 0; _j < __static_swiches.Length; ++_j) { __static_swiches[_j] = slug.fbs.srtf.BoolParameter.Pack(builder, _o.StaticSwiches[_j]); }
                _static_swiches = CreateStaticSwichesVector(builder, __static_swiches);
            }
            var _constant_parameter = _o.ConstantParameter == null ? default(Offset<slug.fbs.srtf.ConstantParameter>) : slug.fbs.srtf.ConstantParameter.Pack(builder, _o.ConstantParameter);
            var _vertex_shaders = default(VectorOffset);
            if (_o.VertexShaders != null)
            {
                var __vertex_shaders = new Offset<slug.fbs.srtf.ShaderItem>[_o.VertexShaders.Count];
                for (var _j = 0; _j < __vertex_shaders.Length; ++_j) { __vertex_shaders[_j] = slug.fbs.srtf.ShaderItem.Pack(builder, _o.VertexShaders[_j]); }
                _vertex_shaders = CreateVertexShadersVector(builder, __vertex_shaders);
            }
            var _pixel_shaders = default(VectorOffset);
            if (_o.PixelShaders != null)
            {
                var __pixel_shaders = new Offset<slug.fbs.srtf.ShaderItem>[_o.PixelShaders.Count];
                for (var _j = 0; _j < __pixel_shaders.Length; ++_j) { __pixel_shaders[_j] = slug.fbs.srtf.ShaderItem.Pack(builder, _o.PixelShaders[_j]); }
                _pixel_shaders = CreatePixelShadersVector(builder, __pixel_shaders);
            }
            var _geometry_shaders = default(VectorOffset);
            if (_o.GeometryShaders != null)
            {
                var __geometry_shaders = new Offset<slug.fbs.srtf.ShaderItem>[_o.GeometryShaders.Count];
                for (var _j = 0; _j < __geometry_shaders.Length; ++_j) { __geometry_shaders[_j] = slug.fbs.srtf.ShaderItem.Pack(builder, _o.GeometryShaders[_j]); }
                _geometry_shaders = CreateGeometryShadersVector(builder, __geometry_shaders);
            }
            var _hull_shaders = default(VectorOffset);
            if (_o.HullShaders != null)
            {
                var __hull_shaders = new Offset<slug.fbs.srtf.ShaderItem>[_o.HullShaders.Count];
                for (var _j = 0; _j < __hull_shaders.Length; ++_j) { __hull_shaders[_j] = slug.fbs.srtf.ShaderItem.Pack(builder, _o.HullShaders[_j]); }
                _hull_shaders = CreateHullShadersVector(builder, __hull_shaders);
            }
            var _domain_shaders = default(VectorOffset);
            if (_o.DomainShaders != null)
            {
                var __domain_shaders = new Offset<slug.fbs.srtf.ShaderItem>[_o.DomainShaders.Count];
                for (var _j = 0; _j < __domain_shaders.Length; ++_j) { __domain_shaders[_j] = slug.fbs.srtf.ShaderItem.Pack(builder, _o.DomainShaders[_j]); }
                _domain_shaders = CreateDomainShadersVector(builder, __domain_shaders);
            }
            var _compute_shaders = default(VectorOffset);
            if (_o.ComputeShaders != null)
            {
                var __compute_shaders = new Offset<slug.fbs.srtf.ShaderItem>[_o.ComputeShaders.Count];
                for (var _j = 0; _j < __compute_shaders.Length; ++_j) { __compute_shaders[_j] = slug.fbs.srtf.ShaderItem.Pack(builder, _o.ComputeShaders[_j]); }
                _compute_shaders = CreateComputeShadersVector(builder, __compute_shaders);
            }
            return CreateShader(
              builder,
              _draw_settings,
              _name,
              _textuers,
              _static_swiches,
              _constant_parameter,
              _vertex_shaders,
              _pixel_shaders,
              _geometry_shaders,
              _hull_shaders,
              _domain_shaders,
              _compute_shaders);
        }
    }

    public class ShaderT
    {
        public slug.fbs.srtf.DrawSettingsT DrawSettings { get; set; }
        public string Name { get; set; }
        public List<slug.fbs.srtf.TextureParameterT> Textuers { get; set; }
        public List<slug.fbs.srtf.BoolParameterT> StaticSwiches { get; set; }
        public slug.fbs.srtf.ConstantParameterT ConstantParameter { get; set; }
        public List<slug.fbs.srtf.ShaderItemT> VertexShaders { get; set; }
        public List<slug.fbs.srtf.ShaderItemT> PixelShaders { get; set; }
        public List<slug.fbs.srtf.ShaderItemT> GeometryShaders { get; set; }
        public List<slug.fbs.srtf.ShaderItemT> HullShaders { get; set; }
        public List<slug.fbs.srtf.ShaderItemT> DomainShaders { get; set; }
        public List<slug.fbs.srtf.ShaderItemT> ComputeShaders { get; set; }

        public ShaderT()
        {
            this.DrawSettings = null;
            this.Name = null;
            this.Textuers = null;
            this.StaticSwiches = null;
            this.ConstantParameter = null;
            this.VertexShaders = null;
            this.PixelShaders = null;
            this.GeometryShaders = null;
            this.HullShaders = null;
            this.DomainShaders = null;
            this.ComputeShaders = null;
        }
        public static ShaderT DeserializeFromBinary(byte[] fbBuffer)
        {
            return Shader.GetRootAsShader(new ByteBuffer(fbBuffer)).UnPack();
        }
        public byte[] SerializeToBinary()
        {
            var fbb = new FlatBufferBuilder(0x10000);
            Shader.FinishShaderBuffer(fbb, Shader.Pack(fbb, this));
            return fbb.DataBuffer.ToSizedArray();
        }
    }


    static public class ShaderVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyTable(tablePos, 4 /*DrawSettings*/, slug.fbs.srtf.DrawSettingsVerify.Verify, false)
              && verifier.VerifyString(tablePos, 6 /*Name*/, false)
              && verifier.VerifyVectorOfTables(tablePos, 8 /*Textuers*/, slug.fbs.srtf.TextureParameterVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 10 /*StaticSwiches*/, slug.fbs.srtf.BoolParameterVerify.Verify, false)
              && verifier.VerifyTable(tablePos, 12 /*ConstantParameter*/, slug.fbs.srtf.ConstantParameterVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 14 /*VertexShaders*/, slug.fbs.srtf.ShaderItemVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 16 /*PixelShaders*/, slug.fbs.srtf.ShaderItemVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 18 /*GeometryShaders*/, slug.fbs.srtf.ShaderItemVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 20 /*HullShaders*/, slug.fbs.srtf.ShaderItemVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 22 /*DomainShaders*/, slug.fbs.srtf.ShaderItemVerify.Verify, false)
              && verifier.VerifyVectorOfTables(tablePos, 24 /*ComputeShaders*/, slug.fbs.srtf.ShaderItemVerify.Verify, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
