// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct ShadingModel : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static ShadingModel GetRootAsShadingModel(ByteBuffer _bb) { return GetRootAsShadingModel(_bb, new ShadingModel()); }
        public static ShadingModel GetRootAsShadingModel(ByteBuffer _bb, ShadingModel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public ShadingModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public uint Id { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateId(uint id) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, id); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.ShadingModel> CreateShadingModel(FlatBufferBuilder builder,
            StringOffset nameOffset = default(StringOffset),
            uint id = 0)
        {
            builder.StartTable(2);
            ShadingModel.AddId(builder, id);
            ShadingModel.AddName(builder, nameOffset);
            return ShadingModel.EndShadingModel(builder);
        }

        public static void StartShadingModel(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
        public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(1, id, 0); }
        public static Offset<slug.fbs.srtf.ShadingModel> EndShadingModel(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.ShadingModel>(o);
        }
        public ShadingModelT UnPack()
        {
            var _o = new ShadingModelT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(ShadingModelT _o)
        {
            _o.Name = this.Name;
            _o.Id = this.Id;
        }
        public static Offset<slug.fbs.srtf.ShadingModel> Pack(FlatBufferBuilder builder, ShadingModelT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.ShadingModel>);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            return CreateShadingModel(
              builder,
              _name,
              _o.Id);
        }
    }

    public class ShadingModelT
    {
        public string Name { get; set; }
        public uint Id { get; set; }

        public ShadingModelT()
        {
            this.Name = null;
            this.Id = 0;
        }
    }


    static public class ShadingModelVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Name*/, false)
              && verifier.VerifyField(tablePos, 6 /*Id*/, 4 /*uint*/, 4, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
