// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct TangentLayer : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
        public TangentLayer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public byte Name(int j) { return __p.bb.Get(__p.bb_pos + 0 + j * 1); }
        public void MutateName(int j, byte name) { __p.bb.Put(__p.bb_pos + 0 + j * 1, name); }
        public slug.fbs.srtf.Vector3 Tangent { get { return (new slug.fbs.srtf.Vector3()).__assign(__p.bb_pos + 64, __p.bb); } }

        public static Offset<slug.fbs.srtf.TangentLayer> CreateTangentLayer(FlatBufferBuilder builder, byte[] Name, float tangent_X, float tangent_Y, float tangent_Z)
        {
            builder.Prep(4, 76);
            builder.Prep(4, 12);
            builder.PutFloat(tangent_Z);
            builder.PutFloat(tangent_Y);
            builder.PutFloat(tangent_X);
            for (int _idx0 = 64; _idx0 > 0; _idx0--)
            {
                builder.PutByte(Name[_idx0 - 1]);
            }
            return new Offset<slug.fbs.srtf.TangentLayer>(builder.Offset);
        }
        public TangentLayerT UnPack()
        {
            var _o = new TangentLayerT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(TangentLayerT _o)
        {
            _o.Name = new byte[64];
            for (var _j = 0; _j < 64; ++_j) { _o.Name[_j] = this.Name(_j); }
            _o.Tangent = this.Tangent.UnPack();
        }
        public static Offset<slug.fbs.srtf.TangentLayer> Pack(FlatBufferBuilder builder, TangentLayerT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.TangentLayer>);
            var _name = _o.Name;
            var _tangent_x = _o.Tangent.X;
            var _tangent_y = _o.Tangent.Y;
            var _tangent_z = _o.Tangent.Z;
            return CreateTangentLayer(
              builder,
              _name,
              _tangent_x,
              _tangent_y,
              _tangent_z);
        }
    }

    public class TangentLayerT
    {
        public byte[] Name { get; set; }
        public slug.fbs.srtf.Vector3T Tangent { get; set; }

        public TangentLayerT()
        {
            this.Name = new byte[64];
            this.Tangent = new slug.fbs.srtf.Vector3T();
        }
    }


}
