// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct TextureParameter : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static TextureParameter GetRootAsTextureParameter(ByteBuffer _bb) { return GetRootAsTextureParameter(_bb, new TextureParameter()); }
        public static TextureParameter GetRootAsTextureParameter(ByteBuffer _bb, TextureParameter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public TextureParameter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string SlotName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSlotNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetSlotNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetSlotNameArray() { return __p.__vector_as_array<byte>(4); }
        public string Texture { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTextureBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
        public ArraySegment<byte>? GetTextureBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public byte[] GetTextureArray() { return __p.__vector_as_array<byte>(6); }

        public static Offset<slug.fbs.srtf.TextureParameter> CreateTextureParameter(FlatBufferBuilder builder,
            StringOffset slot_nameOffset = default(StringOffset),
            StringOffset textureOffset = default(StringOffset))
        {
            builder.StartTable(2);
            TextureParameter.AddTexture(builder, textureOffset);
            TextureParameter.AddSlotName(builder, slot_nameOffset);
            return TextureParameter.EndTextureParameter(builder);
        }

        public static void StartTextureParameter(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddSlotName(FlatBufferBuilder builder, StringOffset slotNameOffset) { builder.AddOffset(0, slotNameOffset.Value, 0); }
        public static void AddTexture(FlatBufferBuilder builder, StringOffset textureOffset) { builder.AddOffset(1, textureOffset.Value, 0); }
        public static Offset<slug.fbs.srtf.TextureParameter> EndTextureParameter(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.TextureParameter>(o);
        }
        public TextureParameterT UnPack()
        {
            var _o = new TextureParameterT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(TextureParameterT _o)
        {
            _o.SlotName = this.SlotName;
            _o.Texture = this.Texture;
        }
        public static Offset<slug.fbs.srtf.TextureParameter> Pack(FlatBufferBuilder builder, TextureParameterT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.TextureParameter>);
            var _slot_name = _o.SlotName == null ? default(StringOffset) : builder.CreateString(_o.SlotName);
            var _texture = _o.Texture == null ? default(StringOffset) : builder.CreateString(_o.Texture);
            return CreateTextureParameter(
              builder,
              _slot_name,
              _texture);
        }
    }

    public class TextureParameterT
    {
        public string SlotName { get; set; }
        public string Texture { get; set; }

        public TextureParameterT()
        {
            this.SlotName = null;
            this.Texture = null;
        }
    }


    static public class TextureParameterVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*SlotName*/, false)
              && verifier.VerifyString(tablePos, 6 /*Texture*/, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
