// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Texture : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static Texture GetRootAsTexture(ByteBuffer _bb) { return GetRootAsTexture(_bb, new Texture()); }
        public static Texture GetRootAsTexture(ByteBuffer _bb, Texture obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public static bool TextureBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "TEXT"); }
        public static bool VerifyTexture(ByteBuffer _bb) { Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("TEXT", false, TextureVerify.Verify); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Texture __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public slug.fbs.srtf.Sampler? Sampler { get { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.Sampler?)(new slug.fbs.srtf.Sampler()).__assign(o + __p.bb_pos, __p.bb) : null; } }
        public byte Source(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
        public int SourceLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSourceBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
        public ArraySegment<byte>? GetSourceBytes() { return __p.__vector_as_arraysegment(8); }
#endif
        public byte[] GetSourceArray() { return __p.__vector_as_array<byte>(8); }
        public bool MutateSource(int j, byte source) { int o = __p.__offset(8); if (o != 0) { __p.bb.Put(__p.__vector(o) + j * 1, source); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.Texture> CreateTexture(FlatBufferBuilder builder,
            StringOffset nameOffset = default(StringOffset),
            slug.fbs.srtf.SamplerT sampler = null,
            VectorOffset sourceOffset = default(VectorOffset))
        {
            builder.StartTable(3);
            Texture.AddSource(builder, sourceOffset);
            Texture.AddSampler(builder, slug.fbs.srtf.Sampler.Pack(builder, sampler));
            Texture.AddName(builder, nameOffset);
            return Texture.EndTexture(builder);
        }

        public static void StartTexture(FlatBufferBuilder builder) { builder.StartTable(3); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
        public static void AddSampler(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Sampler> samplerOffset) { builder.AddStruct(1, samplerOffset.Value, 0); }
        public static void AddSource(FlatBufferBuilder builder, VectorOffset sourceOffset) { builder.AddOffset(2, sourceOffset.Value, 0); }
        public static VectorOffset CreateSourceVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
        public static VectorOffset CreateSourceVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateSourceVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateSourceVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartSourceVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
        public static Offset<slug.fbs.srtf.Texture> EndTexture(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.Texture>(o);
        }
        public static void FinishTextureBuffer(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Texture> offset) { builder.Finish(offset.Value, "TEXT"); }
        public static void FinishSizePrefixedTextureBuffer(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Texture> offset) { builder.FinishSizePrefixed(offset.Value, "TEXT"); }
        public TextureT UnPack()
        {
            var _o = new TextureT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(TextureT _o)
        {
            _o.Name = this.Name;
            _o.Sampler = this.Sampler.HasValue ? this.Sampler.Value.UnPack() : null;
            _o.Source = new List<byte>();
            for (var _j = 0; _j < this.SourceLength; ++_j) { _o.Source.Add(this.Source(_j)); }
        }
        public static Offset<slug.fbs.srtf.Texture> Pack(FlatBufferBuilder builder, TextureT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Texture>);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            var _source = default(VectorOffset);
            if (_o.Source != null)
            {
                var __source = _o.Source.ToArray();
                _source = CreateSourceVector(builder, __source);
            }
            return CreateTexture(
              builder,
              _name,
              _o.Sampler,
              _source);
        }
    }

    public class TextureT
    {
        public string Name { get; set; }
        public slug.fbs.srtf.SamplerT Sampler { get; set; }
        public List<byte> Source { get; set; }

        public TextureT()
        {
            this.Name = null;
            this.Sampler = new slug.fbs.srtf.SamplerT();
            this.Source = null;
        }
        public static TextureT DeserializeFromBinary(byte[] fbBuffer)
        {
            return Texture.GetRootAsTexture(new ByteBuffer(fbBuffer)).UnPack();
        }
        public byte[] SerializeToBinary()
        {
            var fbb = new FlatBufferBuilder(0x10000);
            Texture.FinishTextureBuffer(fbb, Texture.Pack(fbb, this));
            return fbb.DataBuffer.ToSizedArray();
        }
    }


    static public class TextureVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Name*/, false)
              && verifier.VerifyField(tablePos, 6 /*Sampler*/, 32 /*slug.fbs.srtf.Sampler*/, 4, false)
              && verifier.VerifyVectorOfData(tablePos, 8 /*Source*/, 1 /*byte*/, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
