// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace slug.fbs.srtf
{

    public enum TopologyType : short
    {
        PointList = 0,
        LineList = 1,
        LineStrip = 2,
        TriangleList = 3,
        TriangleStrip = 4,
        QuadList = 5,
        QuadStrip = 6,
    };


}
