// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct UVLayer : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
        public UVLayer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public byte Name(int j) { return __p.bb.Get(__p.bb_pos + 0 + j * 1); }
        public void MutateName(int j, byte name) { __p.bb.Put(__p.bb_pos + 0 + j * 1, name); }
        public slug.fbs.srtf.Vector3 Uv { get { return (new slug.fbs.srtf.Vector3()).__assign(__p.bb_pos + 64, __p.bb); } }

        public static Offset<slug.fbs.srtf.UVLayer> CreateUVLayer(FlatBufferBuilder builder, byte[] Name, float uv_X, float uv_Y, float uv_Z)
        {
            builder.Prep(4, 76);
            builder.Prep(4, 12);
            builder.PutFloat(uv_Z);
            builder.PutFloat(uv_Y);
            builder.PutFloat(uv_X);
            for (int _idx0 = 64; _idx0 > 0; _idx0--)
            {
                builder.PutByte(Name[_idx0 - 1]);
            }
            return new Offset<slug.fbs.srtf.UVLayer>(builder.Offset);
        }
        public UVLayerT UnPack()
        {
            var _o = new UVLayerT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(UVLayerT _o)
        {
            _o.Name = new byte[64];
            for (var _j = 0; _j < 64; ++_j) { _o.Name[_j] = this.Name(_j); }
            _o.Uv = this.Uv.UnPack();
        }
        public static Offset<slug.fbs.srtf.UVLayer> Pack(FlatBufferBuilder builder, UVLayerT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.UVLayer>);
            var _name = _o.Name;
            var _uv_x = _o.Uv.X;
            var _uv_y = _o.Uv.Y;
            var _uv_z = _o.Uv.Z;
            return CreateUVLayer(
              builder,
              _name,
              _uv_x,
              _uv_y,
              _uv_z);
        }
    }

    public class UVLayerT
    {
        public byte[] Name { get; set; }
        public slug.fbs.srtf.Vector3T Uv { get; set; }

        public UVLayerT()
        {
            this.Name = new byte[64];
            this.Uv = new slug.fbs.srtf.Vector3T();
        }
    }


}
