// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Vector3Parameter : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static Vector3Parameter GetRootAsVector3Parameter(ByteBuffer _bb) { return GetRootAsVector3Parameter(_bb, new Vector3Parameter()); }
        public static Vector3Parameter GetRootAsVector3Parameter(ByteBuffer _bb, Vector3Parameter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Vector3Parameter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public slug.fbs.srtf.Vector3? Value { get { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.Vector3?)(new slug.fbs.srtf.Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

        public static Offset<slug.fbs.srtf.Vector3Parameter> CreateVector3Parameter(FlatBufferBuilder builder,
            StringOffset nameOffset = default(StringOffset),
            slug.fbs.srtf.Vector3T value = null)
        {
            builder.StartTable(2);
            Vector3Parameter.AddValue(builder, slug.fbs.srtf.Vector3.Pack(builder, value));
            Vector3Parameter.AddName(builder, nameOffset);
            return Vector3Parameter.EndVector3Parameter(builder);
        }

        public static void StartVector3Parameter(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
        public static void AddValue(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Vector3> valueOffset) { builder.AddStruct(1, valueOffset.Value, 0); }
        public static Offset<slug.fbs.srtf.Vector3Parameter> EndVector3Parameter(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.Vector3Parameter>(o);
        }
        public Vector3ParameterT UnPack()
        {
            var _o = new Vector3ParameterT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(Vector3ParameterT _o)
        {
            _o.Name = this.Name;
            _o.Value = this.Value.HasValue ? this.Value.Value.UnPack() : null;
        }
        public static Offset<slug.fbs.srtf.Vector3Parameter> Pack(FlatBufferBuilder builder, Vector3ParameterT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Vector3Parameter>);
            var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
            return CreateVector3Parameter(
              builder,
              _name,
              _o.Value);
        }
    }

    public class Vector3ParameterT
    {
        public string Name { get; set; }
        public slug.fbs.srtf.Vector3T Value { get; set; }

        public Vector3ParameterT()
        {
            this.Name = null;
            this.Value = new slug.fbs.srtf.Vector3T();
        }
    }


    static public class Vector3ParameterVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Name*/, false)
              && verifier.VerifyField(tablePos, 6 /*Value*/, 12 /*slug.fbs.srtf.Vector3*/, 4, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
