// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace slug.fbs.srtf
{

    public enum VertexFormat : short
    {
        NONE = 0,
        BYTE1 = 1,
        BYTE2 = 2,
        BYTE3 = 3,
        BYTE4 = 4,
        BYTE4N = 5,
        UBYTE1 = 6,
        UBYTE2 = 7,
        UBYTE3 = 8,
        UBYTE4 = 9,
        UBYTE8 = 10,
        UBYTE4N = 11,
        SHORT1 = 12,
        SHORT2 = 13,
        SHORT2N = 14,
        SHORT3 = 15,
        SHORT4 = 16,
        SHORT4N = 17,
        USHORT1 = 18,
        USHORT2 = 19,
        USHORT2N = 20,
        USHORT3 = 21,
        USHORT4 = 22,
        USHORT4N = 23,
        USHORT8 = 24,
        INT1 = 25,
        INT2 = 26,
        INT3 = 27,
        INT4 = 28,
        UINT1 = 29,
        UINT2 = 30,
        UINT3 = 31,
        UINT4 = 32,
        FLOAT1 = 33,
        FLOAT2 = 34,
        FLOAT3 = 35,
        FLOAT4 = 36,
        R11G11B10Float = 37,
        R10G10B10A2Unorm = 38,
    };


}
