// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct Vertex : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static Vertex GetRootAsVertex(ByteBuffer _bb) { return GetRootAsVertex(_bb, new Vertex()); }
        public static Vertex GetRootAsVertex(ByteBuffer _bb, Vertex obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Vertex __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.Vector3? Position { get { int o = __p.__offset(4); return o != 0 ? (slug.fbs.srtf.Vector3?)(new slug.fbs.srtf.Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
        public slug.fbs.srtf.Vector3? Normal { get { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.Vector3?)(new slug.fbs.srtf.Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
        public slug.fbs.srtf.UVLayer? Uvs(int j) { int o = __p.__offset(8); return o != 0 ? (slug.fbs.srtf.UVLayer?)(new slug.fbs.srtf.UVLayer()).__assign(__p.__vector(o) + j * 76, __p.bb) : null; }
        public int UvsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.TangentLayer? Tangents(int j) { int o = __p.__offset(10); return o != 0 ? (slug.fbs.srtf.TangentLayer?)(new slug.fbs.srtf.TangentLayer()).__assign(__p.__vector(o) + j * 76, __p.bb) : null; }
        public int TangentsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.BinormalLayer? Binormals(int j) { int o = __p.__offset(12); return o != 0 ? (slug.fbs.srtf.BinormalLayer?)(new slug.fbs.srtf.BinormalLayer()).__assign(__p.__vector(o) + j * 76, __p.bb) : null; }
        public int BinormalsLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.ColorLayer? Colors(int j) { int o = __p.__offset(14); return o != 0 ? (slug.fbs.srtf.ColorLayer?)(new slug.fbs.srtf.ColorLayer()).__assign(__p.__vector(o) + j * 80, __p.bb) : null; }
        public int ColorsLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
        public slug.fbs.srtf.BoneLayer? Bones(int j) { int o = __p.__offset(16); return o != 0 ? (slug.fbs.srtf.BoneLayer?)(new slug.fbs.srtf.BoneLayer()).__assign(__p.__vector(o) + j * 72, __p.bb) : null; }
        public int BonesLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }

        public static Offset<slug.fbs.srtf.Vertex> CreateVertex(FlatBufferBuilder builder,
            slug.fbs.srtf.Vector3T position = null,
            slug.fbs.srtf.Vector3T normal = null,
            VectorOffset uvsOffset = default(VectorOffset),
            VectorOffset tangentsOffset = default(VectorOffset),
            VectorOffset binormalsOffset = default(VectorOffset),
            VectorOffset colorsOffset = default(VectorOffset),
            VectorOffset bonesOffset = default(VectorOffset))
        {
            builder.StartTable(7);
            Vertex.AddBones(builder, bonesOffset);
            Vertex.AddColors(builder, colorsOffset);
            Vertex.AddBinormals(builder, binormalsOffset);
            Vertex.AddTangents(builder, tangentsOffset);
            Vertex.AddUvs(builder, uvsOffset);
            Vertex.AddNormal(builder, slug.fbs.srtf.Vector3.Pack(builder, normal));
            Vertex.AddPosition(builder, slug.fbs.srtf.Vector3.Pack(builder, position));
            return Vertex.EndVertex(builder);
        }

        public static void StartVertex(FlatBufferBuilder builder) { builder.StartTable(7); }
        public static void AddPosition(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Vector3> positionOffset) { builder.AddStruct(0, positionOffset.Value, 0); }
        public static void AddNormal(FlatBufferBuilder builder, Offset<slug.fbs.srtf.Vector3> normalOffset) { builder.AddStruct(1, normalOffset.Value, 0); }
        public static void AddUvs(FlatBufferBuilder builder, VectorOffset uvsOffset) { builder.AddOffset(2, uvsOffset.Value, 0); }
        public static void StartUvsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(76, numElems, 4); }
        public static void AddTangents(FlatBufferBuilder builder, VectorOffset tangentsOffset) { builder.AddOffset(3, tangentsOffset.Value, 0); }
        public static void StartTangentsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(76, numElems, 4); }
        public static void AddBinormals(FlatBufferBuilder builder, VectorOffset binormalsOffset) { builder.AddOffset(4, binormalsOffset.Value, 0); }
        public static void StartBinormalsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(76, numElems, 4); }
        public static void AddColors(FlatBufferBuilder builder, VectorOffset colorsOffset) { builder.AddOffset(5, colorsOffset.Value, 0); }
        public static void StartColorsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(80, numElems, 4); }
        public static void AddBones(FlatBufferBuilder builder, VectorOffset bonesOffset) { builder.AddOffset(6, bonesOffset.Value, 0); }
        public static void StartBonesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(72, numElems, 4); }
        public static Offset<slug.fbs.srtf.Vertex> EndVertex(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.Vertex>(o);
        }
        public VertexT UnPack()
        {
            var _o = new VertexT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(VertexT _o)
        {
            _o.Position = this.Position.HasValue ? this.Position.Value.UnPack() : null;
            _o.Normal = this.Normal.HasValue ? this.Normal.Value.UnPack() : null;
            _o.Uvs = new List<slug.fbs.srtf.UVLayerT>();
            for (var _j = 0; _j < this.UvsLength; ++_j) { _o.Uvs.Add(this.Uvs(_j).HasValue ? this.Uvs(_j).Value.UnPack() : null); }
            _o.Tangents = new List<slug.fbs.srtf.TangentLayerT>();
            for (var _j = 0; _j < this.TangentsLength; ++_j) { _o.Tangents.Add(this.Tangents(_j).HasValue ? this.Tangents(_j).Value.UnPack() : null); }
            _o.Binormals = new List<slug.fbs.srtf.BinormalLayerT>();
            for (var _j = 0; _j < this.BinormalsLength; ++_j) { _o.Binormals.Add(this.Binormals(_j).HasValue ? this.Binormals(_j).Value.UnPack() : null); }
            _o.Colors = new List<slug.fbs.srtf.ColorLayerT>();
            for (var _j = 0; _j < this.ColorsLength; ++_j) { _o.Colors.Add(this.Colors(_j).HasValue ? this.Colors(_j).Value.UnPack() : null); }
            _o.Bones = new List<slug.fbs.srtf.BoneLayerT>();
            for (var _j = 0; _j < this.BonesLength; ++_j) { _o.Bones.Add(this.Bones(_j).HasValue ? this.Bones(_j).Value.UnPack() : null); }
        }
        public static Offset<slug.fbs.srtf.Vertex> Pack(FlatBufferBuilder builder, VertexT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.Vertex>);
            var _uvs = default(VectorOffset);
            if (_o.Uvs != null)
            {
                StartUvsVector(builder, _o.Uvs.Count);
                for (var _j = _o.Uvs.Count - 1; _j >= 0; --_j) { slug.fbs.srtf.UVLayer.Pack(builder, _o.Uvs[_j]); }
                _uvs = builder.EndVector();
            }
            var _tangents = default(VectorOffset);
            if (_o.Tangents != null)
            {
                StartTangentsVector(builder, _o.Tangents.Count);
                for (var _j = _o.Tangents.Count - 1; _j >= 0; --_j) { slug.fbs.srtf.TangentLayer.Pack(builder, _o.Tangents[_j]); }
                _tangents = builder.EndVector();
            }
            var _binormals = default(VectorOffset);
            if (_o.Binormals != null)
            {
                StartBinormalsVector(builder, _o.Binormals.Count);
                for (var _j = _o.Binormals.Count - 1; _j >= 0; --_j) { slug.fbs.srtf.BinormalLayer.Pack(builder, _o.Binormals[_j]); }
                _binormals = builder.EndVector();
            }
            var _colors = default(VectorOffset);
            if (_o.Colors != null)
            {
                StartColorsVector(builder, _o.Colors.Count);
                for (var _j = _o.Colors.Count - 1; _j >= 0; --_j) { slug.fbs.srtf.ColorLayer.Pack(builder, _o.Colors[_j]); }
                _colors = builder.EndVector();
            }
            var _bones = default(VectorOffset);
            if (_o.Bones != null)
            {
                StartBonesVector(builder, _o.Bones.Count);
                for (var _j = _o.Bones.Count - 1; _j >= 0; --_j) { slug.fbs.srtf.BoneLayer.Pack(builder, _o.Bones[_j]); }
                _bones = builder.EndVector();
            }
            return CreateVertex(
              builder,
              _o.Position,
              _o.Normal,
              _uvs,
              _tangents,
              _binormals,
              _colors,
              _bones);
        }
    }

    public class VertexT
    {
        public slug.fbs.srtf.Vector3T Position { get; set; }
        public slug.fbs.srtf.Vector3T Normal { get; set; }
        public List<slug.fbs.srtf.UVLayerT> Uvs { get; set; }
        public List<slug.fbs.srtf.TangentLayerT> Tangents { get; set; }
        public List<slug.fbs.srtf.BinormalLayerT> Binormals { get; set; }
        public List<slug.fbs.srtf.ColorLayerT> Colors { get; set; }
        public List<slug.fbs.srtf.BoneLayerT> Bones { get; set; }

        public VertexT()
        {
            this.Position = new slug.fbs.srtf.Vector3T();
            this.Normal = new slug.fbs.srtf.Vector3T();
            this.Uvs = null;
            this.Tangents = null;
            this.Binormals = null;
            this.Colors = null;
            this.Bones = null;
        }
    }


    static public class VertexVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyField(tablePos, 4 /*Position*/, 12 /*slug.fbs.srtf.Vector3*/, 4, false)
              && verifier.VerifyField(tablePos, 6 /*Normal*/, 12 /*slug.fbs.srtf.Vector3*/, 4, false)
              && verifier.VerifyVectorOfData(tablePos, 8 /*Uvs*/, 76 /*slug.fbs.srtf.UVLayer*/, false)
              && verifier.VerifyVectorOfData(tablePos, 10 /*Tangents*/, 76 /*slug.fbs.srtf.TangentLayer*/, false)
              && verifier.VerifyVectorOfData(tablePos, 12 /*Binormals*/, 76 /*slug.fbs.srtf.BinormalLayer*/, false)
              && verifier.VerifyVectorOfData(tablePos, 14 /*Colors*/, 80 /*slug.fbs.srtf.ColorLayer*/, false)
              && verifier.VerifyVectorOfData(tablePos, 16 /*Bones*/, 72 /*slug.fbs.srtf.BoneLayer*/, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
