// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using global::Google.FlatBuffers;
using global::System;
using global::System.Collections.Generic;

namespace slug.fbs.srtf
{
    public struct VertexAccessor : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
        public static VertexAccessor GetRootAsVertexAccessor(ByteBuffer _bb) { return GetRootAsVertexAccessor(_bb, new VertexAccessor()); }
        public static VertexAccessor GetRootAsVertexAccessor(ByteBuffer _bb, VertexAccessor obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public VertexAccessor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public slug.fbs.srtf.SemanticType SemanticType { get { int o = __p.__offset(4); return o != 0 ? (slug.fbs.srtf.SemanticType)__p.bb.GetShort(o + __p.bb_pos) : slug.fbs.srtf.SemanticType.Position; } }
        public bool MutateSemanticType(slug.fbs.srtf.SemanticType semantic_type) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutShort(o + __p.bb_pos, (short)semantic_type); return true; } else { return false; } }
        public slug.fbs.srtf.SemanticType SemanticIndex { get { int o = __p.__offset(6); return o != 0 ? (slug.fbs.srtf.SemanticType)__p.bb.GetShort(o + __p.bb_pos) : slug.fbs.srtf.SemanticType.Position; } }
        public bool MutateSemanticIndex(slug.fbs.srtf.SemanticType semantic_index) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutShort(o + __p.bb_pos, (short)semantic_index); return true; } else { return false; } }
        public slug.fbs.srtf.VertexFormat Foramt { get { int o = __p.__offset(8); return o != 0 ? (slug.fbs.srtf.VertexFormat)__p.bb.GetShort(o + __p.bb_pos) : slug.fbs.srtf.VertexFormat.NONE; } }
        public bool MutateForamt(slug.fbs.srtf.VertexFormat foramt) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutShort(o + __p.bb_pos, (short)foramt); return true; } else { return false; } }
        public uint Offset { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateOffset(uint offset) { int o = __p.__offset(10); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, offset); return true; } else { return false; } }
        public uint Size { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool MutateSize(uint size) { int o = __p.__offset(12); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, size); return true; } else { return false; } }

        public static Offset<slug.fbs.srtf.VertexAccessor> CreateVertexAccessor(FlatBufferBuilder builder,
            slug.fbs.srtf.SemanticType semantic_type = slug.fbs.srtf.SemanticType.Position,
            slug.fbs.srtf.SemanticType semantic_index = slug.fbs.srtf.SemanticType.Position,
            slug.fbs.srtf.VertexFormat foramt = slug.fbs.srtf.VertexFormat.NONE,
            uint offset = 0,
            uint size = 0)
        {
            builder.StartTable(5);
            VertexAccessor.AddSize(builder, size);
            VertexAccessor.AddOffset(builder, offset);
            VertexAccessor.AddForamt(builder, foramt);
            VertexAccessor.AddSemanticIndex(builder, semantic_index);
            VertexAccessor.AddSemanticType(builder, semantic_type);
            return VertexAccessor.EndVertexAccessor(builder);
        }

        public static void StartVertexAccessor(FlatBufferBuilder builder) { builder.StartTable(5); }
        public static void AddSemanticType(FlatBufferBuilder builder, slug.fbs.srtf.SemanticType semanticType) { builder.AddShort(0, (short)semanticType, 0); }
        public static void AddSemanticIndex(FlatBufferBuilder builder, slug.fbs.srtf.SemanticType semanticIndex) { builder.AddShort(1, (short)semanticIndex, 0); }
        public static void AddForamt(FlatBufferBuilder builder, slug.fbs.srtf.VertexFormat foramt) { builder.AddShort(2, (short)foramt, 0); }
        public static void AddOffset(FlatBufferBuilder builder, uint offset) { builder.AddUint(3, offset, 0); }
        public static void AddSize(FlatBufferBuilder builder, uint size) { builder.AddUint(4, size, 0); }
        public static Offset<slug.fbs.srtf.VertexAccessor> EndVertexAccessor(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<slug.fbs.srtf.VertexAccessor>(o);
        }
        public VertexAccessorT UnPack()
        {
            var _o = new VertexAccessorT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(VertexAccessorT _o)
        {
            _o.SemanticType = this.SemanticType;
            _o.SemanticIndex = this.SemanticIndex;
            _o.Foramt = this.Foramt;
            _o.Offset = this.Offset;
            _o.Size = this.Size;
        }
        public static Offset<slug.fbs.srtf.VertexAccessor> Pack(FlatBufferBuilder builder, VertexAccessorT _o)
        {
            if (_o == null) return default(Offset<slug.fbs.srtf.VertexAccessor>);
            return CreateVertexAccessor(
              builder,
              _o.SemanticType,
              _o.SemanticIndex,
              _o.Foramt,
              _o.Offset,
              _o.Size);
        }
    }

    public class VertexAccessorT
    {
        public slug.fbs.srtf.SemanticType SemanticType { get; set; }
        public slug.fbs.srtf.SemanticType SemanticIndex { get; set; }
        public slug.fbs.srtf.VertexFormat Foramt { get; set; }
        public uint Offset { get; set; }
        public uint Size { get; set; }

        public VertexAccessorT()
        {
            this.SemanticType = slug.fbs.srtf.SemanticType.Position;
            this.SemanticIndex = slug.fbs.srtf.SemanticType.Position;
            this.Foramt = slug.fbs.srtf.VertexFormat.NONE;
            this.Offset = 0;
            this.Size = 0;
        }
    }


    static public class VertexAccessorVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyField(tablePos, 4 /*SemanticType*/, 2 /*slug.fbs.srtf.SemanticType*/, 2, false)
              && verifier.VerifyField(tablePos, 6 /*SemanticIndex*/, 2 /*slug.fbs.srtf.SemanticType*/, 2, false)
              && verifier.VerifyField(tablePos, 8 /*Foramt*/, 2 /*slug.fbs.srtf.VertexFormat*/, 2, false)
              && verifier.VerifyField(tablePos, 10 /*Offset*/, 4 /*uint*/, 4, false)
              && verifier.VerifyField(tablePos, 12 /*Size*/, 4 /*uint*/, 4, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
