macro(setup_thirdparty_predefine)
    if(${SLUG_USE_GOOGLETEST})
        LIST(APPEND COMPILE_DEFINATIONS_ALL SLUG_USE_GOOGLETEST)
    endif()

    if(${SLUG_USE_GOOGLEBENCHMARK})
        LIST(APPEND COMPILE_DEFINATIONS_ALL SLUG_USE_GOOGLEBENCHMARK)
    endif()

    if(${SLUG_USE_MIMALLOC})
        LIST(APPEND COMPILE_DEFINATIONS_ALL SLUG_USE_MIMALLOC)
    endif()

    if(${SLUG_USE_CEREAL})
        LIST(APPEND COMPILE_DEFINATIONS_ALL SLUG_USE_CEREAL)
    endif()

    if(${SLUG_USE_FLATBUFFERS})
        LIST(APPEND COMPILE_DEFINATIONS_ALL SLUG_USE_FLATBUFFERS)
    endif()

    if(${SLUG_USE_FLATC})
        LIST(APPEND COMPILE_DEFINATIONS_ALL SLUG_USE_FLATC)
    endif()

    if(${SLUG_USE_LLVM})
        LIST(APPEND COMPILE_DEFINATIONS_ALL SLUG_USE_LLVM)
    endif()
endmacro()