// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_SLUG_FBS_SRTF_H_
#define FLATBUFFERS_GENERATED_COMMON_SLUG_FBS_SRTF_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace slug {
namespace fbs {
namespace srtf {

struct Vector2;

struct Vector3;

struct Vector4;

struct Matrix3x3;

struct Matrix4x4;

struct AABB;

struct BoolParameter;
struct BoolParameterBuilder;

struct FloatParameter;
struct FloatParameterBuilder;

struct FloatArrayParameter;
struct FloatArrayParameterBuilder;

struct Vector2Parameter;
struct Vector2ParameterBuilder;

struct Vector3Parameter;
struct Vector3ParameterBuilder;

struct Vector4Parameter;
struct Vector4ParameterBuilder;

struct Matrix3x3Parameter;
struct Matrix3x3ParameterBuilder;

struct Matrix4x4Parameter;
struct Matrix4x4ParameterBuilder;

inline const ::flatbuffers::TypeTable *Vector2TypeTable();

inline const ::flatbuffers::TypeTable *Vector3TypeTable();

inline const ::flatbuffers::TypeTable *Vector4TypeTable();

inline const ::flatbuffers::TypeTable *Matrix3x3TypeTable();

inline const ::flatbuffers::TypeTable *Matrix4x4TypeTable();

inline const ::flatbuffers::TypeTable *AABBTypeTable();

inline const ::flatbuffers::TypeTable *BoolParameterTypeTable();

inline const ::flatbuffers::TypeTable *FloatParameterTypeTable();

inline const ::flatbuffers::TypeTable *FloatArrayParameterTypeTable();

inline const ::flatbuffers::TypeTable *Vector2ParameterTypeTable();

inline const ::flatbuffers::TypeTable *Vector3ParameterTypeTable();

inline const ::flatbuffers::TypeTable *Vector4ParameterTypeTable();

inline const ::flatbuffers::TypeTable *Matrix3x3ParameterTypeTable();

inline const ::flatbuffers::TypeTable *Matrix4x4ParameterTypeTable();

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Vector2TypeTable();
  }
  Vector2()
      : x_(0),
        y_(0) {
  }
  Vector2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  void mutate_x(float _x) {
    ::flatbuffers::WriteScalar(&x_, _x);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  void mutate_y(float _y) {
    ::flatbuffers::WriteScalar(&y_, _y);
  }
};
FLATBUFFERS_STRUCT_END(Vector2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Vector3TypeTable();
  }
  Vector3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vector3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  void mutate_x(float _x) {
    ::flatbuffers::WriteScalar(&x_, _x);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  void mutate_y(float _y) {
    ::flatbuffers::WriteScalar(&y_, _y);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  void mutate_z(float _z) {
    ::flatbuffers::WriteScalar(&z_, _z);
  }
};
FLATBUFFERS_STRUCT_END(Vector3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector4 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Vector4TypeTable();
  }
  Vector4()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vector4(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  void mutate_x(float _x) {
    ::flatbuffers::WriteScalar(&x_, _x);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  void mutate_y(float _y) {
    ::flatbuffers::WriteScalar(&y_, _y);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  void mutate_z(float _z) {
    ::flatbuffers::WriteScalar(&z_, _z);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
  void mutate_w(float _w) {
    ::flatbuffers::WriteScalar(&w_, _w);
  }
};
FLATBUFFERS_STRUCT_END(Vector4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Matrix3x3 FLATBUFFERS_FINAL_CLASS {
 private:
  float m_[9];

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Matrix3x3TypeTable();
  }
  Matrix3x3()
      : m_() {
  }
  Matrix3x3(::flatbuffers::span<const float, 9> _m) {
    ::flatbuffers::CastToArray(m_).CopyFromSpan(_m);
  }
  const ::flatbuffers::Array<float, 9> *m() const {
    return &::flatbuffers::CastToArray(m_);
  }
  ::flatbuffers::Array<float, 9> *mutable_m() {
    return &::flatbuffers::CastToArray(m_);
  }
};
FLATBUFFERS_STRUCT_END(Matrix3x3, 36);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Matrix4x4 FLATBUFFERS_FINAL_CLASS {
 private:
  float m_[16];

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Matrix4x4TypeTable();
  }
  Matrix4x4()
      : m_() {
  }
  Matrix4x4(::flatbuffers::span<const float, 16> _m) {
    ::flatbuffers::CastToArray(m_).CopyFromSpan(_m);
  }
  const ::flatbuffers::Array<float, 16> *m() const {
    return &::flatbuffers::CastToArray(m_);
  }
  ::flatbuffers::Array<float, 16> *mutable_m() {
    return &::flatbuffers::CastToArray(m_);
  }
};
FLATBUFFERS_STRUCT_END(Matrix4x4, 64);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) AABB FLATBUFFERS_FINAL_CLASS {
 private:
  slug::fbs::srtf::Vector3 max_;
  slug::fbs::srtf::Vector3 min_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return AABBTypeTable();
  }
  AABB()
      : max_(),
        min_() {
  }
  AABB(const slug::fbs::srtf::Vector3 &_max, const slug::fbs::srtf::Vector3 &_min)
      : max_(_max),
        min_(_min) {
  }
  const slug::fbs::srtf::Vector3 &max() const {
    return max_;
  }
  slug::fbs::srtf::Vector3 &mutable_max() {
    return max_;
  }
  const slug::fbs::srtf::Vector3 &min() const {
    return min_;
  }
  slug::fbs::srtf::Vector3 &mutable_min() {
    return min_;
  }
};
FLATBUFFERS_STRUCT_END(AABB, 24);

struct BoolParameter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoolParameterBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return BoolParameterTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  bool value() const {
    return GetField<uint8_t>(VT_VALUE, 0) != 0;
  }
  bool mutate_value(bool _value = 0) {
    return SetField<uint8_t>(VT_VALUE, static_cast<uint8_t>(_value), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_VALUE, 1) &&
           verifier.EndTable();
  }
};

struct BoolParameterBuilder {
  typedef BoolParameter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(BoolParameter::VT_NAME, name);
  }
  void add_value(bool value) {
    fbb_.AddElement<uint8_t>(BoolParameter::VT_VALUE, static_cast<uint8_t>(value), 0);
  }
  explicit BoolParameterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BoolParameter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BoolParameter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BoolParameter> CreateBoolParameter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    bool value = false) {
  BoolParameterBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_value(value);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BoolParameter> CreateBoolParameterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    bool value = false) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return slug::fbs::srtf::CreateBoolParameter(
      _fbb,
      name__,
      value);
}

struct FloatParameter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FloatParameterBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return FloatParameterTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  bool mutate_value(float _value = 0.0f) {
    return SetField<float>(VT_VALUE, _value, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<float>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct FloatParameterBuilder {
  typedef FloatParameter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(FloatParameter::VT_NAME, name);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(FloatParameter::VT_VALUE, value, 0.0f);
  }
  explicit FloatParameterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FloatParameter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FloatParameter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FloatParameter> CreateFloatParameter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    float value = 0.0f) {
  FloatParameterBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FloatParameter> CreateFloatParameterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    float value = 0.0f) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return slug::fbs::srtf::CreateFloatParameter(
      _fbb,
      name__,
      value);
}

struct FloatArrayParameter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FloatArrayParameterBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return FloatArrayParameterTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<float> *value() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_VALUE);
  }
  ::flatbuffers::Vector<float> *mutable_value() {
    return GetPointer<::flatbuffers::Vector<float> *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.EndTable();
  }
};

struct FloatArrayParameterBuilder {
  typedef FloatArrayParameter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(FloatArrayParameter::VT_NAME, name);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::Vector<float>> value) {
    fbb_.AddOffset(FloatArrayParameter::VT_VALUE, value);
  }
  explicit FloatArrayParameterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FloatArrayParameter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FloatArrayParameter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FloatArrayParameter> CreateFloatArrayParameter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> value = 0) {
  FloatArrayParameterBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FloatArrayParameter> CreateFloatArrayParameterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<float> *value = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto value__ = value ? _fbb.CreateVector<float>(*value) : 0;
  return slug::fbs::srtf::CreateFloatArrayParameter(
      _fbb,
      name__,
      value__);
}

struct Vector2Parameter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vector2ParameterBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Vector2ParameterTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const slug::fbs::srtf::Vector2 *value() const {
    return GetStruct<const slug::fbs::srtf::Vector2 *>(VT_VALUE);
  }
  slug::fbs::srtf::Vector2 *mutable_value() {
    return GetStruct<slug::fbs::srtf::Vector2 *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<slug::fbs::srtf::Vector2>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct Vector2ParameterBuilder {
  typedef Vector2Parameter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Vector2Parameter::VT_NAME, name);
  }
  void add_value(const slug::fbs::srtf::Vector2 *value) {
    fbb_.AddStruct(Vector2Parameter::VT_VALUE, value);
  }
  explicit Vector2ParameterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vector2Parameter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vector2Parameter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vector2Parameter> CreateVector2Parameter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const slug::fbs::srtf::Vector2 *value = nullptr) {
  Vector2ParameterBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Vector2Parameter> CreateVector2ParameterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const slug::fbs::srtf::Vector2 *value = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return slug::fbs::srtf::CreateVector2Parameter(
      _fbb,
      name__,
      value);
}

struct Vector3Parameter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vector3ParameterBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Vector3ParameterTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const slug::fbs::srtf::Vector3 *value() const {
    return GetStruct<const slug::fbs::srtf::Vector3 *>(VT_VALUE);
  }
  slug::fbs::srtf::Vector3 *mutable_value() {
    return GetStruct<slug::fbs::srtf::Vector3 *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<slug::fbs::srtf::Vector3>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct Vector3ParameterBuilder {
  typedef Vector3Parameter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Vector3Parameter::VT_NAME, name);
  }
  void add_value(const slug::fbs::srtf::Vector3 *value) {
    fbb_.AddStruct(Vector3Parameter::VT_VALUE, value);
  }
  explicit Vector3ParameterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vector3Parameter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vector3Parameter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vector3Parameter> CreateVector3Parameter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const slug::fbs::srtf::Vector3 *value = nullptr) {
  Vector3ParameterBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Vector3Parameter> CreateVector3ParameterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const slug::fbs::srtf::Vector3 *value = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return slug::fbs::srtf::CreateVector3Parameter(
      _fbb,
      name__,
      value);
}

struct Vector4Parameter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vector4ParameterBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Vector4ParameterTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const slug::fbs::srtf::Vector4 *value() const {
    return GetStruct<const slug::fbs::srtf::Vector4 *>(VT_VALUE);
  }
  slug::fbs::srtf::Vector4 *mutable_value() {
    return GetStruct<slug::fbs::srtf::Vector4 *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<slug::fbs::srtf::Vector4>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct Vector4ParameterBuilder {
  typedef Vector4Parameter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Vector4Parameter::VT_NAME, name);
  }
  void add_value(const slug::fbs::srtf::Vector4 *value) {
    fbb_.AddStruct(Vector4Parameter::VT_VALUE, value);
  }
  explicit Vector4ParameterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vector4Parameter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vector4Parameter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vector4Parameter> CreateVector4Parameter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const slug::fbs::srtf::Vector4 *value = nullptr) {
  Vector4ParameterBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Vector4Parameter> CreateVector4ParameterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const slug::fbs::srtf::Vector4 *value = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return slug::fbs::srtf::CreateVector4Parameter(
      _fbb,
      name__,
      value);
}

struct Matrix3x3Parameter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Matrix3x3ParameterBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Matrix3x3ParameterTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const slug::fbs::srtf::Matrix3x3 *value() const {
    return GetStruct<const slug::fbs::srtf::Matrix3x3 *>(VT_VALUE);
  }
  slug::fbs::srtf::Matrix3x3 *mutable_value() {
    return GetStruct<slug::fbs::srtf::Matrix3x3 *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<slug::fbs::srtf::Matrix3x3>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct Matrix3x3ParameterBuilder {
  typedef Matrix3x3Parameter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Matrix3x3Parameter::VT_NAME, name);
  }
  void add_value(const slug::fbs::srtf::Matrix3x3 *value) {
    fbb_.AddStruct(Matrix3x3Parameter::VT_VALUE, value);
  }
  explicit Matrix3x3ParameterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Matrix3x3Parameter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Matrix3x3Parameter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Matrix3x3Parameter> CreateMatrix3x3Parameter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const slug::fbs::srtf::Matrix3x3 *value = nullptr) {
  Matrix3x3ParameterBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Matrix3x3Parameter> CreateMatrix3x3ParameterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const slug::fbs::srtf::Matrix3x3 *value = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return slug::fbs::srtf::CreateMatrix3x3Parameter(
      _fbb,
      name__,
      value);
}

struct Matrix4x4Parameter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Matrix4x4ParameterBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Matrix4x4ParameterTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const slug::fbs::srtf::Matrix4x4 *value() const {
    return GetStruct<const slug::fbs::srtf::Matrix4x4 *>(VT_VALUE);
  }
  slug::fbs::srtf::Matrix4x4 *mutable_value() {
    return GetStruct<slug::fbs::srtf::Matrix4x4 *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<slug::fbs::srtf::Matrix4x4>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct Matrix4x4ParameterBuilder {
  typedef Matrix4x4Parameter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Matrix4x4Parameter::VT_NAME, name);
  }
  void add_value(const slug::fbs::srtf::Matrix4x4 *value) {
    fbb_.AddStruct(Matrix4x4Parameter::VT_VALUE, value);
  }
  explicit Matrix4x4ParameterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Matrix4x4Parameter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Matrix4x4Parameter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Matrix4x4Parameter> CreateMatrix4x4Parameter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const slug::fbs::srtf::Matrix4x4 *value = nullptr) {
  Matrix4x4ParameterBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Matrix4x4Parameter> CreateMatrix4x4ParameterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const slug::fbs::srtf::Matrix4x4 *value = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return slug::fbs::srtf::CreateMatrix4x4Parameter(
      _fbb,
      name__,
      value);
}

inline const ::flatbuffers::TypeTable *Vector2TypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_FLOAT, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 0, -1 }
  };
  static const int64_t values[] = { 0, 4, 8 };
  static const char * const names[] = {
    "x",
    "y"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 2, type_codes, nullptr, nullptr, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *Vector3TypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_FLOAT, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 0, -1 }
  };
  static const int64_t values[] = { 0, 4, 8, 12 };
  static const char * const names[] = {
    "x",
    "y",
    "z"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 3, type_codes, nullptr, nullptr, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *Vector4TypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_FLOAT, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 0, -1 }
  };
  static const int64_t values[] = { 0, 4, 8, 12, 16 };
  static const char * const names[] = {
    "x",
    "y",
    "z",
    "w"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 4, type_codes, nullptr, nullptr, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *Matrix3x3TypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_FLOAT, 1, -1 }
  };
  static const int16_t array_sizes[] = { 9,  };
  static const int64_t values[] = { 0, 36 };
  static const char * const names[] = {
    "m"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 1, type_codes, nullptr, array_sizes, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *Matrix4x4TypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_FLOAT, 1, -1 }
  };
  static const int16_t array_sizes[] = { 16,  };
  static const int64_t values[] = { 0, 64 };
  static const char * const names[] = {
    "m"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 1, type_codes, nullptr, array_sizes, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *AABBTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Vector3TypeTable
  };
  static const int64_t values[] = { 0, 12, 24 };
  static const char * const names[] = {
    "max",
    "min"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 2, type_codes, type_refs, nullptr, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *BoolParameterTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 }
  };
  static const char * const names[] = {
    "name",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *FloatParameterTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 0, -1 }
  };
  static const char * const names[] = {
    "name",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *FloatArrayParameterTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 1, -1 }
  };
  static const char * const names[] = {
    "name",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *Vector2ParameterTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Vector2TypeTable
  };
  static const char * const names[] = {
    "name",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *Vector3ParameterTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Vector3TypeTable
  };
  static const char * const names[] = {
    "name",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *Vector4ParameterTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Vector4TypeTable
  };
  static const char * const names[] = {
    "name",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *Matrix3x3ParameterTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Matrix3x3TypeTable
  };
  static const char * const names[] = {
    "name",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *Matrix4x4ParameterTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Matrix4x4TypeTable
  };
  static const char * const names[] = {
    "name",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace srtf
}  // namespace fbs
}  // namespace slug

#endif  // FLATBUFFERS_GENERATED_COMMON_SLUG_FBS_SRTF_H_
