// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MATERIALS_SLUG_FBS_SRTF_H_
#define FLATBUFFERS_GENERATED_MATERIALS_SLUG_FBS_SRTF_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "Shader_fbs.h"

namespace slug {
namespace fbs {
namespace srtf {

struct Material;
struct MaterialBuilder;

inline const ::flatbuffers::TypeTable *MaterialTypeTable();

struct Material FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return MaterialTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SHADER = 4,
    VT_NAME = 6,
    VT_DRAW_SETTINGS = 8,
    VT_TEXTUERS = 10,
    VT_STATIC_SWICHES = 12,
    VT_CONSTANT_PARAMETER = 14
  };
  const ::flatbuffers::String *shader() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SHADER);
  }
  ::flatbuffers::String *mutable_shader() {
    return GetPointer<::flatbuffers::String *>(VT_SHADER);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const slug::fbs::srtf::DrawSettings *draw_settings() const {
    return GetPointer<const slug::fbs::srtf::DrawSettings *>(VT_DRAW_SETTINGS);
  }
  slug::fbs::srtf::DrawSettings *mutable_draw_settings() {
    return GetPointer<slug::fbs::srtf::DrawSettings *>(VT_DRAW_SETTINGS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>> *textuers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>> *>(VT_TEXTUERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>> *mutable_textuers() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>> *>(VT_TEXTUERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *static_swiches() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *>(VT_STATIC_SWICHES);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *mutable_static_swiches() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *>(VT_STATIC_SWICHES);
  }
  const slug::fbs::srtf::ConstantParameter *constant_parameter() const {
    return GetPointer<const slug::fbs::srtf::ConstantParameter *>(VT_CONSTANT_PARAMETER);
  }
  slug::fbs::srtf::ConstantParameter *mutable_constant_parameter() {
    return GetPointer<slug::fbs::srtf::ConstantParameter *>(VT_CONSTANT_PARAMETER);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SHADER) &&
           verifier.VerifyString(shader()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_DRAW_SETTINGS) &&
           verifier.VerifyTable(draw_settings()) &&
           VerifyOffset(verifier, VT_TEXTUERS) &&
           verifier.VerifyVector(textuers()) &&
           verifier.VerifyVectorOfTables(textuers()) &&
           VerifyOffset(verifier, VT_STATIC_SWICHES) &&
           verifier.VerifyVector(static_swiches()) &&
           verifier.VerifyVectorOfTables(static_swiches()) &&
           VerifyOffset(verifier, VT_CONSTANT_PARAMETER) &&
           verifier.VerifyTable(constant_parameter()) &&
           verifier.EndTable();
  }
};

struct MaterialBuilder {
  typedef Material Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_shader(::flatbuffers::Offset<::flatbuffers::String> shader) {
    fbb_.AddOffset(Material::VT_SHADER, shader);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Material::VT_NAME, name);
  }
  void add_draw_settings(::flatbuffers::Offset<slug::fbs::srtf::DrawSettings> draw_settings) {
    fbb_.AddOffset(Material::VT_DRAW_SETTINGS, draw_settings);
  }
  void add_textuers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>>> textuers) {
    fbb_.AddOffset(Material::VT_TEXTUERS, textuers);
  }
  void add_static_swiches(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>>> static_swiches) {
    fbb_.AddOffset(Material::VT_STATIC_SWICHES, static_swiches);
  }
  void add_constant_parameter(::flatbuffers::Offset<slug::fbs::srtf::ConstantParameter> constant_parameter) {
    fbb_.AddOffset(Material::VT_CONSTANT_PARAMETER, constant_parameter);
  }
  explicit MaterialBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Material> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Material>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Material> CreateMaterial(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> shader = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<slug::fbs::srtf::DrawSettings> draw_settings = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>>> textuers = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>>> static_swiches = 0,
    ::flatbuffers::Offset<slug::fbs::srtf::ConstantParameter> constant_parameter = 0) {
  MaterialBuilder builder_(_fbb);
  builder_.add_constant_parameter(constant_parameter);
  builder_.add_static_swiches(static_swiches);
  builder_.add_textuers(textuers);
  builder_.add_draw_settings(draw_settings);
  builder_.add_name(name);
  builder_.add_shader(shader);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Material> CreateMaterialDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *shader = nullptr,
    const char *name = nullptr,
    ::flatbuffers::Offset<slug::fbs::srtf::DrawSettings> draw_settings = 0,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>> *textuers = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *static_swiches = nullptr,
    ::flatbuffers::Offset<slug::fbs::srtf::ConstantParameter> constant_parameter = 0) {
  auto shader__ = shader ? _fbb.CreateString(shader) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto textuers__ = textuers ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>>(*textuers) : 0;
  auto static_swiches__ = static_swiches ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>>(*static_swiches) : 0;
  return slug::fbs::srtf::CreateMaterial(
      _fbb,
      shader__,
      name__,
      draw_settings,
      textuers__,
      static_swiches__,
      constant_parameter);
}

inline const ::flatbuffers::TypeTable *MaterialTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 1, 1 },
    { ::flatbuffers::ET_SEQUENCE, 1, 2 },
    { ::flatbuffers::ET_SEQUENCE, 0, 3 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::DrawSettingsTypeTable,
    slug::fbs::srtf::TextureParameterTypeTable,
    slug::fbs::srtf::BoolParameterTypeTable,
    slug::fbs::srtf::ConstantParameterTypeTable
  };
  static const char * const names[] = {
    "shader",
    "name",
    "draw_settings",
    "textuers",
    "static_swiches",
    "constant_parameter"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 6, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const slug::fbs::srtf::Material *GetMaterial(const void *buf) {
  return ::flatbuffers::GetRoot<slug::fbs::srtf::Material>(buf);
}

inline const slug::fbs::srtf::Material *GetSizePrefixedMaterial(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<slug::fbs::srtf::Material>(buf);
}

inline Material *GetMutableMaterial(void *buf) {
  return ::flatbuffers::GetMutableRoot<Material>(buf);
}

inline slug::fbs::srtf::Material *GetMutableSizePrefixedMaterial(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<slug::fbs::srtf::Material>(buf);
}

inline const char *MaterialIdentifier() {
  return "MATE";
}

inline bool MaterialBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, MaterialIdentifier());
}

inline bool SizePrefixedMaterialBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, MaterialIdentifier(), true);
}

inline bool VerifyMaterialBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<slug::fbs::srtf::Material>(MaterialIdentifier());
}

inline bool VerifySizePrefixedMaterialBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<slug::fbs::srtf::Material>(MaterialIdentifier());
}

inline void FinishMaterialBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::Material> root) {
  fbb.Finish(root, MaterialIdentifier());
}

inline void FinishSizePrefixedMaterialBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::Material> root) {
  fbb.FinishSizePrefixed(root, MaterialIdentifier());
}

}  // namespace srtf
}  // namespace fbs
}  // namespace slug

#endif  // FLATBUFFERS_GENERATED_MATERIALS_SLUG_FBS_SRTF_H_
