// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MODEL_SLUG_FBS_SRTF_H_
#define FLATBUFFERS_GENERATED_MODEL_SLUG_FBS_SRTF_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "common_fbs.h"

namespace slug {
namespace fbs {
namespace srtf {

struct UVLayer;

struct TangentLayer;

struct BinormalLayer;

struct ColorLayer;

struct BoneLayer;

struct Vertex;
struct VertexBuilder;

struct Node;
struct NodeBuilder;

struct MaterialSlot;
struct MaterialSlotBuilder;

struct VertexAccessor;
struct VertexAccessorBuilder;

struct indexAccessor;
struct indexAccessorBuilder;

struct OptimizeMeshBuffer;
struct OptimizeMeshBufferBuilder;

struct OptimizeMesh;
struct OptimizeMeshBuilder;

struct Mesh;
struct MeshBuilder;

struct SubModel;
struct SubModelBuilder;

struct LodItemSettings;

struct LodSettings;
struct LodSettingsBuilder;

struct LodModel;
struct LodModelBuilder;

struct Model;
struct ModelBuilder;

inline const ::flatbuffers::TypeTable *UVLayerTypeTable();

inline const ::flatbuffers::TypeTable *TangentLayerTypeTable();

inline const ::flatbuffers::TypeTable *BinormalLayerTypeTable();

inline const ::flatbuffers::TypeTable *ColorLayerTypeTable();

inline const ::flatbuffers::TypeTable *BoneLayerTypeTable();

inline const ::flatbuffers::TypeTable *VertexTypeTable();

inline const ::flatbuffers::TypeTable *NodeTypeTable();

inline const ::flatbuffers::TypeTable *MaterialSlotTypeTable();

inline const ::flatbuffers::TypeTable *VertexAccessorTypeTable();

inline const ::flatbuffers::TypeTable *indexAccessorTypeTable();

inline const ::flatbuffers::TypeTable *OptimizeMeshBufferTypeTable();

inline const ::flatbuffers::TypeTable *OptimizeMeshTypeTable();

inline const ::flatbuffers::TypeTable *MeshTypeTable();

inline const ::flatbuffers::TypeTable *SubModelTypeTable();

inline const ::flatbuffers::TypeTable *LodItemSettingsTypeTable();

inline const ::flatbuffers::TypeTable *LodSettingsTypeTable();

inline const ::flatbuffers::TypeTable *LodModelTypeTable();

inline const ::flatbuffers::TypeTable *ModelTypeTable();

enum TopologyType : int16_t {
  TopologyType_PointList = 0,
  TopologyType_LineList = 1,
  TopologyType_LineStrip = 2,
  TopologyType_TriangleList = 3,
  TopologyType_TriangleStrip = 4,
  TopologyType_QuadList = 5,
  TopologyType_QuadStrip = 6,
  TopologyType_MIN = TopologyType_PointList,
  TopologyType_MAX = TopologyType_QuadStrip
};

inline const TopologyType (&EnumValuesTopologyType())[7] {
  static const TopologyType values[] = {
    TopologyType_PointList,
    TopologyType_LineList,
    TopologyType_LineStrip,
    TopologyType_TriangleList,
    TopologyType_TriangleStrip,
    TopologyType_QuadList,
    TopologyType_QuadStrip
  };
  return values;
}

inline const char * const *EnumNamesTopologyType() {
  static const char * const names[8] = {
    "PointList",
    "LineList",
    "LineStrip",
    "TriangleList",
    "TriangleStrip",
    "QuadList",
    "QuadStrip",
    nullptr
  };
  return names;
}

inline const char *EnumNameTopologyType(TopologyType e) {
  if (::flatbuffers::IsOutRange(e, TopologyType_PointList, TopologyType_QuadStrip)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTopologyType()[index];
}

enum SemanticType : int16_t {
  SemanticType_Position = 0,
  SemanticType_Normal = 1,
  SemanticType_Texcoord = 2,
  SemanticType_Tangent = 3,
  SemanticType_Binormal = 4,
  SemanticType_Color = 5,
  SemanticType_BoneIndex = 6,
  SemanticType_BoneWeight = 7,
  SemanticType_MIN = SemanticType_Position,
  SemanticType_MAX = SemanticType_BoneWeight
};

inline const SemanticType (&EnumValuesSemanticType())[8] {
  static const SemanticType values[] = {
    SemanticType_Position,
    SemanticType_Normal,
    SemanticType_Texcoord,
    SemanticType_Tangent,
    SemanticType_Binormal,
    SemanticType_Color,
    SemanticType_BoneIndex,
    SemanticType_BoneWeight
  };
  return values;
}

inline const char * const *EnumNamesSemanticType() {
  static const char * const names[9] = {
    "Position",
    "Normal",
    "Texcoord",
    "Tangent",
    "Binormal",
    "Color",
    "BoneIndex",
    "BoneWeight",
    nullptr
  };
  return names;
}

inline const char *EnumNameSemanticType(SemanticType e) {
  if (::flatbuffers::IsOutRange(e, SemanticType_Position, SemanticType_BoneWeight)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSemanticType()[index];
}

enum VertexFormat : int16_t {
  VertexFormat_NONE = 0,
  VertexFormat_BYTE1 = 1,
  VertexFormat_BYTE2 = 2,
  VertexFormat_BYTE3 = 3,
  VertexFormat_BYTE4 = 4,
  VertexFormat_BYTE4N = 5,
  VertexFormat_UBYTE1 = 6,
  VertexFormat_UBYTE2 = 7,
  VertexFormat_UBYTE3 = 8,
  VertexFormat_UBYTE4 = 9,
  VertexFormat_UBYTE8 = 10,
  VertexFormat_UBYTE4N = 11,
  VertexFormat_SHORT1 = 12,
  VertexFormat_SHORT2 = 13,
  VertexFormat_SHORT2N = 14,
  VertexFormat_SHORT3 = 15,
  VertexFormat_SHORT4 = 16,
  VertexFormat_SHORT4N = 17,
  VertexFormat_USHORT1 = 18,
  VertexFormat_USHORT2 = 19,
  VertexFormat_USHORT2N = 20,
  VertexFormat_USHORT3 = 21,
  VertexFormat_USHORT4 = 22,
  VertexFormat_USHORT4N = 23,
  VertexFormat_USHORT8 = 24,
  VertexFormat_INT1 = 25,
  VertexFormat_INT2 = 26,
  VertexFormat_INT3 = 27,
  VertexFormat_INT4 = 28,
  VertexFormat_UINT1 = 29,
  VertexFormat_UINT2 = 30,
  VertexFormat_UINT3 = 31,
  VertexFormat_UINT4 = 32,
  VertexFormat_FLOAT1 = 33,
  VertexFormat_FLOAT2 = 34,
  VertexFormat_FLOAT3 = 35,
  VertexFormat_FLOAT4 = 36,
  VertexFormat_R11G11B10Float = 37,
  VertexFormat_R10G10B10A2Unorm = 38,
  VertexFormat_MIN = VertexFormat_NONE,
  VertexFormat_MAX = VertexFormat_R10G10B10A2Unorm
};

inline const VertexFormat (&EnumValuesVertexFormat())[39] {
  static const VertexFormat values[] = {
    VertexFormat_NONE,
    VertexFormat_BYTE1,
    VertexFormat_BYTE2,
    VertexFormat_BYTE3,
    VertexFormat_BYTE4,
    VertexFormat_BYTE4N,
    VertexFormat_UBYTE1,
    VertexFormat_UBYTE2,
    VertexFormat_UBYTE3,
    VertexFormat_UBYTE4,
    VertexFormat_UBYTE8,
    VertexFormat_UBYTE4N,
    VertexFormat_SHORT1,
    VertexFormat_SHORT2,
    VertexFormat_SHORT2N,
    VertexFormat_SHORT3,
    VertexFormat_SHORT4,
    VertexFormat_SHORT4N,
    VertexFormat_USHORT1,
    VertexFormat_USHORT2,
    VertexFormat_USHORT2N,
    VertexFormat_USHORT3,
    VertexFormat_USHORT4,
    VertexFormat_USHORT4N,
    VertexFormat_USHORT8,
    VertexFormat_INT1,
    VertexFormat_INT2,
    VertexFormat_INT3,
    VertexFormat_INT4,
    VertexFormat_UINT1,
    VertexFormat_UINT2,
    VertexFormat_UINT3,
    VertexFormat_UINT4,
    VertexFormat_FLOAT1,
    VertexFormat_FLOAT2,
    VertexFormat_FLOAT3,
    VertexFormat_FLOAT4,
    VertexFormat_R11G11B10Float,
    VertexFormat_R10G10B10A2Unorm
  };
  return values;
}

inline const char * const *EnumNamesVertexFormat() {
  static const char * const names[40] = {
    "NONE",
    "BYTE1",
    "BYTE2",
    "BYTE3",
    "BYTE4",
    "BYTE4N",
    "UBYTE1",
    "UBYTE2",
    "UBYTE3",
    "UBYTE4",
    "UBYTE8",
    "UBYTE4N",
    "SHORT1",
    "SHORT2",
    "SHORT2N",
    "SHORT3",
    "SHORT4",
    "SHORT4N",
    "USHORT1",
    "USHORT2",
    "USHORT2N",
    "USHORT3",
    "USHORT4",
    "USHORT4N",
    "USHORT8",
    "INT1",
    "INT2",
    "INT3",
    "INT4",
    "UINT1",
    "UINT2",
    "UINT3",
    "UINT4",
    "FLOAT1",
    "FLOAT2",
    "FLOAT3",
    "FLOAT4",
    "R11G11B10Float",
    "R10G10B10A2Unorm",
    nullptr
  };
  return names;
}

inline const char *EnumNameVertexFormat(VertexFormat e) {
  if (::flatbuffers::IsOutRange(e, VertexFormat_NONE, VertexFormat_R10G10B10A2Unorm)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesVertexFormat()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) UVLayer FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t name_[64];
  slug::fbs::srtf::Vector3 uv_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return UVLayerTypeTable();
  }
  UVLayer()
      : name_(),
        uv_() {
  }
  UVLayer(const slug::fbs::srtf::Vector3 &_uv)
      : name_(),
        uv_(_uv) {
  }
  UVLayer(::flatbuffers::span<const uint8_t, 64> _name, const slug::fbs::srtf::Vector3 &_uv)
      : uv_(_uv) {
    ::flatbuffers::CastToArray(name_).CopyFromSpan(_name);
  }
  const ::flatbuffers::Array<uint8_t, 64> *name() const {
    return &::flatbuffers::CastToArray(name_);
  }
  ::flatbuffers::Array<uint8_t, 64> *mutable_name() {
    return &::flatbuffers::CastToArray(name_);
  }
  const slug::fbs::srtf::Vector3 &uv() const {
    return uv_;
  }
  slug::fbs::srtf::Vector3 &mutable_uv() {
    return uv_;
  }
};
FLATBUFFERS_STRUCT_END(UVLayer, 76);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) TangentLayer FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t name_[64];
  slug::fbs::srtf::Vector3 tangent_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return TangentLayerTypeTable();
  }
  TangentLayer()
      : name_(),
        tangent_() {
  }
  TangentLayer(const slug::fbs::srtf::Vector3 &_tangent)
      : name_(),
        tangent_(_tangent) {
  }
  TangentLayer(::flatbuffers::span<const uint8_t, 64> _name, const slug::fbs::srtf::Vector3 &_tangent)
      : tangent_(_tangent) {
    ::flatbuffers::CastToArray(name_).CopyFromSpan(_name);
  }
  const ::flatbuffers::Array<uint8_t, 64> *name() const {
    return &::flatbuffers::CastToArray(name_);
  }
  ::flatbuffers::Array<uint8_t, 64> *mutable_name() {
    return &::flatbuffers::CastToArray(name_);
  }
  const slug::fbs::srtf::Vector3 &tangent() const {
    return tangent_;
  }
  slug::fbs::srtf::Vector3 &mutable_tangent() {
    return tangent_;
  }
};
FLATBUFFERS_STRUCT_END(TangentLayer, 76);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) BinormalLayer FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t name_[64];
  slug::fbs::srtf::Vector3 binormal_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return BinormalLayerTypeTable();
  }
  BinormalLayer()
      : name_(),
        binormal_() {
  }
  BinormalLayer(const slug::fbs::srtf::Vector3 &_binormal)
      : name_(),
        binormal_(_binormal) {
  }
  BinormalLayer(::flatbuffers::span<const uint8_t, 64> _name, const slug::fbs::srtf::Vector3 &_binormal)
      : binormal_(_binormal) {
    ::flatbuffers::CastToArray(name_).CopyFromSpan(_name);
  }
  const ::flatbuffers::Array<uint8_t, 64> *name() const {
    return &::flatbuffers::CastToArray(name_);
  }
  ::flatbuffers::Array<uint8_t, 64> *mutable_name() {
    return &::flatbuffers::CastToArray(name_);
  }
  const slug::fbs::srtf::Vector3 &binormal() const {
    return binormal_;
  }
  slug::fbs::srtf::Vector3 &mutable_binormal() {
    return binormal_;
  }
};
FLATBUFFERS_STRUCT_END(BinormalLayer, 76);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) ColorLayer FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t name_[64];
  slug::fbs::srtf::Vector4 color_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ColorLayerTypeTable();
  }
  ColorLayer()
      : name_(),
        color_() {
  }
  ColorLayer(const slug::fbs::srtf::Vector4 &_color)
      : name_(),
        color_(_color) {
  }
  ColorLayer(::flatbuffers::span<const uint8_t, 64> _name, const slug::fbs::srtf::Vector4 &_color)
      : color_(_color) {
    ::flatbuffers::CastToArray(name_).CopyFromSpan(_name);
  }
  const ::flatbuffers::Array<uint8_t, 64> *name() const {
    return &::flatbuffers::CastToArray(name_);
  }
  ::flatbuffers::Array<uint8_t, 64> *mutable_name() {
    return &::flatbuffers::CastToArray(name_);
  }
  const slug::fbs::srtf::Vector4 &color() const {
    return color_;
  }
  slug::fbs::srtf::Vector4 &mutable_color() {
    return color_;
  }
};
FLATBUFFERS_STRUCT_END(ColorLayer, 80);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) BoneLayer FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t name_[64];
  int32_t id_;
  float weight_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return BoneLayerTypeTable();
  }
  BoneLayer()
      : name_(),
        id_(0),
        weight_(0) {
  }
  BoneLayer(int32_t _id, float _weight)
      : name_(),
        id_(::flatbuffers::EndianScalar(_id)),
        weight_(::flatbuffers::EndianScalar(_weight)) {
  }
  BoneLayer(::flatbuffers::span<const uint8_t, 64> _name, int32_t _id, float _weight)
      : id_(::flatbuffers::EndianScalar(_id)),
        weight_(::flatbuffers::EndianScalar(_weight)) {
    ::flatbuffers::CastToArray(name_).CopyFromSpan(_name);
  }
  const ::flatbuffers::Array<uint8_t, 64> *name() const {
    return &::flatbuffers::CastToArray(name_);
  }
  ::flatbuffers::Array<uint8_t, 64> *mutable_name() {
    return &::flatbuffers::CastToArray(name_);
  }
  int32_t id() const {
    return ::flatbuffers::EndianScalar(id_);
  }
  void mutate_id(int32_t _id) {
    ::flatbuffers::WriteScalar(&id_, _id);
  }
  float weight() const {
    return ::flatbuffers::EndianScalar(weight_);
  }
  void mutate_weight(float _weight) {
    ::flatbuffers::WriteScalar(&weight_, _weight);
  }
};
FLATBUFFERS_STRUCT_END(BoneLayer, 72);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) LodItemSettings FLATBUFFERS_FINAL_CLASS {
 private:
  float draw_pixel_area_ratio_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return LodItemSettingsTypeTable();
  }
  LodItemSettings()
      : draw_pixel_area_ratio_(0) {
  }
  LodItemSettings(float _draw_pixel_area_ratio)
      : draw_pixel_area_ratio_(::flatbuffers::EndianScalar(_draw_pixel_area_ratio)) {
  }
  float draw_pixel_area_ratio() const {
    return ::flatbuffers::EndianScalar(draw_pixel_area_ratio_);
  }
  void mutate_draw_pixel_area_ratio(float _draw_pixel_area_ratio) {
    ::flatbuffers::WriteScalar(&draw_pixel_area_ratio_, _draw_pixel_area_ratio);
  }
};
FLATBUFFERS_STRUCT_END(LodItemSettings, 4);

struct Vertex FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VertexBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return VertexTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_NORMAL = 6,
    VT_UVS = 8,
    VT_TANGENTS = 10,
    VT_BINORMALS = 12,
    VT_COLORS = 14,
    VT_BONES = 16
  };
  const slug::fbs::srtf::Vector3 *position() const {
    return GetStruct<const slug::fbs::srtf::Vector3 *>(VT_POSITION);
  }
  slug::fbs::srtf::Vector3 *mutable_position() {
    return GetStruct<slug::fbs::srtf::Vector3 *>(VT_POSITION);
  }
  const slug::fbs::srtf::Vector3 *normal() const {
    return GetStruct<const slug::fbs::srtf::Vector3 *>(VT_NORMAL);
  }
  slug::fbs::srtf::Vector3 *mutable_normal() {
    return GetStruct<slug::fbs::srtf::Vector3 *>(VT_NORMAL);
  }
  const ::flatbuffers::Vector<const slug::fbs::srtf::UVLayer *> *uvs() const {
    return GetPointer<const ::flatbuffers::Vector<const slug::fbs::srtf::UVLayer *> *>(VT_UVS);
  }
  ::flatbuffers::Vector<const slug::fbs::srtf::UVLayer *> *mutable_uvs() {
    return GetPointer<::flatbuffers::Vector<const slug::fbs::srtf::UVLayer *> *>(VT_UVS);
  }
  const ::flatbuffers::Vector<const slug::fbs::srtf::TangentLayer *> *tangents() const {
    return GetPointer<const ::flatbuffers::Vector<const slug::fbs::srtf::TangentLayer *> *>(VT_TANGENTS);
  }
  ::flatbuffers::Vector<const slug::fbs::srtf::TangentLayer *> *mutable_tangents() {
    return GetPointer<::flatbuffers::Vector<const slug::fbs::srtf::TangentLayer *> *>(VT_TANGENTS);
  }
  const ::flatbuffers::Vector<const slug::fbs::srtf::BinormalLayer *> *binormals() const {
    return GetPointer<const ::flatbuffers::Vector<const slug::fbs::srtf::BinormalLayer *> *>(VT_BINORMALS);
  }
  ::flatbuffers::Vector<const slug::fbs::srtf::BinormalLayer *> *mutable_binormals() {
    return GetPointer<::flatbuffers::Vector<const slug::fbs::srtf::BinormalLayer *> *>(VT_BINORMALS);
  }
  const ::flatbuffers::Vector<const slug::fbs::srtf::ColorLayer *> *colors() const {
    return GetPointer<const ::flatbuffers::Vector<const slug::fbs::srtf::ColorLayer *> *>(VT_COLORS);
  }
  ::flatbuffers::Vector<const slug::fbs::srtf::ColorLayer *> *mutable_colors() {
    return GetPointer<::flatbuffers::Vector<const slug::fbs::srtf::ColorLayer *> *>(VT_COLORS);
  }
  const ::flatbuffers::Vector<const slug::fbs::srtf::BoneLayer *> *bones() const {
    return GetPointer<const ::flatbuffers::Vector<const slug::fbs::srtf::BoneLayer *> *>(VT_BONES);
  }
  ::flatbuffers::Vector<const slug::fbs::srtf::BoneLayer *> *mutable_bones() {
    return GetPointer<::flatbuffers::Vector<const slug::fbs::srtf::BoneLayer *> *>(VT_BONES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<slug::fbs::srtf::Vector3>(verifier, VT_POSITION, 4) &&
           VerifyField<slug::fbs::srtf::Vector3>(verifier, VT_NORMAL, 4) &&
           VerifyOffset(verifier, VT_UVS) &&
           verifier.VerifyVector(uvs()) &&
           VerifyOffset(verifier, VT_TANGENTS) &&
           verifier.VerifyVector(tangents()) &&
           VerifyOffset(verifier, VT_BINORMALS) &&
           verifier.VerifyVector(binormals()) &&
           VerifyOffset(verifier, VT_COLORS) &&
           verifier.VerifyVector(colors()) &&
           VerifyOffset(verifier, VT_BONES) &&
           verifier.VerifyVector(bones()) &&
           verifier.EndTable();
  }
};

struct VertexBuilder {
  typedef Vertex Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(const slug::fbs::srtf::Vector3 *position) {
    fbb_.AddStruct(Vertex::VT_POSITION, position);
  }
  void add_normal(const slug::fbs::srtf::Vector3 *normal) {
    fbb_.AddStruct(Vertex::VT_NORMAL, normal);
  }
  void add_uvs(::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::UVLayer *>> uvs) {
    fbb_.AddOffset(Vertex::VT_UVS, uvs);
  }
  void add_tangents(::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::TangentLayer *>> tangents) {
    fbb_.AddOffset(Vertex::VT_TANGENTS, tangents);
  }
  void add_binormals(::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::BinormalLayer *>> binormals) {
    fbb_.AddOffset(Vertex::VT_BINORMALS, binormals);
  }
  void add_colors(::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::ColorLayer *>> colors) {
    fbb_.AddOffset(Vertex::VT_COLORS, colors);
  }
  void add_bones(::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::BoneLayer *>> bones) {
    fbb_.AddOffset(Vertex::VT_BONES, bones);
  }
  explicit VertexBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vertex> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vertex>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vertex> CreateVertex(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const slug::fbs::srtf::Vector3 *position = nullptr,
    const slug::fbs::srtf::Vector3 *normal = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::UVLayer *>> uvs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::TangentLayer *>> tangents = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::BinormalLayer *>> binormals = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::ColorLayer *>> colors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::BoneLayer *>> bones = 0) {
  VertexBuilder builder_(_fbb);
  builder_.add_bones(bones);
  builder_.add_colors(colors);
  builder_.add_binormals(binormals);
  builder_.add_tangents(tangents);
  builder_.add_uvs(uvs);
  builder_.add_normal(normal);
  builder_.add_position(position);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Vertex> CreateVertexDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const slug::fbs::srtf::Vector3 *position = nullptr,
    const slug::fbs::srtf::Vector3 *normal = nullptr,
    const std::vector<slug::fbs::srtf::UVLayer> *uvs = nullptr,
    const std::vector<slug::fbs::srtf::TangentLayer> *tangents = nullptr,
    const std::vector<slug::fbs::srtf::BinormalLayer> *binormals = nullptr,
    const std::vector<slug::fbs::srtf::ColorLayer> *colors = nullptr,
    const std::vector<slug::fbs::srtf::BoneLayer> *bones = nullptr) {
  auto uvs__ = uvs ? _fbb.CreateVectorOfStructs<slug::fbs::srtf::UVLayer>(*uvs) : 0;
  auto tangents__ = tangents ? _fbb.CreateVectorOfStructs<slug::fbs::srtf::TangentLayer>(*tangents) : 0;
  auto binormals__ = binormals ? _fbb.CreateVectorOfStructs<slug::fbs::srtf::BinormalLayer>(*binormals) : 0;
  auto colors__ = colors ? _fbb.CreateVectorOfStructs<slug::fbs::srtf::ColorLayer>(*colors) : 0;
  auto bones__ = bones ? _fbb.CreateVectorOfStructs<slug::fbs::srtf::BoneLayer>(*bones) : 0;
  return slug::fbs::srtf::CreateVertex(
      _fbb,
      position,
      normal,
      uvs__,
      tangents__,
      binormals__,
      colors__,
      bones__);
}

struct Node FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NodeBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return NodeTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_PARENT = 6,
    VT_BINDPOSE = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  int32_t parent() const {
    return GetField<int32_t>(VT_PARENT, 0);
  }
  bool mutate_parent(int32_t _parent = 0) {
    return SetField<int32_t>(VT_PARENT, _parent, 0);
  }
  const slug::fbs::srtf::Matrix4x4 *bindpose() const {
    return GetStruct<const slug::fbs::srtf::Matrix4x4 *>(VT_BINDPOSE);
  }
  slug::fbs::srtf::Matrix4x4 *mutable_bindpose() {
    return GetStruct<slug::fbs::srtf::Matrix4x4 *>(VT_BINDPOSE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_PARENT, 4) &&
           VerifyField<slug::fbs::srtf::Matrix4x4>(verifier, VT_BINDPOSE, 4) &&
           verifier.EndTable();
  }
};

struct NodeBuilder {
  typedef Node Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Node::VT_NAME, name);
  }
  void add_parent(int32_t parent) {
    fbb_.AddElement<int32_t>(Node::VT_PARENT, parent, 0);
  }
  void add_bindpose(const slug::fbs::srtf::Matrix4x4 *bindpose) {
    fbb_.AddStruct(Node::VT_BINDPOSE, bindpose);
  }
  explicit NodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Node> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Node>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Node> CreateNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t parent = 0,
    const slug::fbs::srtf::Matrix4x4 *bindpose = nullptr) {
  NodeBuilder builder_(_fbb);
  builder_.add_bindpose(bindpose);
  builder_.add_parent(parent);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Node> CreateNodeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int32_t parent = 0,
    const slug::fbs::srtf::Matrix4x4 *bindpose = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return slug::fbs::srtf::CreateNode(
      _fbb,
      name__,
      parent,
      bindpose);
}

struct MaterialSlot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialSlotBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return MaterialSlotTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SLOT = 4,
    VT_MATERIAL = 6
  };
  const ::flatbuffers::String *slot() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SLOT);
  }
  ::flatbuffers::String *mutable_slot() {
    return GetPointer<::flatbuffers::String *>(VT_SLOT);
  }
  const ::flatbuffers::String *material() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MATERIAL);
  }
  ::flatbuffers::String *mutable_material() {
    return GetPointer<::flatbuffers::String *>(VT_MATERIAL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SLOT) &&
           verifier.VerifyString(slot()) &&
           VerifyOffset(verifier, VT_MATERIAL) &&
           verifier.VerifyString(material()) &&
           verifier.EndTable();
  }
};

struct MaterialSlotBuilder {
  typedef MaterialSlot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_slot(::flatbuffers::Offset<::flatbuffers::String> slot) {
    fbb_.AddOffset(MaterialSlot::VT_SLOT, slot);
  }
  void add_material(::flatbuffers::Offset<::flatbuffers::String> material) {
    fbb_.AddOffset(MaterialSlot::VT_MATERIAL, material);
  }
  explicit MaterialSlotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MaterialSlot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MaterialSlot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MaterialSlot> CreateMaterialSlot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> slot = 0,
    ::flatbuffers::Offset<::flatbuffers::String> material = 0) {
  MaterialSlotBuilder builder_(_fbb);
  builder_.add_material(material);
  builder_.add_slot(slot);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MaterialSlot> CreateMaterialSlotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *slot = nullptr,
    const char *material = nullptr) {
  auto slot__ = slot ? _fbb.CreateString(slot) : 0;
  auto material__ = material ? _fbb.CreateString(material) : 0;
  return slug::fbs::srtf::CreateMaterialSlot(
      _fbb,
      slot__,
      material__);
}

struct VertexAccessor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VertexAccessorBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return VertexAccessorTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEMANTIC_TYPE = 4,
    VT_SEMANTIC_INDEX = 6,
    VT_FORAMT = 8,
    VT_OFFSET = 10,
    VT_SIZE = 12
  };
  slug::fbs::srtf::SemanticType semantic_type() const {
    return static_cast<slug::fbs::srtf::SemanticType>(GetField<int16_t>(VT_SEMANTIC_TYPE, 0));
  }
  bool mutate_semantic_type(slug::fbs::srtf::SemanticType _semantic_type = static_cast<slug::fbs::srtf::SemanticType>(0)) {
    return SetField<int16_t>(VT_SEMANTIC_TYPE, static_cast<int16_t>(_semantic_type), 0);
  }
  slug::fbs::srtf::SemanticType semantic_index() const {
    return static_cast<slug::fbs::srtf::SemanticType>(GetField<int16_t>(VT_SEMANTIC_INDEX, 0));
  }
  bool mutate_semantic_index(slug::fbs::srtf::SemanticType _semantic_index = static_cast<slug::fbs::srtf::SemanticType>(0)) {
    return SetField<int16_t>(VT_SEMANTIC_INDEX, static_cast<int16_t>(_semantic_index), 0);
  }
  slug::fbs::srtf::VertexFormat foramt() const {
    return static_cast<slug::fbs::srtf::VertexFormat>(GetField<int16_t>(VT_FORAMT, 0));
  }
  bool mutate_foramt(slug::fbs::srtf::VertexFormat _foramt = static_cast<slug::fbs::srtf::VertexFormat>(0)) {
    return SetField<int16_t>(VT_FORAMT, static_cast<int16_t>(_foramt), 0);
  }
  uint32_t offset() const {
    return GetField<uint32_t>(VT_OFFSET, 0);
  }
  bool mutate_offset(uint32_t _offset = 0) {
    return SetField<uint32_t>(VT_OFFSET, _offset, 0);
  }
  uint32_t size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  bool mutate_size(uint32_t _size = 0) {
    return SetField<uint32_t>(VT_SIZE, _size, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_SEMANTIC_TYPE, 2) &&
           VerifyField<int16_t>(verifier, VT_SEMANTIC_INDEX, 2) &&
           VerifyField<int16_t>(verifier, VT_FORAMT, 2) &&
           VerifyField<uint32_t>(verifier, VT_OFFSET, 4) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           verifier.EndTable();
  }
};

struct VertexAccessorBuilder {
  typedef VertexAccessor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_semantic_type(slug::fbs::srtf::SemanticType semantic_type) {
    fbb_.AddElement<int16_t>(VertexAccessor::VT_SEMANTIC_TYPE, static_cast<int16_t>(semantic_type), 0);
  }
  void add_semantic_index(slug::fbs::srtf::SemanticType semantic_index) {
    fbb_.AddElement<int16_t>(VertexAccessor::VT_SEMANTIC_INDEX, static_cast<int16_t>(semantic_index), 0);
  }
  void add_foramt(slug::fbs::srtf::VertexFormat foramt) {
    fbb_.AddElement<int16_t>(VertexAccessor::VT_FORAMT, static_cast<int16_t>(foramt), 0);
  }
  void add_offset(uint32_t offset) {
    fbb_.AddElement<uint32_t>(VertexAccessor::VT_OFFSET, offset, 0);
  }
  void add_size(uint32_t size) {
    fbb_.AddElement<uint32_t>(VertexAccessor::VT_SIZE, size, 0);
  }
  explicit VertexAccessorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VertexAccessor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VertexAccessor>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VertexAccessor> CreateVertexAccessor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    slug::fbs::srtf::SemanticType semantic_type = slug::fbs::srtf::SemanticType_Position,
    slug::fbs::srtf::SemanticType semantic_index = slug::fbs::srtf::SemanticType_Position,
    slug::fbs::srtf::VertexFormat foramt = slug::fbs::srtf::VertexFormat_NONE,
    uint32_t offset = 0,
    uint32_t size = 0) {
  VertexAccessorBuilder builder_(_fbb);
  builder_.add_size(size);
  builder_.add_offset(offset);
  builder_.add_foramt(foramt);
  builder_.add_semantic_index(semantic_index);
  builder_.add_semantic_type(semantic_type);
  return builder_.Finish();
}

struct indexAccessor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef indexAccessorBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return indexAccessorTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FORAMT = 4,
    VT_OFFSET = 6,
    VT_SIZE = 8
  };
  slug::fbs::srtf::VertexFormat foramt() const {
    return static_cast<slug::fbs::srtf::VertexFormat>(GetField<int16_t>(VT_FORAMT, 0));
  }
  bool mutate_foramt(slug::fbs::srtf::VertexFormat _foramt = static_cast<slug::fbs::srtf::VertexFormat>(0)) {
    return SetField<int16_t>(VT_FORAMT, static_cast<int16_t>(_foramt), 0);
  }
  uint32_t offset() const {
    return GetField<uint32_t>(VT_OFFSET, 0);
  }
  bool mutate_offset(uint32_t _offset = 0) {
    return SetField<uint32_t>(VT_OFFSET, _offset, 0);
  }
  uint32_t size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  bool mutate_size(uint32_t _size = 0) {
    return SetField<uint32_t>(VT_SIZE, _size, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_FORAMT, 2) &&
           VerifyField<uint32_t>(verifier, VT_OFFSET, 4) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           verifier.EndTable();
  }
};

struct indexAccessorBuilder {
  typedef indexAccessor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_foramt(slug::fbs::srtf::VertexFormat foramt) {
    fbb_.AddElement<int16_t>(indexAccessor::VT_FORAMT, static_cast<int16_t>(foramt), 0);
  }
  void add_offset(uint32_t offset) {
    fbb_.AddElement<uint32_t>(indexAccessor::VT_OFFSET, offset, 0);
  }
  void add_size(uint32_t size) {
    fbb_.AddElement<uint32_t>(indexAccessor::VT_SIZE, size, 0);
  }
  explicit indexAccessorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<indexAccessor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<indexAccessor>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<indexAccessor> CreateindexAccessor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    slug::fbs::srtf::VertexFormat foramt = slug::fbs::srtf::VertexFormat_NONE,
    uint32_t offset = 0,
    uint32_t size = 0) {
  indexAccessorBuilder builder_(_fbb);
  builder_.add_size(size);
  builder_.add_offset(offset);
  builder_.add_foramt(foramt);
  return builder_.Finish();
}

struct OptimizeMeshBuffer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OptimizeMeshBufferBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return OptimizeMeshBufferTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_SOURCE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<int8_t> *source() const {
    return GetPointer<const ::flatbuffers::Vector<int8_t> *>(VT_SOURCE);
  }
  ::flatbuffers::Vector<int8_t> *mutable_source() {
    return GetPointer<::flatbuffers::Vector<int8_t> *>(VT_SOURCE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyVector(source()) &&
           verifier.EndTable();
  }
};

struct OptimizeMeshBufferBuilder {
  typedef OptimizeMeshBuffer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(OptimizeMeshBuffer::VT_NAME, name);
  }
  void add_source(::flatbuffers::Offset<::flatbuffers::Vector<int8_t>> source) {
    fbb_.AddOffset(OptimizeMeshBuffer::VT_SOURCE, source);
  }
  explicit OptimizeMeshBufferBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OptimizeMeshBuffer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OptimizeMeshBuffer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OptimizeMeshBuffer> CreateOptimizeMeshBuffer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int8_t>> source = 0) {
  OptimizeMeshBufferBuilder builder_(_fbb);
  builder_.add_source(source);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<OptimizeMeshBuffer> CreateOptimizeMeshBufferDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<int8_t> *source = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto source__ = source ? _fbb.CreateVector<int8_t>(*source) : 0;
  return slug::fbs::srtf::CreateOptimizeMeshBuffer(
      _fbb,
      name__,
      source__);
}

struct OptimizeMesh FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OptimizeMeshBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return OptimizeMeshTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTEX_ACCESSORS = 4,
    VT_INDEX_ACCESSOR = 6,
    VT_VERTEX_COUNT = 8,
    VT_VERTEX_BYTE_SIZE = 10,
    VT_INDEX_COUNT = 12,
    VT_INDEX_BYTE_SIZE = 14,
    VT_MATERIAL = 16,
    VT_NODE = 18
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::VertexAccessor>> *vertex_accessors() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::VertexAccessor>> *>(VT_VERTEX_ACCESSORS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::VertexAccessor>> *mutable_vertex_accessors() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::VertexAccessor>> *>(VT_VERTEX_ACCESSORS);
  }
  const slug::fbs::srtf::indexAccessor *index_accessor() const {
    return GetPointer<const slug::fbs::srtf::indexAccessor *>(VT_INDEX_ACCESSOR);
  }
  slug::fbs::srtf::indexAccessor *mutable_index_accessor() {
    return GetPointer<slug::fbs::srtf::indexAccessor *>(VT_INDEX_ACCESSOR);
  }
  uint32_t vertex_count() const {
    return GetField<uint32_t>(VT_VERTEX_COUNT, 0);
  }
  bool mutate_vertex_count(uint32_t _vertex_count = 0) {
    return SetField<uint32_t>(VT_VERTEX_COUNT, _vertex_count, 0);
  }
  uint32_t vertex_byte_size() const {
    return GetField<uint32_t>(VT_VERTEX_BYTE_SIZE, 0);
  }
  bool mutate_vertex_byte_size(uint32_t _vertex_byte_size = 0) {
    return SetField<uint32_t>(VT_VERTEX_BYTE_SIZE, _vertex_byte_size, 0);
  }
  uint32_t index_count() const {
    return GetField<uint32_t>(VT_INDEX_COUNT, 0);
  }
  bool mutate_index_count(uint32_t _index_count = 0) {
    return SetField<uint32_t>(VT_INDEX_COUNT, _index_count, 0);
  }
  uint32_t index_byte_size() const {
    return GetField<uint32_t>(VT_INDEX_BYTE_SIZE, 0);
  }
  bool mutate_index_byte_size(uint32_t _index_byte_size = 0) {
    return SetField<uint32_t>(VT_INDEX_BYTE_SIZE, _index_byte_size, 0);
  }
  uint32_t material() const {
    return GetField<uint32_t>(VT_MATERIAL, 0);
  }
  bool mutate_material(uint32_t _material = 0) {
    return SetField<uint32_t>(VT_MATERIAL, _material, 0);
  }
  uint32_t node() const {
    return GetField<uint32_t>(VT_NODE, 0);
  }
  bool mutate_node(uint32_t _node = 0) {
    return SetField<uint32_t>(VT_NODE, _node, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTEX_ACCESSORS) &&
           verifier.VerifyVector(vertex_accessors()) &&
           verifier.VerifyVectorOfTables(vertex_accessors()) &&
           VerifyOffset(verifier, VT_INDEX_ACCESSOR) &&
           verifier.VerifyTable(index_accessor()) &&
           VerifyField<uint32_t>(verifier, VT_VERTEX_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_VERTEX_BYTE_SIZE, 4) &&
           VerifyField<uint32_t>(verifier, VT_INDEX_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_INDEX_BYTE_SIZE, 4) &&
           VerifyField<uint32_t>(verifier, VT_MATERIAL, 4) &&
           VerifyField<uint32_t>(verifier, VT_NODE, 4) &&
           verifier.EndTable();
  }
};

struct OptimizeMeshBuilder {
  typedef OptimizeMesh Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertex_accessors(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::VertexAccessor>>> vertex_accessors) {
    fbb_.AddOffset(OptimizeMesh::VT_VERTEX_ACCESSORS, vertex_accessors);
  }
  void add_index_accessor(::flatbuffers::Offset<slug::fbs::srtf::indexAccessor> index_accessor) {
    fbb_.AddOffset(OptimizeMesh::VT_INDEX_ACCESSOR, index_accessor);
  }
  void add_vertex_count(uint32_t vertex_count) {
    fbb_.AddElement<uint32_t>(OptimizeMesh::VT_VERTEX_COUNT, vertex_count, 0);
  }
  void add_vertex_byte_size(uint32_t vertex_byte_size) {
    fbb_.AddElement<uint32_t>(OptimizeMesh::VT_VERTEX_BYTE_SIZE, vertex_byte_size, 0);
  }
  void add_index_count(uint32_t index_count) {
    fbb_.AddElement<uint32_t>(OptimizeMesh::VT_INDEX_COUNT, index_count, 0);
  }
  void add_index_byte_size(uint32_t index_byte_size) {
    fbb_.AddElement<uint32_t>(OptimizeMesh::VT_INDEX_BYTE_SIZE, index_byte_size, 0);
  }
  void add_material(uint32_t material) {
    fbb_.AddElement<uint32_t>(OptimizeMesh::VT_MATERIAL, material, 0);
  }
  void add_node(uint32_t node) {
    fbb_.AddElement<uint32_t>(OptimizeMesh::VT_NODE, node, 0);
  }
  explicit OptimizeMeshBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OptimizeMesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OptimizeMesh>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OptimizeMesh> CreateOptimizeMesh(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::VertexAccessor>>> vertex_accessors = 0,
    ::flatbuffers::Offset<slug::fbs::srtf::indexAccessor> index_accessor = 0,
    uint32_t vertex_count = 0,
    uint32_t vertex_byte_size = 0,
    uint32_t index_count = 0,
    uint32_t index_byte_size = 0,
    uint32_t material = 0,
    uint32_t node = 0) {
  OptimizeMeshBuilder builder_(_fbb);
  builder_.add_node(node);
  builder_.add_material(material);
  builder_.add_index_byte_size(index_byte_size);
  builder_.add_index_count(index_count);
  builder_.add_vertex_byte_size(vertex_byte_size);
  builder_.add_vertex_count(vertex_count);
  builder_.add_index_accessor(index_accessor);
  builder_.add_vertex_accessors(vertex_accessors);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<OptimizeMesh> CreateOptimizeMeshDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::VertexAccessor>> *vertex_accessors = nullptr,
    ::flatbuffers::Offset<slug::fbs::srtf::indexAccessor> index_accessor = 0,
    uint32_t vertex_count = 0,
    uint32_t vertex_byte_size = 0,
    uint32_t index_count = 0,
    uint32_t index_byte_size = 0,
    uint32_t material = 0,
    uint32_t node = 0) {
  auto vertex_accessors__ = vertex_accessors ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::VertexAccessor>>(*vertex_accessors) : 0;
  return slug::fbs::srtf::CreateOptimizeMesh(
      _fbb,
      vertex_accessors__,
      index_accessor,
      vertex_count,
      vertex_byte_size,
      index_count,
      index_byte_size,
      material,
      node);
}

struct Mesh FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return MeshTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTICES = 4,
    VT_INDICES = 6,
    VT_MATERIAL = 8,
    VT_NODE = 10,
    VT_AABB = 12
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vertex>> *vertices() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vertex>> *>(VT_VERTICES);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vertex>> *mutable_vertices() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vertex>> *>(VT_VERTICES);
  }
  const ::flatbuffers::Vector<uint32_t> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDICES);
  }
  ::flatbuffers::Vector<uint32_t> *mutable_indices() {
    return GetPointer<::flatbuffers::Vector<uint32_t> *>(VT_INDICES);
  }
  uint32_t material() const {
    return GetField<uint32_t>(VT_MATERIAL, 0);
  }
  bool mutate_material(uint32_t _material = 0) {
    return SetField<uint32_t>(VT_MATERIAL, _material, 0);
  }
  uint32_t node() const {
    return GetField<uint32_t>(VT_NODE, 0);
  }
  bool mutate_node(uint32_t _node = 0) {
    return SetField<uint32_t>(VT_NODE, _node, 0);
  }
  const slug::fbs::srtf::AABB *aabb() const {
    return GetStruct<const slug::fbs::srtf::AABB *>(VT_AABB);
  }
  slug::fbs::srtf::AABB *mutable_aabb() {
    return GetStruct<slug::fbs::srtf::AABB *>(VT_AABB);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           verifier.VerifyVectorOfTables(vertices()) &&
           VerifyOffset(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           VerifyField<uint32_t>(verifier, VT_MATERIAL, 4) &&
           VerifyField<uint32_t>(verifier, VT_NODE, 4) &&
           VerifyField<slug::fbs::srtf::AABB>(verifier, VT_AABB, 4) &&
           verifier.EndTable();
  }
};

struct MeshBuilder {
  typedef Mesh Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertices(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vertex>>> vertices) {
    fbb_.AddOffset(Mesh::VT_VERTICES, vertices);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices) {
    fbb_.AddOffset(Mesh::VT_INDICES, indices);
  }
  void add_material(uint32_t material) {
    fbb_.AddElement<uint32_t>(Mesh::VT_MATERIAL, material, 0);
  }
  void add_node(uint32_t node) {
    fbb_.AddElement<uint32_t>(Mesh::VT_NODE, node, 0);
  }
  void add_aabb(const slug::fbs::srtf::AABB *aabb) {
    fbb_.AddStruct(Mesh::VT_AABB, aabb);
  }
  explicit MeshBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Mesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Mesh>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Mesh> CreateMesh(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vertex>>> vertices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices = 0,
    uint32_t material = 0,
    uint32_t node = 0,
    const slug::fbs::srtf::AABB *aabb = nullptr) {
  MeshBuilder builder_(_fbb);
  builder_.add_aabb(aabb);
  builder_.add_node(node);
  builder_.add_material(material);
  builder_.add_indices(indices);
  builder_.add_vertices(vertices);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Mesh> CreateMeshDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::Vertex>> *vertices = nullptr,
    const std::vector<uint32_t> *indices = nullptr,
    uint32_t material = 0,
    uint32_t node = 0,
    const slug::fbs::srtf::AABB *aabb = nullptr) {
  auto vertices__ = vertices ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::Vertex>>(*vertices) : 0;
  auto indices__ = indices ? _fbb.CreateVector<uint32_t>(*indices) : 0;
  return slug::fbs::srtf::CreateMesh(
      _fbb,
      vertices__,
      indices__,
      material,
      node,
      aabb);
}

struct SubModel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SubModelBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SubModelTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_USE_OPTIMIZE_MESH = 6,
    VT_MESHES = 8,
    VT_OPTIMIZE_MESHES = 10,
    VT_BUFFER = 12,
    VT_NODES = 14,
    VT_MATERIALS = 16,
    VT_TOPOLOGY = 18
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  bool use_optimize_mesh() const {
    return GetField<uint8_t>(VT_USE_OPTIMIZE_MESH, 0) != 0;
  }
  bool mutate_use_optimize_mesh(bool _use_optimize_mesh = 0) {
    return SetField<uint8_t>(VT_USE_OPTIMIZE_MESH, static_cast<uint8_t>(_use_optimize_mesh), 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Mesh>> *meshes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Mesh>> *>(VT_MESHES);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Mesh>> *mutable_meshes() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Mesh>> *>(VT_MESHES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::OptimizeMesh>> *optimize_meshes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::OptimizeMesh>> *>(VT_OPTIMIZE_MESHES);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::OptimizeMesh>> *mutable_optimize_meshes() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::OptimizeMesh>> *>(VT_OPTIMIZE_MESHES);
  }
  const slug::fbs::srtf::OptimizeMeshBuffer *buffer() const {
    return GetPointer<const slug::fbs::srtf::OptimizeMeshBuffer *>(VT_BUFFER);
  }
  slug::fbs::srtf::OptimizeMeshBuffer *mutable_buffer() {
    return GetPointer<slug::fbs::srtf::OptimizeMeshBuffer *>(VT_BUFFER);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Node>> *nodes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Node>> *>(VT_NODES);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Node>> *mutable_nodes() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Node>> *>(VT_NODES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::MaterialSlot>> *materials() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::MaterialSlot>> *>(VT_MATERIALS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::MaterialSlot>> *mutable_materials() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::MaterialSlot>> *>(VT_MATERIALS);
  }
  slug::fbs::srtf::TopologyType topology() const {
    return static_cast<slug::fbs::srtf::TopologyType>(GetField<int16_t>(VT_TOPOLOGY, 0));
  }
  bool mutate_topology(slug::fbs::srtf::TopologyType _topology = static_cast<slug::fbs::srtf::TopologyType>(0)) {
    return SetField<int16_t>(VT_TOPOLOGY, static_cast<int16_t>(_topology), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_USE_OPTIMIZE_MESH, 1) &&
           VerifyOffset(verifier, VT_MESHES) &&
           verifier.VerifyVector(meshes()) &&
           verifier.VerifyVectorOfTables(meshes()) &&
           VerifyOffset(verifier, VT_OPTIMIZE_MESHES) &&
           verifier.VerifyVector(optimize_meshes()) &&
           verifier.VerifyVectorOfTables(optimize_meshes()) &&
           VerifyOffset(verifier, VT_BUFFER) &&
           verifier.VerifyTable(buffer()) &&
           VerifyOffset(verifier, VT_NODES) &&
           verifier.VerifyVector(nodes()) &&
           verifier.VerifyVectorOfTables(nodes()) &&
           VerifyOffset(verifier, VT_MATERIALS) &&
           verifier.VerifyVector(materials()) &&
           verifier.VerifyVectorOfTables(materials()) &&
           VerifyField<int16_t>(verifier, VT_TOPOLOGY, 2) &&
           verifier.EndTable();
  }
};

struct SubModelBuilder {
  typedef SubModel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SubModel::VT_NAME, name);
  }
  void add_use_optimize_mesh(bool use_optimize_mesh) {
    fbb_.AddElement<uint8_t>(SubModel::VT_USE_OPTIMIZE_MESH, static_cast<uint8_t>(use_optimize_mesh), 0);
  }
  void add_meshes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Mesh>>> meshes) {
    fbb_.AddOffset(SubModel::VT_MESHES, meshes);
  }
  void add_optimize_meshes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::OptimizeMesh>>> optimize_meshes) {
    fbb_.AddOffset(SubModel::VT_OPTIMIZE_MESHES, optimize_meshes);
  }
  void add_buffer(::flatbuffers::Offset<slug::fbs::srtf::OptimizeMeshBuffer> buffer) {
    fbb_.AddOffset(SubModel::VT_BUFFER, buffer);
  }
  void add_nodes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Node>>> nodes) {
    fbb_.AddOffset(SubModel::VT_NODES, nodes);
  }
  void add_materials(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::MaterialSlot>>> materials) {
    fbb_.AddOffset(SubModel::VT_MATERIALS, materials);
  }
  void add_topology(slug::fbs::srtf::TopologyType topology) {
    fbb_.AddElement<int16_t>(SubModel::VT_TOPOLOGY, static_cast<int16_t>(topology), 0);
  }
  explicit SubModelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SubModel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SubModel>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SubModel> CreateSubModel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    bool use_optimize_mesh = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Mesh>>> meshes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::OptimizeMesh>>> optimize_meshes = 0,
    ::flatbuffers::Offset<slug::fbs::srtf::OptimizeMeshBuffer> buffer = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Node>>> nodes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::MaterialSlot>>> materials = 0,
    slug::fbs::srtf::TopologyType topology = slug::fbs::srtf::TopologyType_PointList) {
  SubModelBuilder builder_(_fbb);
  builder_.add_materials(materials);
  builder_.add_nodes(nodes);
  builder_.add_buffer(buffer);
  builder_.add_optimize_meshes(optimize_meshes);
  builder_.add_meshes(meshes);
  builder_.add_name(name);
  builder_.add_topology(topology);
  builder_.add_use_optimize_mesh(use_optimize_mesh);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SubModel> CreateSubModelDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    bool use_optimize_mesh = false,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::Mesh>> *meshes = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::OptimizeMesh>> *optimize_meshes = nullptr,
    ::flatbuffers::Offset<slug::fbs::srtf::OptimizeMeshBuffer> buffer = 0,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::Node>> *nodes = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::MaterialSlot>> *materials = nullptr,
    slug::fbs::srtf::TopologyType topology = slug::fbs::srtf::TopologyType_PointList) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto meshes__ = meshes ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::Mesh>>(*meshes) : 0;
  auto optimize_meshes__ = optimize_meshes ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::OptimizeMesh>>(*optimize_meshes) : 0;
  auto nodes__ = nodes ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::Node>>(*nodes) : 0;
  auto materials__ = materials ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::MaterialSlot>>(*materials) : 0;
  return slug::fbs::srtf::CreateSubModel(
      _fbb,
      name__,
      use_optimize_mesh,
      meshes__,
      optimize_meshes__,
      buffer,
      nodes__,
      materials__,
      topology);
}

struct LodSettings FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LodSettingsBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return LodSettingsTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OFFSET_LOD_INDEX = 4,
    VT_ITEMS = 6
  };
  int32_t offset_lod_index() const {
    return GetField<int32_t>(VT_OFFSET_LOD_INDEX, 0);
  }
  bool mutate_offset_lod_index(int32_t _offset_lod_index = 0) {
    return SetField<int32_t>(VT_OFFSET_LOD_INDEX, _offset_lod_index, 0);
  }
  const ::flatbuffers::Vector<const slug::fbs::srtf::LodItemSettings *> *items() const {
    return GetPointer<const ::flatbuffers::Vector<const slug::fbs::srtf::LodItemSettings *> *>(VT_ITEMS);
  }
  ::flatbuffers::Vector<const slug::fbs::srtf::LodItemSettings *> *mutable_items() {
    return GetPointer<::flatbuffers::Vector<const slug::fbs::srtf::LodItemSettings *> *>(VT_ITEMS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_OFFSET_LOD_INDEX, 4) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.EndTable();
  }
};

struct LodSettingsBuilder {
  typedef LodSettings Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_offset_lod_index(int32_t offset_lod_index) {
    fbb_.AddElement<int32_t>(LodSettings::VT_OFFSET_LOD_INDEX, offset_lod_index, 0);
  }
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::LodItemSettings *>> items) {
    fbb_.AddOffset(LodSettings::VT_ITEMS, items);
  }
  explicit LodSettingsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LodSettings> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LodSettings>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LodSettings> CreateLodSettings(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t offset_lod_index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slug::fbs::srtf::LodItemSettings *>> items = 0) {
  LodSettingsBuilder builder_(_fbb);
  builder_.add_items(items);
  builder_.add_offset_lod_index(offset_lod_index);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LodSettings> CreateLodSettingsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t offset_lod_index = 0,
    const std::vector<slug::fbs::srtf::LodItemSettings> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVectorOfStructs<slug::fbs::srtf::LodItemSettings>(*items) : 0;
  return slug::fbs::srtf::CreateLodSettings(
      _fbb,
      offset_lod_index,
      items__);
}

struct LodModel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LodModelBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return LodModelTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LOD_SETTINGS = 4,
    VT_SUB_MODELS = 6
  };
  const slug::fbs::srtf::LodSettings *lod_settings() const {
    return GetPointer<const slug::fbs::srtf::LodSettings *>(VT_LOD_SETTINGS);
  }
  slug::fbs::srtf::LodSettings *mutable_lod_settings() {
    return GetPointer<slug::fbs::srtf::LodSettings *>(VT_LOD_SETTINGS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::SubModel>> *sub_models() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::SubModel>> *>(VT_SUB_MODELS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::SubModel>> *mutable_sub_models() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::SubModel>> *>(VT_SUB_MODELS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LOD_SETTINGS) &&
           verifier.VerifyTable(lod_settings()) &&
           VerifyOffset(verifier, VT_SUB_MODELS) &&
           verifier.VerifyVector(sub_models()) &&
           verifier.VerifyVectorOfTables(sub_models()) &&
           verifier.EndTable();
  }
};

struct LodModelBuilder {
  typedef LodModel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_lod_settings(::flatbuffers::Offset<slug::fbs::srtf::LodSettings> lod_settings) {
    fbb_.AddOffset(LodModel::VT_LOD_SETTINGS, lod_settings);
  }
  void add_sub_models(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::SubModel>>> sub_models) {
    fbb_.AddOffset(LodModel::VT_SUB_MODELS, sub_models);
  }
  explicit LodModelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LodModel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LodModel>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LodModel> CreateLodModel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::LodSettings> lod_settings = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::SubModel>>> sub_models = 0) {
  LodModelBuilder builder_(_fbb);
  builder_.add_sub_models(sub_models);
  builder_.add_lod_settings(lod_settings);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LodModel> CreateLodModelDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::LodSettings> lod_settings = 0,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::SubModel>> *sub_models = nullptr) {
  auto sub_models__ = sub_models ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::SubModel>>(*sub_models) : 0;
  return slug::fbs::srtf::CreateLodModel(
      _fbb,
      lod_settings,
      sub_models__);
}

struct Model FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ModelTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAIN_MODEL = 4,
    VT_LOD_MODEL = 6
  };
  const slug::fbs::srtf::SubModel *main_model() const {
    return GetPointer<const slug::fbs::srtf::SubModel *>(VT_MAIN_MODEL);
  }
  slug::fbs::srtf::SubModel *mutable_main_model() {
    return GetPointer<slug::fbs::srtf::SubModel *>(VT_MAIN_MODEL);
  }
  const slug::fbs::srtf::LodModel *lod_model() const {
    return GetPointer<const slug::fbs::srtf::LodModel *>(VT_LOD_MODEL);
  }
  slug::fbs::srtf::LodModel *mutable_lod_model() {
    return GetPointer<slug::fbs::srtf::LodModel *>(VT_LOD_MODEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MAIN_MODEL) &&
           verifier.VerifyTable(main_model()) &&
           VerifyOffset(verifier, VT_LOD_MODEL) &&
           verifier.VerifyTable(lod_model()) &&
           verifier.EndTable();
  }
};

struct ModelBuilder {
  typedef Model Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_main_model(::flatbuffers::Offset<slug::fbs::srtf::SubModel> main_model) {
    fbb_.AddOffset(Model::VT_MAIN_MODEL, main_model);
  }
  void add_lod_model(::flatbuffers::Offset<slug::fbs::srtf::LodModel> lod_model) {
    fbb_.AddOffset(Model::VT_LOD_MODEL, lod_model);
  }
  explicit ModelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Model> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Model>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Model> CreateModel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::SubModel> main_model = 0,
    ::flatbuffers::Offset<slug::fbs::srtf::LodModel> lod_model = 0) {
  ModelBuilder builder_(_fbb);
  builder_.add_lod_model(lod_model);
  builder_.add_main_model(main_model);
  return builder_.Finish();
}

inline const ::flatbuffers::TypeTable *TopologyTypeTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::TopologyTypeTypeTable
  };
  static const char * const names[] = {
    "PointList",
    "LineList",
    "LineStrip",
    "TriangleList",
    "TriangleStrip",
    "QuadList",
    "QuadStrip"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_ENUM, 7, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *SemanticTypeTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::SemanticTypeTypeTable
  };
  static const char * const names[] = {
    "Position",
    "Normal",
    "Texcoord",
    "Tangent",
    "Binormal",
    "Color",
    "BoneIndex",
    "BoneWeight"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_ENUM, 8, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *VertexFormatTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::VertexFormatTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "BYTE1",
    "BYTE2",
    "BYTE3",
    "BYTE4",
    "BYTE4N",
    "UBYTE1",
    "UBYTE2",
    "UBYTE3",
    "UBYTE4",
    "UBYTE8",
    "UBYTE4N",
    "SHORT1",
    "SHORT2",
    "SHORT2N",
    "SHORT3",
    "SHORT4",
    "SHORT4N",
    "USHORT1",
    "USHORT2",
    "USHORT2N",
    "USHORT3",
    "USHORT4",
    "USHORT4N",
    "USHORT8",
    "INT1",
    "INT2",
    "INT3",
    "INT4",
    "UINT1",
    "UINT2",
    "UINT3",
    "UINT4",
    "FLOAT1",
    "FLOAT2",
    "FLOAT3",
    "FLOAT4",
    "R11G11B10Float",
    "R10G10B10A2Unorm"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_ENUM, 39, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *UVLayerTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 1, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Vector3TypeTable
  };
  static const int16_t array_sizes[] = { 64,  };
  static const int64_t values[] = { 0, 64, 76 };
  static const char * const names[] = {
    "name",
    "uv"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 2, type_codes, type_refs, array_sizes, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *TangentLayerTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 1, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Vector3TypeTable
  };
  static const int16_t array_sizes[] = { 64,  };
  static const int64_t values[] = { 0, 64, 76 };
  static const char * const names[] = {
    "name",
    "tangent"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 2, type_codes, type_refs, array_sizes, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *BinormalLayerTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 1, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Vector3TypeTable
  };
  static const int16_t array_sizes[] = { 64,  };
  static const int64_t values[] = { 0, 64, 76 };
  static const char * const names[] = {
    "name",
    "binormal"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 2, type_codes, type_refs, array_sizes, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ColorLayerTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 1, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Vector4TypeTable
  };
  static const int16_t array_sizes[] = { 64,  };
  static const int64_t values[] = { 0, 64, 80 };
  static const char * const names[] = {
    "name",
    "color"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 2, type_codes, type_refs, array_sizes, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *BoneLayerTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 1, -1 },
    { ::flatbuffers::ET_INT, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 0, -1 }
  };
  static const int16_t array_sizes[] = { 64,  };
  static const int64_t values[] = { 0, 64, 68, 72 };
  static const char * const names[] = {
    "name",
    "id",
    "weight"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 3, type_codes, nullptr, array_sizes, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *VertexTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 1, 1 },
    { ::flatbuffers::ET_SEQUENCE, 1, 2 },
    { ::flatbuffers::ET_SEQUENCE, 1, 3 },
    { ::flatbuffers::ET_SEQUENCE, 1, 4 },
    { ::flatbuffers::ET_SEQUENCE, 1, 5 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Vector3TypeTable,
    slug::fbs::srtf::UVLayerTypeTable,
    slug::fbs::srtf::TangentLayerTypeTable,
    slug::fbs::srtf::BinormalLayerTypeTable,
    slug::fbs::srtf::ColorLayerTypeTable,
    slug::fbs::srtf::BoneLayerTypeTable
  };
  static const char * const names[] = {
    "position",
    "normal",
    "uvs",
    "tangents",
    "binormals",
    "colors",
    "bones"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 7, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *NodeTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_INT, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Matrix4x4TypeTable
  };
  static const char * const names[] = {
    "name",
    "parent",
    "bindpose"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *MaterialSlotTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const char * const names[] = {
    "slot",
    "material"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *VertexAccessorTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_SHORT, 0, 1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::SemanticTypeTypeTable,
    slug::fbs::srtf::VertexFormatTypeTable
  };
  static const char * const names[] = {
    "semantic_type",
    "semantic_index",
    "foramt",
    "offset",
    "size"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 5, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *indexAccessorTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SHORT, 0, 0 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::VertexFormatTypeTable
  };
  static const char * const names[] = {
    "foramt",
    "offset",
    "size"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *OptimizeMeshBufferTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_CHAR, 1, -1 }
  };
  static const char * const names[] = {
    "name",
    "source"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *OptimizeMeshTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 1, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::VertexAccessorTypeTable,
    slug::fbs::srtf::indexAccessorTypeTable
  };
  static const char * const names[] = {
    "vertex_accessors",
    "index_accessor",
    "vertex_count",
    "vertex_byte_size",
    "index_count",
    "index_byte_size",
    "material",
    "node"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 8, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *MeshTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 1, 0 },
    { ::flatbuffers::ET_UINT, 1, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::VertexTypeTable,
    slug::fbs::srtf::AABBTypeTable
  };
  static const char * const names[] = {
    "vertices",
    "indices",
    "material",
    "node",
    "aabb"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 5, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *SubModelTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 1, 0 },
    { ::flatbuffers::ET_SEQUENCE, 1, 1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 2 },
    { ::flatbuffers::ET_SEQUENCE, 1, 3 },
    { ::flatbuffers::ET_SEQUENCE, 1, 4 },
    { ::flatbuffers::ET_SHORT, 0, 5 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::MeshTypeTable,
    slug::fbs::srtf::OptimizeMeshTypeTable,
    slug::fbs::srtf::OptimizeMeshBufferTypeTable,
    slug::fbs::srtf::NodeTypeTable,
    slug::fbs::srtf::MaterialSlotTypeTable,
    slug::fbs::srtf::TopologyTypeTypeTable
  };
  static const char * const names[] = {
    "name",
    "use_optimize_mesh",
    "meshes",
    "optimize_meshes",
    "buffer",
    "nodes",
    "materials",
    "topology"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 8, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *LodItemSettingsTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_FLOAT, 0, -1 }
  };
  static const int64_t values[] = { 0, 4 };
  static const char * const names[] = {
    "draw_pixel_area_ratio"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 1, type_codes, nullptr, nullptr, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *LodSettingsTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_INT, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 1, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::LodItemSettingsTypeTable
  };
  static const char * const names[] = {
    "offset_lod_index",
    "items"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *LodModelTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 1, 1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::LodSettingsTypeTable,
    slug::fbs::srtf::SubModelTypeTable
  };
  static const char * const names[] = {
    "lod_settings",
    "sub_models"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ModelTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::SubModelTypeTable,
    slug::fbs::srtf::LodModelTypeTable
  };
  static const char * const names[] = {
    "main_model",
    "lod_model"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const slug::fbs::srtf::Model *GetModel(const void *buf) {
  return ::flatbuffers::GetRoot<slug::fbs::srtf::Model>(buf);
}

inline const slug::fbs::srtf::Model *GetSizePrefixedModel(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<slug::fbs::srtf::Model>(buf);
}

inline Model *GetMutableModel(void *buf) {
  return ::flatbuffers::GetMutableRoot<Model>(buf);
}

inline slug::fbs::srtf::Model *GetMutableSizePrefixedModel(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<slug::fbs::srtf::Model>(buf);
}

inline const char *ModelIdentifier() {
  return "MODL";
}

inline bool ModelBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ModelIdentifier());
}

inline bool SizePrefixedModelBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ModelIdentifier(), true);
}

inline bool VerifyModelBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<slug::fbs::srtf::Model>(ModelIdentifier());
}

inline bool VerifySizePrefixedModelBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<slug::fbs::srtf::Model>(ModelIdentifier());
}

inline void FinishModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::Model> root) {
  fbb.Finish(root, ModelIdentifier());
}

inline void FinishSizePrefixedModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::Model> root) {
  fbb.FinishSizePrefixed(root, ModelIdentifier());
}

}  // namespace srtf
}  // namespace fbs
}  // namespace slug

#endif  // FLATBUFFERS_GENERATED_MODEL_SLUG_FBS_SRTF_H_
