// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SHADER_SLUG_FBS_SRTF_H_
#define FLATBUFFERS_GENERATED_SHADER_SLUG_FBS_SRTF_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "common_fbs.h"

namespace slug {
namespace fbs {
namespace srtf {

struct GiSettings;

struct ShadingModel;
struct ShadingModelBuilder;

struct ShaderItem;
struct ShaderItemBuilder;

struct TextureParameter;
struct TextureParameterBuilder;

struct ConstantBufferLayout;
struct ConstantBufferLayoutBuilder;

struct ConstantParameter;
struct ConstantParameterBuilder;

struct DrawSettings;
struct DrawSettingsBuilder;

struct Shader;
struct ShaderBuilder;

inline const ::flatbuffers::TypeTable *GiSettingsTypeTable();

inline const ::flatbuffers::TypeTable *ShadingModelTypeTable();

inline const ::flatbuffers::TypeTable *ShaderItemTypeTable();

inline const ::flatbuffers::TypeTable *TextureParameterTypeTable();

inline const ::flatbuffers::TypeTable *ConstantBufferLayoutTypeTable();

inline const ::flatbuffers::TypeTable *ConstantParameterTypeTable();

inline const ::flatbuffers::TypeTable *DrawSettingsTypeTable();

inline const ::flatbuffers::TypeTable *ShaderTypeTable();

enum BlendOptions : uint8_t {
  BlendOptions_Opaque = 0,
  BlendOptions_Mask = 1,
  BlendOptions_Transparent = 2,
  BlendOptions_Addtive = 3,
  BlendOptions_Modulate = 4,
  BlendOptions_MIN = BlendOptions_Opaque,
  BlendOptions_MAX = BlendOptions_Modulate
};

inline const BlendOptions (&EnumValuesBlendOptions())[5] {
  static const BlendOptions values[] = {
    BlendOptions_Opaque,
    BlendOptions_Mask,
    BlendOptions_Transparent,
    BlendOptions_Addtive,
    BlendOptions_Modulate
  };
  return values;
}

inline const char * const *EnumNamesBlendOptions() {
  static const char * const names[6] = {
    "Opaque",
    "Mask",
    "Transparent",
    "Addtive",
    "Modulate",
    nullptr
  };
  return names;
}

inline const char *EnumNameBlendOptions(BlendOptions e) {
  if (::flatbuffers::IsOutRange(e, BlendOptions_Opaque, BlendOptions_Modulate)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBlendOptions()[index];
}

enum ConstantParameterType : uint8_t {
  ConstantParameterType_Bool = 0,
  ConstantParameterType_Float = 1,
  ConstantParameterType_FloatArray = 2,
  ConstantParameterType_Vector2 = 3,
  ConstantParameterType_Vector3 = 4,
  ConstantParameterType_Vector4 = 5,
  ConstantParameterType_Matrix3x3 = 6,
  ConstantParameterType_Matrix4x4 = 7,
  ConstantParameterType_MIN = ConstantParameterType_Bool,
  ConstantParameterType_MAX = ConstantParameterType_Matrix4x4
};

inline const ConstantParameterType (&EnumValuesConstantParameterType())[8] {
  static const ConstantParameterType values[] = {
    ConstantParameterType_Bool,
    ConstantParameterType_Float,
    ConstantParameterType_FloatArray,
    ConstantParameterType_Vector2,
    ConstantParameterType_Vector3,
    ConstantParameterType_Vector4,
    ConstantParameterType_Matrix3x3,
    ConstantParameterType_Matrix4x4
  };
  return values;
}

inline const char * const *EnumNamesConstantParameterType() {
  static const char * const names[9] = {
    "Bool",
    "Float",
    "FloatArray",
    "Vector2",
    "Vector3",
    "Vector4",
    "Matrix3x3",
    "Matrix4x4",
    nullptr
  };
  return names;
}

inline const char *EnumNameConstantParameterType(ConstantParameterType e) {
  if (::flatbuffers::IsOutRange(e, ConstantParameterType_Bool, ConstantParameterType_Matrix4x4)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesConstantParameterType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) GiSettings FLATBUFFERS_FINAL_CLASS {
 private:
  float diffuse_boost_;
  float emissive_boost_;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return GiSettingsTypeTable();
  }
  GiSettings()
      : diffuse_boost_(0),
        emissive_boost_(0) {
  }
  GiSettings(float _diffuse_boost, float _emissive_boost)
      : diffuse_boost_(::flatbuffers::EndianScalar(_diffuse_boost)),
        emissive_boost_(::flatbuffers::EndianScalar(_emissive_boost)) {
  }
  float diffuse_boost() const {
    return ::flatbuffers::EndianScalar(diffuse_boost_);
  }
  void mutate_diffuse_boost(float _diffuse_boost) {
    ::flatbuffers::WriteScalar(&diffuse_boost_, _diffuse_boost);
  }
  float emissive_boost() const {
    return ::flatbuffers::EndianScalar(emissive_boost_);
  }
  void mutate_emissive_boost(float _emissive_boost) {
    ::flatbuffers::WriteScalar(&emissive_boost_, _emissive_boost);
  }
};
FLATBUFFERS_STRUCT_END(GiSettings, 8);

struct ShadingModel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ShadingModelBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ShadingModelTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_ID = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool mutate_id(uint32_t _id = 0) {
    return SetField<uint32_t>(VT_ID, _id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct ShadingModelBuilder {
  typedef ShadingModel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(ShadingModel::VT_NAME, name);
  }
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(ShadingModel::VT_ID, id, 0);
  }
  explicit ShadingModelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ShadingModel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ShadingModel>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ShadingModel> CreateShadingModel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t id = 0) {
  ShadingModelBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ShadingModel> CreateShadingModelDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    uint32_t id = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return slug::fbs::srtf::CreateShadingModel(
      _fbb,
      name__,
      id);
}

struct ShaderItem FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ShaderItemBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ShaderItemTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_CODE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<uint8_t> *code() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CODE);
  }
  ::flatbuffers::Vector<uint8_t> *mutable_code() {
    return GetPointer<::flatbuffers::Vector<uint8_t> *>(VT_CODE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_CODE) &&
           verifier.VerifyVector(code()) &&
           verifier.EndTable();
  }
};

struct ShaderItemBuilder {
  typedef ShaderItem Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(ShaderItem::VT_NAME, name);
  }
  void add_code(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> code) {
    fbb_.AddOffset(ShaderItem::VT_CODE, code);
  }
  explicit ShaderItemBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ShaderItem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ShaderItem>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ShaderItem> CreateShaderItem(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> code = 0) {
  ShaderItemBuilder builder_(_fbb);
  builder_.add_code(code);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ShaderItem> CreateShaderItemDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<uint8_t> *code = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto code__ = code ? _fbb.CreateVector<uint8_t>(*code) : 0;
  return slug::fbs::srtf::CreateShaderItem(
      _fbb,
      name__,
      code__);
}

struct TextureParameter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TextureParameterBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return TextureParameterTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SLOT_NAME = 4,
    VT_TEXTURE = 6
  };
  const ::flatbuffers::String *slot_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SLOT_NAME);
  }
  ::flatbuffers::String *mutable_slot_name() {
    return GetPointer<::flatbuffers::String *>(VT_SLOT_NAME);
  }
  const ::flatbuffers::String *texture() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXTURE);
  }
  ::flatbuffers::String *mutable_texture() {
    return GetPointer<::flatbuffers::String *>(VT_TEXTURE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SLOT_NAME) &&
           verifier.VerifyString(slot_name()) &&
           VerifyOffset(verifier, VT_TEXTURE) &&
           verifier.VerifyString(texture()) &&
           verifier.EndTable();
  }
};

struct TextureParameterBuilder {
  typedef TextureParameter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_slot_name(::flatbuffers::Offset<::flatbuffers::String> slot_name) {
    fbb_.AddOffset(TextureParameter::VT_SLOT_NAME, slot_name);
  }
  void add_texture(::flatbuffers::Offset<::flatbuffers::String> texture) {
    fbb_.AddOffset(TextureParameter::VT_TEXTURE, texture);
  }
  explicit TextureParameterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TextureParameter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TextureParameter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TextureParameter> CreateTextureParameter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> slot_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> texture = 0) {
  TextureParameterBuilder builder_(_fbb);
  builder_.add_texture(texture);
  builder_.add_slot_name(slot_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TextureParameter> CreateTextureParameterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *slot_name = nullptr,
    const char *texture = nullptr) {
  auto slot_name__ = slot_name ? _fbb.CreateString(slot_name) : 0;
  auto texture__ = texture ? _fbb.CreateString(texture) : 0;
  return slug::fbs::srtf::CreateTextureParameter(
      _fbb,
      slot_name__,
      texture__);
}

struct ConstantBufferLayout FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConstantBufferLayoutBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ConstantBufferLayoutTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARAMETER_NAME = 4,
    VT_TYPE = 6
  };
  const ::flatbuffers::String *parameter_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PARAMETER_NAME);
  }
  ::flatbuffers::String *mutable_parameter_name() {
    return GetPointer<::flatbuffers::String *>(VT_PARAMETER_NAME);
  }
  slug::fbs::srtf::ConstantParameterType type() const {
    return static_cast<slug::fbs::srtf::ConstantParameterType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  bool mutate_type(slug::fbs::srtf::ConstantParameterType _type = static_cast<slug::fbs::srtf::ConstantParameterType>(0)) {
    return SetField<uint8_t>(VT_TYPE, static_cast<uint8_t>(_type), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PARAMETER_NAME) &&
           verifier.VerifyString(parameter_name()) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           verifier.EndTable();
  }
};

struct ConstantBufferLayoutBuilder {
  typedef ConstantBufferLayout Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_parameter_name(::flatbuffers::Offset<::flatbuffers::String> parameter_name) {
    fbb_.AddOffset(ConstantBufferLayout::VT_PARAMETER_NAME, parameter_name);
  }
  void add_type(slug::fbs::srtf::ConstantParameterType type) {
    fbb_.AddElement<uint8_t>(ConstantBufferLayout::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  explicit ConstantBufferLayoutBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ConstantBufferLayout> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ConstantBufferLayout>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ConstantBufferLayout> CreateConstantBufferLayout(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> parameter_name = 0,
    slug::fbs::srtf::ConstantParameterType type = slug::fbs::srtf::ConstantParameterType_Bool) {
  ConstantBufferLayoutBuilder builder_(_fbb);
  builder_.add_parameter_name(parameter_name);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ConstantBufferLayout> CreateConstantBufferLayoutDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *parameter_name = nullptr,
    slug::fbs::srtf::ConstantParameterType type = slug::fbs::srtf::ConstantParameterType_Bool) {
  auto parameter_name__ = parameter_name ? _fbb.CreateString(parameter_name) : 0;
  return slug::fbs::srtf::CreateConstantBufferLayout(
      _fbb,
      parameter_name__,
      type);
}

struct ConstantParameter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConstantParameterBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ConstantParameterTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LAYOUTS = 4,
    VT_BOOL_PARAMETERS = 6,
    VT_FLOAT_PARAMETERS = 8,
    VT_FLOAT_ARRAY_PARAMETERS = 10,
    VT_VECTOR2_PARAMETERS = 12,
    VT_VECTOR3_PARAMETERS = 14,
    VT_VECTOR4_PARAMETERS = 16,
    VT_MATRIX3X3_PARAMETERS = 18,
    VT_MATRIX4X4_PARAMETERS = 20
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ConstantBufferLayout>> *layouts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ConstantBufferLayout>> *>(VT_LAYOUTS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ConstantBufferLayout>> *mutable_layouts() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ConstantBufferLayout>> *>(VT_LAYOUTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *bool_parameters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *>(VT_BOOL_PARAMETERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *mutable_bool_parameters() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *>(VT_BOOL_PARAMETERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatParameter>> *float_parameters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatParameter>> *>(VT_FLOAT_PARAMETERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatParameter>> *mutable_float_parameters() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatParameter>> *>(VT_FLOAT_PARAMETERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatArrayParameter>> *float_array_parameters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatArrayParameter>> *>(VT_FLOAT_ARRAY_PARAMETERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatArrayParameter>> *mutable_float_array_parameters() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatArrayParameter>> *>(VT_FLOAT_ARRAY_PARAMETERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector2Parameter>> *vector2_parameters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector2Parameter>> *>(VT_VECTOR2_PARAMETERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector2Parameter>> *mutable_vector2_parameters() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector2Parameter>> *>(VT_VECTOR2_PARAMETERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector3Parameter>> *vector3_parameters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector3Parameter>> *>(VT_VECTOR3_PARAMETERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector3Parameter>> *mutable_vector3_parameters() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector3Parameter>> *>(VT_VECTOR3_PARAMETERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector4Parameter>> *vector4_parameters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector4Parameter>> *>(VT_VECTOR4_PARAMETERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector4Parameter>> *mutable_vector4_parameters() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector4Parameter>> *>(VT_VECTOR4_PARAMETERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix3x3Parameter>> *matrix3x3_parameters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix3x3Parameter>> *>(VT_MATRIX3X3_PARAMETERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix3x3Parameter>> *mutable_matrix3x3_parameters() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix3x3Parameter>> *>(VT_MATRIX3X3_PARAMETERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix4x4Parameter>> *matrix4x4_parameters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix4x4Parameter>> *>(VT_MATRIX4X4_PARAMETERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix4x4Parameter>> *mutable_matrix4x4_parameters() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix4x4Parameter>> *>(VT_MATRIX4X4_PARAMETERS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LAYOUTS) &&
           verifier.VerifyVector(layouts()) &&
           verifier.VerifyVectorOfTables(layouts()) &&
           VerifyOffset(verifier, VT_BOOL_PARAMETERS) &&
           verifier.VerifyVector(bool_parameters()) &&
           verifier.VerifyVectorOfTables(bool_parameters()) &&
           VerifyOffset(verifier, VT_FLOAT_PARAMETERS) &&
           verifier.VerifyVector(float_parameters()) &&
           verifier.VerifyVectorOfTables(float_parameters()) &&
           VerifyOffset(verifier, VT_FLOAT_ARRAY_PARAMETERS) &&
           verifier.VerifyVector(float_array_parameters()) &&
           verifier.VerifyVectorOfTables(float_array_parameters()) &&
           VerifyOffset(verifier, VT_VECTOR2_PARAMETERS) &&
           verifier.VerifyVector(vector2_parameters()) &&
           verifier.VerifyVectorOfTables(vector2_parameters()) &&
           VerifyOffset(verifier, VT_VECTOR3_PARAMETERS) &&
           verifier.VerifyVector(vector3_parameters()) &&
           verifier.VerifyVectorOfTables(vector3_parameters()) &&
           VerifyOffset(verifier, VT_VECTOR4_PARAMETERS) &&
           verifier.VerifyVector(vector4_parameters()) &&
           verifier.VerifyVectorOfTables(vector4_parameters()) &&
           VerifyOffset(verifier, VT_MATRIX3X3_PARAMETERS) &&
           verifier.VerifyVector(matrix3x3_parameters()) &&
           verifier.VerifyVectorOfTables(matrix3x3_parameters()) &&
           VerifyOffset(verifier, VT_MATRIX4X4_PARAMETERS) &&
           verifier.VerifyVector(matrix4x4_parameters()) &&
           verifier.VerifyVectorOfTables(matrix4x4_parameters()) &&
           verifier.EndTable();
  }
};

struct ConstantParameterBuilder {
  typedef ConstantParameter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_layouts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ConstantBufferLayout>>> layouts) {
    fbb_.AddOffset(ConstantParameter::VT_LAYOUTS, layouts);
  }
  void add_bool_parameters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>>> bool_parameters) {
    fbb_.AddOffset(ConstantParameter::VT_BOOL_PARAMETERS, bool_parameters);
  }
  void add_float_parameters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatParameter>>> float_parameters) {
    fbb_.AddOffset(ConstantParameter::VT_FLOAT_PARAMETERS, float_parameters);
  }
  void add_float_array_parameters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatArrayParameter>>> float_array_parameters) {
    fbb_.AddOffset(ConstantParameter::VT_FLOAT_ARRAY_PARAMETERS, float_array_parameters);
  }
  void add_vector2_parameters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector2Parameter>>> vector2_parameters) {
    fbb_.AddOffset(ConstantParameter::VT_VECTOR2_PARAMETERS, vector2_parameters);
  }
  void add_vector3_parameters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector3Parameter>>> vector3_parameters) {
    fbb_.AddOffset(ConstantParameter::VT_VECTOR3_PARAMETERS, vector3_parameters);
  }
  void add_vector4_parameters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector4Parameter>>> vector4_parameters) {
    fbb_.AddOffset(ConstantParameter::VT_VECTOR4_PARAMETERS, vector4_parameters);
  }
  void add_matrix3x3_parameters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix3x3Parameter>>> matrix3x3_parameters) {
    fbb_.AddOffset(ConstantParameter::VT_MATRIX3X3_PARAMETERS, matrix3x3_parameters);
  }
  void add_matrix4x4_parameters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix4x4Parameter>>> matrix4x4_parameters) {
    fbb_.AddOffset(ConstantParameter::VT_MATRIX4X4_PARAMETERS, matrix4x4_parameters);
  }
  explicit ConstantParameterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ConstantParameter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ConstantParameter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ConstantParameter> CreateConstantParameter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ConstantBufferLayout>>> layouts = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>>> bool_parameters = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatParameter>>> float_parameters = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::FloatArrayParameter>>> float_array_parameters = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector2Parameter>>> vector2_parameters = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector3Parameter>>> vector3_parameters = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Vector4Parameter>>> vector4_parameters = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix3x3Parameter>>> matrix3x3_parameters = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix4x4Parameter>>> matrix4x4_parameters = 0) {
  ConstantParameterBuilder builder_(_fbb);
  builder_.add_matrix4x4_parameters(matrix4x4_parameters);
  builder_.add_matrix3x3_parameters(matrix3x3_parameters);
  builder_.add_vector4_parameters(vector4_parameters);
  builder_.add_vector3_parameters(vector3_parameters);
  builder_.add_vector2_parameters(vector2_parameters);
  builder_.add_float_array_parameters(float_array_parameters);
  builder_.add_float_parameters(float_parameters);
  builder_.add_bool_parameters(bool_parameters);
  builder_.add_layouts(layouts);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ConstantParameter> CreateConstantParameterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::ConstantBufferLayout>> *layouts = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *bool_parameters = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::FloatParameter>> *float_parameters = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::FloatArrayParameter>> *float_array_parameters = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::Vector2Parameter>> *vector2_parameters = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::Vector3Parameter>> *vector3_parameters = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::Vector4Parameter>> *vector4_parameters = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix3x3Parameter>> *matrix3x3_parameters = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::Matrix4x4Parameter>> *matrix4x4_parameters = nullptr) {
  auto layouts__ = layouts ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::ConstantBufferLayout>>(*layouts) : 0;
  auto bool_parameters__ = bool_parameters ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>>(*bool_parameters) : 0;
  auto float_parameters__ = float_parameters ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::FloatParameter>>(*float_parameters) : 0;
  auto float_array_parameters__ = float_array_parameters ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::FloatArrayParameter>>(*float_array_parameters) : 0;
  auto vector2_parameters__ = vector2_parameters ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::Vector2Parameter>>(*vector2_parameters) : 0;
  auto vector3_parameters__ = vector3_parameters ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::Vector3Parameter>>(*vector3_parameters) : 0;
  auto vector4_parameters__ = vector4_parameters ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::Vector4Parameter>>(*vector4_parameters) : 0;
  auto matrix3x3_parameters__ = matrix3x3_parameters ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::Matrix3x3Parameter>>(*matrix3x3_parameters) : 0;
  auto matrix4x4_parameters__ = matrix4x4_parameters ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::Matrix4x4Parameter>>(*matrix4x4_parameters) : 0;
  return slug::fbs::srtf::CreateConstantParameter(
      _fbb,
      layouts__,
      bool_parameters__,
      float_parameters__,
      float_array_parameters__,
      vector2_parameters__,
      vector3_parameters__,
      vector4_parameters__,
      matrix3x3_parameters__,
      matrix4x4_parameters__);
}

struct DrawSettings FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DrawSettingsBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DrawSettingsTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BLEND = 4,
    VT_SHADING_MODEL = 6,
    VT_GI_SETTINGS = 8,
    VT_ALPHA_THRESHOLD = 10,
    VT_SORT_PRIORITY = 12,
    VT_TWO_SIDE = 14,
    VT_ALPHA_TO_COVERAGE = 16
  };
  slug::fbs::srtf::BlendOptions blend() const {
    return static_cast<slug::fbs::srtf::BlendOptions>(GetField<uint8_t>(VT_BLEND, 0));
  }
  bool mutate_blend(slug::fbs::srtf::BlendOptions _blend = static_cast<slug::fbs::srtf::BlendOptions>(0)) {
    return SetField<uint8_t>(VT_BLEND, static_cast<uint8_t>(_blend), 0);
  }
  const slug::fbs::srtf::ShadingModel *shading_model() const {
    return GetPointer<const slug::fbs::srtf::ShadingModel *>(VT_SHADING_MODEL);
  }
  slug::fbs::srtf::ShadingModel *mutable_shading_model() {
    return GetPointer<slug::fbs::srtf::ShadingModel *>(VT_SHADING_MODEL);
  }
  const slug::fbs::srtf::GiSettings *gi_settings() const {
    return GetStruct<const slug::fbs::srtf::GiSettings *>(VT_GI_SETTINGS);
  }
  slug::fbs::srtf::GiSettings *mutable_gi_settings() {
    return GetStruct<slug::fbs::srtf::GiSettings *>(VT_GI_SETTINGS);
  }
  float alpha_threshold() const {
    return GetField<float>(VT_ALPHA_THRESHOLD, 0.0f);
  }
  bool mutate_alpha_threshold(float _alpha_threshold = 0.0f) {
    return SetField<float>(VT_ALPHA_THRESHOLD, _alpha_threshold, 0.0f);
  }
  int32_t sort_priority() const {
    return GetField<int32_t>(VT_SORT_PRIORITY, 0);
  }
  bool mutate_sort_priority(int32_t _sort_priority = 0) {
    return SetField<int32_t>(VT_SORT_PRIORITY, _sort_priority, 0);
  }
  bool two_side() const {
    return GetField<uint8_t>(VT_TWO_SIDE, 0) != 0;
  }
  bool mutate_two_side(bool _two_side = 0) {
    return SetField<uint8_t>(VT_TWO_SIDE, static_cast<uint8_t>(_two_side), 0);
  }
  bool alpha_to_coverage() const {
    return GetField<uint8_t>(VT_ALPHA_TO_COVERAGE, 0) != 0;
  }
  bool mutate_alpha_to_coverage(bool _alpha_to_coverage = 0) {
    return SetField<uint8_t>(VT_ALPHA_TO_COVERAGE, static_cast<uint8_t>(_alpha_to_coverage), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BLEND, 1) &&
           VerifyOffset(verifier, VT_SHADING_MODEL) &&
           verifier.VerifyTable(shading_model()) &&
           VerifyField<slug::fbs::srtf::GiSettings>(verifier, VT_GI_SETTINGS, 4) &&
           VerifyField<float>(verifier, VT_ALPHA_THRESHOLD, 4) &&
           VerifyField<int32_t>(verifier, VT_SORT_PRIORITY, 4) &&
           VerifyField<uint8_t>(verifier, VT_TWO_SIDE, 1) &&
           VerifyField<uint8_t>(verifier, VT_ALPHA_TO_COVERAGE, 1) &&
           verifier.EndTable();
  }
};

struct DrawSettingsBuilder {
  typedef DrawSettings Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_blend(slug::fbs::srtf::BlendOptions blend) {
    fbb_.AddElement<uint8_t>(DrawSettings::VT_BLEND, static_cast<uint8_t>(blend), 0);
  }
  void add_shading_model(::flatbuffers::Offset<slug::fbs::srtf::ShadingModel> shading_model) {
    fbb_.AddOffset(DrawSettings::VT_SHADING_MODEL, shading_model);
  }
  void add_gi_settings(const slug::fbs::srtf::GiSettings *gi_settings) {
    fbb_.AddStruct(DrawSettings::VT_GI_SETTINGS, gi_settings);
  }
  void add_alpha_threshold(float alpha_threshold) {
    fbb_.AddElement<float>(DrawSettings::VT_ALPHA_THRESHOLD, alpha_threshold, 0.0f);
  }
  void add_sort_priority(int32_t sort_priority) {
    fbb_.AddElement<int32_t>(DrawSettings::VT_SORT_PRIORITY, sort_priority, 0);
  }
  void add_two_side(bool two_side) {
    fbb_.AddElement<uint8_t>(DrawSettings::VT_TWO_SIDE, static_cast<uint8_t>(two_side), 0);
  }
  void add_alpha_to_coverage(bool alpha_to_coverage) {
    fbb_.AddElement<uint8_t>(DrawSettings::VT_ALPHA_TO_COVERAGE, static_cast<uint8_t>(alpha_to_coverage), 0);
  }
  explicit DrawSettingsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DrawSettings> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DrawSettings>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DrawSettings> CreateDrawSettings(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    slug::fbs::srtf::BlendOptions blend = slug::fbs::srtf::BlendOptions_Opaque,
    ::flatbuffers::Offset<slug::fbs::srtf::ShadingModel> shading_model = 0,
    const slug::fbs::srtf::GiSettings *gi_settings = nullptr,
    float alpha_threshold = 0.0f,
    int32_t sort_priority = 0,
    bool two_side = false,
    bool alpha_to_coverage = false) {
  DrawSettingsBuilder builder_(_fbb);
  builder_.add_sort_priority(sort_priority);
  builder_.add_alpha_threshold(alpha_threshold);
  builder_.add_gi_settings(gi_settings);
  builder_.add_shading_model(shading_model);
  builder_.add_alpha_to_coverage(alpha_to_coverage);
  builder_.add_two_side(two_side);
  builder_.add_blend(blend);
  return builder_.Finish();
}

struct Shader FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ShaderBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ShaderTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DRAW_SETTINGS = 4,
    VT_NAME = 6,
    VT_TEXTUERS = 8,
    VT_STATIC_SWICHES = 10,
    VT_CONSTANT_PARAMETER = 12,
    VT_VERTEX_SHADERS = 14,
    VT_PIXEL_SHADERS = 16,
    VT_GEOMETRY_SHADERS = 18,
    VT_HULL_SHADERS = 20,
    VT_DOMAIN_SHADERS = 22,
    VT_COMPUTE_SHADERS = 24
  };
  const slug::fbs::srtf::DrawSettings *draw_settings() const {
    return GetPointer<const slug::fbs::srtf::DrawSettings *>(VT_DRAW_SETTINGS);
  }
  slug::fbs::srtf::DrawSettings *mutable_draw_settings() {
    return GetPointer<slug::fbs::srtf::DrawSettings *>(VT_DRAW_SETTINGS);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>> *textuers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>> *>(VT_TEXTUERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>> *mutable_textuers() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>> *>(VT_TEXTUERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *static_swiches() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *>(VT_STATIC_SWICHES);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *mutable_static_swiches() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *>(VT_STATIC_SWICHES);
  }
  const slug::fbs::srtf::ConstantParameter *constant_parameter() const {
    return GetPointer<const slug::fbs::srtf::ConstantParameter *>(VT_CONSTANT_PARAMETER);
  }
  slug::fbs::srtf::ConstantParameter *mutable_constant_parameter() {
    return GetPointer<slug::fbs::srtf::ConstantParameter *>(VT_CONSTANT_PARAMETER);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *vertex_shaders() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_VERTEX_SHADERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *mutable_vertex_shaders() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_VERTEX_SHADERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *pixel_shaders() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_PIXEL_SHADERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *mutable_pixel_shaders() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_PIXEL_SHADERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *geometry_shaders() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_GEOMETRY_SHADERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *mutable_geometry_shaders() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_GEOMETRY_SHADERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *hull_shaders() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_HULL_SHADERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *mutable_hull_shaders() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_HULL_SHADERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *domain_shaders() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_DOMAIN_SHADERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *mutable_domain_shaders() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_DOMAIN_SHADERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *compute_shaders() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_COMPUTE_SHADERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *mutable_compute_shaders() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *>(VT_COMPUTE_SHADERS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DRAW_SETTINGS) &&
           verifier.VerifyTable(draw_settings()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TEXTUERS) &&
           verifier.VerifyVector(textuers()) &&
           verifier.VerifyVectorOfTables(textuers()) &&
           VerifyOffset(verifier, VT_STATIC_SWICHES) &&
           verifier.VerifyVector(static_swiches()) &&
           verifier.VerifyVectorOfTables(static_swiches()) &&
           VerifyOffset(verifier, VT_CONSTANT_PARAMETER) &&
           verifier.VerifyTable(constant_parameter()) &&
           VerifyOffset(verifier, VT_VERTEX_SHADERS) &&
           verifier.VerifyVector(vertex_shaders()) &&
           verifier.VerifyVectorOfTables(vertex_shaders()) &&
           VerifyOffset(verifier, VT_PIXEL_SHADERS) &&
           verifier.VerifyVector(pixel_shaders()) &&
           verifier.VerifyVectorOfTables(pixel_shaders()) &&
           VerifyOffset(verifier, VT_GEOMETRY_SHADERS) &&
           verifier.VerifyVector(geometry_shaders()) &&
           verifier.VerifyVectorOfTables(geometry_shaders()) &&
           VerifyOffset(verifier, VT_HULL_SHADERS) &&
           verifier.VerifyVector(hull_shaders()) &&
           verifier.VerifyVectorOfTables(hull_shaders()) &&
           VerifyOffset(verifier, VT_DOMAIN_SHADERS) &&
           verifier.VerifyVector(domain_shaders()) &&
           verifier.VerifyVectorOfTables(domain_shaders()) &&
           VerifyOffset(verifier, VT_COMPUTE_SHADERS) &&
           verifier.VerifyVector(compute_shaders()) &&
           verifier.VerifyVectorOfTables(compute_shaders()) &&
           verifier.EndTable();
  }
};

struct ShaderBuilder {
  typedef Shader Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_draw_settings(::flatbuffers::Offset<slug::fbs::srtf::DrawSettings> draw_settings) {
    fbb_.AddOffset(Shader::VT_DRAW_SETTINGS, draw_settings);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Shader::VT_NAME, name);
  }
  void add_textuers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>>> textuers) {
    fbb_.AddOffset(Shader::VT_TEXTUERS, textuers);
  }
  void add_static_swiches(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>>> static_swiches) {
    fbb_.AddOffset(Shader::VT_STATIC_SWICHES, static_swiches);
  }
  void add_constant_parameter(::flatbuffers::Offset<slug::fbs::srtf::ConstantParameter> constant_parameter) {
    fbb_.AddOffset(Shader::VT_CONSTANT_PARAMETER, constant_parameter);
  }
  void add_vertex_shaders(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> vertex_shaders) {
    fbb_.AddOffset(Shader::VT_VERTEX_SHADERS, vertex_shaders);
  }
  void add_pixel_shaders(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> pixel_shaders) {
    fbb_.AddOffset(Shader::VT_PIXEL_SHADERS, pixel_shaders);
  }
  void add_geometry_shaders(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> geometry_shaders) {
    fbb_.AddOffset(Shader::VT_GEOMETRY_SHADERS, geometry_shaders);
  }
  void add_hull_shaders(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> hull_shaders) {
    fbb_.AddOffset(Shader::VT_HULL_SHADERS, hull_shaders);
  }
  void add_domain_shaders(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> domain_shaders) {
    fbb_.AddOffset(Shader::VT_DOMAIN_SHADERS, domain_shaders);
  }
  void add_compute_shaders(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> compute_shaders) {
    fbb_.AddOffset(Shader::VT_COMPUTE_SHADERS, compute_shaders);
  }
  explicit ShaderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Shader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Shader>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Shader> CreateShader(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::DrawSettings> draw_settings = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>>> textuers = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>>> static_swiches = 0,
    ::flatbuffers::Offset<slug::fbs::srtf::ConstantParameter> constant_parameter = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> vertex_shaders = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> pixel_shaders = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> geometry_shaders = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> hull_shaders = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> domain_shaders = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>> compute_shaders = 0) {
  ShaderBuilder builder_(_fbb);
  builder_.add_compute_shaders(compute_shaders);
  builder_.add_domain_shaders(domain_shaders);
  builder_.add_hull_shaders(hull_shaders);
  builder_.add_geometry_shaders(geometry_shaders);
  builder_.add_pixel_shaders(pixel_shaders);
  builder_.add_vertex_shaders(vertex_shaders);
  builder_.add_constant_parameter(constant_parameter);
  builder_.add_static_swiches(static_swiches);
  builder_.add_textuers(textuers);
  builder_.add_name(name);
  builder_.add_draw_settings(draw_settings);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Shader> CreateShaderDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::DrawSettings> draw_settings = 0,
    const char *name = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>> *textuers = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>> *static_swiches = nullptr,
    ::flatbuffers::Offset<slug::fbs::srtf::ConstantParameter> constant_parameter = 0,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *vertex_shaders = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *pixel_shaders = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *geometry_shaders = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *hull_shaders = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *domain_shaders = nullptr,
    const std::vector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>> *compute_shaders = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto textuers__ = textuers ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::TextureParameter>>(*textuers) : 0;
  auto static_swiches__ = static_swiches ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::BoolParameter>>(*static_swiches) : 0;
  auto vertex_shaders__ = vertex_shaders ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>(*vertex_shaders) : 0;
  auto pixel_shaders__ = pixel_shaders ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>(*pixel_shaders) : 0;
  auto geometry_shaders__ = geometry_shaders ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>(*geometry_shaders) : 0;
  auto hull_shaders__ = hull_shaders ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>(*hull_shaders) : 0;
  auto domain_shaders__ = domain_shaders ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>(*domain_shaders) : 0;
  auto compute_shaders__ = compute_shaders ? _fbb.CreateVector<::flatbuffers::Offset<slug::fbs::srtf::ShaderItem>>(*compute_shaders) : 0;
  return slug::fbs::srtf::CreateShader(
      _fbb,
      draw_settings,
      name__,
      textuers__,
      static_swiches__,
      constant_parameter,
      vertex_shaders__,
      pixel_shaders__,
      geometry_shaders__,
      hull_shaders__,
      domain_shaders__,
      compute_shaders__);
}

inline const ::flatbuffers::TypeTable *BlendOptionsTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::BlendOptionsTypeTable
  };
  static const char * const names[] = {
    "Opaque",
    "Mask",
    "Transparent",
    "Addtive",
    "Modulate"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_ENUM, 5, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ConstantParameterTypeTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::ConstantParameterTypeTypeTable
  };
  static const char * const names[] = {
    "Bool",
    "Float",
    "FloatArray",
    "Vector2",
    "Vector3",
    "Vector4",
    "Matrix3x3",
    "Matrix4x4"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_ENUM, 8, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *GiSettingsTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_FLOAT, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 0, -1 }
  };
  static const int64_t values[] = { 0, 4, 8 };
  static const char * const names[] = {
    "diffuse_boost",
    "emissive_boost"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 2, type_codes, nullptr, nullptr, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ShadingModelTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 }
  };
  static const char * const names[] = {
    "name",
    "id"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ShaderItemTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 1, -1 }
  };
  static const char * const names[] = {
    "name",
    "code"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *TextureParameterTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const char * const names[] = {
    "slot_name",
    "texture"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ConstantBufferLayoutTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::ConstantParameterTypeTypeTable
  };
  static const char * const names[] = {
    "parameter_name",
    "type"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ConstantParameterTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 1, 0 },
    { ::flatbuffers::ET_SEQUENCE, 1, 1 },
    { ::flatbuffers::ET_SEQUENCE, 1, 2 },
    { ::flatbuffers::ET_SEQUENCE, 1, 3 },
    { ::flatbuffers::ET_SEQUENCE, 1, 4 },
    { ::flatbuffers::ET_SEQUENCE, 1, 5 },
    { ::flatbuffers::ET_SEQUENCE, 1, 6 },
    { ::flatbuffers::ET_SEQUENCE, 1, 7 },
    { ::flatbuffers::ET_SEQUENCE, 1, 8 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::ConstantBufferLayoutTypeTable,
    slug::fbs::srtf::BoolParameterTypeTable,
    slug::fbs::srtf::FloatParameterTypeTable,
    slug::fbs::srtf::FloatArrayParameterTypeTable,
    slug::fbs::srtf::Vector2ParameterTypeTable,
    slug::fbs::srtf::Vector3ParameterTypeTable,
    slug::fbs::srtf::Vector4ParameterTypeTable,
    slug::fbs::srtf::Matrix3x3ParameterTypeTable,
    slug::fbs::srtf::Matrix4x4ParameterTypeTable
  };
  static const char * const names[] = {
    "layouts",
    "bool_parameters",
    "float_parameters",
    "float_array_parameters",
    "vector2_parameters",
    "vector3_parameters",
    "vector4_parameters",
    "matrix3x3_parameters",
    "matrix4x4_parameters"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 9, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *DrawSettingsTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 2 },
    { ::flatbuffers::ET_FLOAT, 0, -1 },
    { ::flatbuffers::ET_INT, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::BlendOptionsTypeTable,
    slug::fbs::srtf::ShadingModelTypeTable,
    slug::fbs::srtf::GiSettingsTypeTable
  };
  static const char * const names[] = {
    "blend",
    "shading_model",
    "gi_settings",
    "alpha_threshold",
    "sort_priority",
    "two_side",
    "alpha_to_coverage"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 7, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ShaderTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 1, 1 },
    { ::flatbuffers::ET_SEQUENCE, 1, 2 },
    { ::flatbuffers::ET_SEQUENCE, 0, 3 },
    { ::flatbuffers::ET_SEQUENCE, 1, 4 },
    { ::flatbuffers::ET_SEQUENCE, 1, 4 },
    { ::flatbuffers::ET_SEQUENCE, 1, 4 },
    { ::flatbuffers::ET_SEQUENCE, 1, 4 },
    { ::flatbuffers::ET_SEQUENCE, 1, 4 },
    { ::flatbuffers::ET_SEQUENCE, 1, 4 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::DrawSettingsTypeTable,
    slug::fbs::srtf::TextureParameterTypeTable,
    slug::fbs::srtf::BoolParameterTypeTable,
    slug::fbs::srtf::ConstantParameterTypeTable,
    slug::fbs::srtf::ShaderItemTypeTable
  };
  static const char * const names[] = {
    "draw_settings",
    "name",
    "textuers",
    "static_swiches",
    "constant_parameter",
    "vertex_shaders",
    "pixel_shaders",
    "geometry_shaders",
    "hull_shaders",
    "domain_shaders",
    "compute_shaders"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 11, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const slug::fbs::srtf::Shader *GetShader(const void *buf) {
  return ::flatbuffers::GetRoot<slug::fbs::srtf::Shader>(buf);
}

inline const slug::fbs::srtf::Shader *GetSizePrefixedShader(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<slug::fbs::srtf::Shader>(buf);
}

inline Shader *GetMutableShader(void *buf) {
  return ::flatbuffers::GetMutableRoot<Shader>(buf);
}

inline slug::fbs::srtf::Shader *GetMutableSizePrefixedShader(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<slug::fbs::srtf::Shader>(buf);
}

inline const char *ShaderIdentifier() {
  return "SHAD";
}

inline bool ShaderBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ShaderIdentifier());
}

inline bool SizePrefixedShaderBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ShaderIdentifier(), true);
}

inline bool VerifyShaderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<slug::fbs::srtf::Shader>(ShaderIdentifier());
}

inline bool VerifySizePrefixedShaderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<slug::fbs::srtf::Shader>(ShaderIdentifier());
}

inline void FinishShaderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::Shader> root) {
  fbb.Finish(root, ShaderIdentifier());
}

inline void FinishSizePrefixedShaderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::Shader> root) {
  fbb.FinishSizePrefixed(root, ShaderIdentifier());
}

}  // namespace srtf
}  // namespace fbs
}  // namespace slug

#endif  // FLATBUFFERS_GENERATED_SHADER_SLUG_FBS_SRTF_H_
