// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TEXTURE_SLUG_FBS_SRTF_H_
#define FLATBUFFERS_GENERATED_TEXTURE_SLUG_FBS_SRTF_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "common_fbs.h"

namespace slug {
namespace fbs {
namespace srtf {

struct Sampler;

struct Texture;
struct TextureBuilder;

inline const ::flatbuffers::TypeTable *SamplerTypeTable();

inline const ::flatbuffers::TypeTable *TextureTypeTable();

enum SamplerAddressMode : uint8_t {
  SamplerAddressMode_Clamp = 0,
  SamplerAddressMode_Wrap = 1,
  SamplerAddressMode_Border = 2,
  SamplerAddressMode_Mirror = 3,
  SamplerAddressMode_MIN = SamplerAddressMode_Clamp,
  SamplerAddressMode_MAX = SamplerAddressMode_Mirror
};

inline const SamplerAddressMode (&EnumValuesSamplerAddressMode())[4] {
  static const SamplerAddressMode values[] = {
    SamplerAddressMode_Clamp,
    SamplerAddressMode_Wrap,
    SamplerAddressMode_Border,
    SamplerAddressMode_Mirror
  };
  return values;
}

inline const char * const *EnumNamesSamplerAddressMode() {
  static const char * const names[5] = {
    "Clamp",
    "Wrap",
    "Border",
    "Mirror",
    nullptr
  };
  return names;
}

inline const char *EnumNameSamplerAddressMode(SamplerAddressMode e) {
  if (::flatbuffers::IsOutRange(e, SamplerAddressMode_Clamp, SamplerAddressMode_Mirror)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSamplerAddressMode()[index];
}

enum SamplerReductionType : uint8_t {
  SamplerReductionType_Standard = 0,
  SamplerReductionType_Comparison = 1,
  SamplerReductionType_Minimum = 2,
  SamplerReductionType_Maximum = 3,
  SamplerReductionType_MIN = SamplerReductionType_Standard,
  SamplerReductionType_MAX = SamplerReductionType_Maximum
};

inline const SamplerReductionType (&EnumValuesSamplerReductionType())[4] {
  static const SamplerReductionType values[] = {
    SamplerReductionType_Standard,
    SamplerReductionType_Comparison,
    SamplerReductionType_Minimum,
    SamplerReductionType_Maximum
  };
  return values;
}

inline const char * const *EnumNamesSamplerReductionType() {
  static const char * const names[5] = {
    "Standard",
    "Comparison",
    "Minimum",
    "Maximum",
    nullptr
  };
  return names;
}

inline const char *EnumNameSamplerReductionType(SamplerReductionType e) {
  if (::flatbuffers::IsOutRange(e, SamplerReductionType_Standard, SamplerReductionType_Maximum)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSamplerReductionType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Sampler FLATBUFFERS_FINAL_CLASS {
 private:
  slug::fbs::srtf::Vector4 color_;
  float max_anisotropy_;
  float mip_bias_;
  uint8_t min_filter_;
  uint8_t mag_filter_;
  uint8_t mip_filter_;
  uint8_t address_u_;
  uint8_t address_v_;
  uint8_t address_w_;
  uint8_t reduction_type_;
  int8_t padding0__;

 public:
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SamplerTypeTable();
  }
  Sampler()
      : color_(),
        max_anisotropy_(0),
        mip_bias_(0),
        min_filter_(0),
        mag_filter_(0),
        mip_filter_(0),
        address_u_(0),
        address_v_(0),
        address_w_(0),
        reduction_type_(0),
        padding0__(0) {
    (void)padding0__;
  }
  Sampler(const slug::fbs::srtf::Vector4 &_color, float _max_anisotropy, float _mip_bias, bool _min_filter, bool _mag_filter, bool _mip_filter, slug::fbs::srtf::SamplerAddressMode _address_u, slug::fbs::srtf::SamplerAddressMode _address_v, slug::fbs::srtf::SamplerAddressMode _address_w, slug::fbs::srtf::SamplerReductionType _reduction_type)
      : color_(_color),
        max_anisotropy_(::flatbuffers::EndianScalar(_max_anisotropy)),
        mip_bias_(::flatbuffers::EndianScalar(_mip_bias)),
        min_filter_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_min_filter))),
        mag_filter_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_mag_filter))),
        mip_filter_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_mip_filter))),
        address_u_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_address_u))),
        address_v_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_address_v))),
        address_w_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_address_w))),
        reduction_type_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_reduction_type))),
        padding0__(0) {
    (void)padding0__;
  }
  const slug::fbs::srtf::Vector4 &color() const {
    return color_;
  }
  slug::fbs::srtf::Vector4 &mutable_color() {
    return color_;
  }
  float max_anisotropy() const {
    return ::flatbuffers::EndianScalar(max_anisotropy_);
  }
  void mutate_max_anisotropy(float _max_anisotropy) {
    ::flatbuffers::WriteScalar(&max_anisotropy_, _max_anisotropy);
  }
  float mip_bias() const {
    return ::flatbuffers::EndianScalar(mip_bias_);
  }
  void mutate_mip_bias(float _mip_bias) {
    ::flatbuffers::WriteScalar(&mip_bias_, _mip_bias);
  }
  bool min_filter() const {
    return ::flatbuffers::EndianScalar(min_filter_) != 0;
  }
  void mutate_min_filter(bool _min_filter) {
    ::flatbuffers::WriteScalar(&min_filter_, static_cast<uint8_t>(_min_filter));
  }
  bool mag_filter() const {
    return ::flatbuffers::EndianScalar(mag_filter_) != 0;
  }
  void mutate_mag_filter(bool _mag_filter) {
    ::flatbuffers::WriteScalar(&mag_filter_, static_cast<uint8_t>(_mag_filter));
  }
  bool mip_filter() const {
    return ::flatbuffers::EndianScalar(mip_filter_) != 0;
  }
  void mutate_mip_filter(bool _mip_filter) {
    ::flatbuffers::WriteScalar(&mip_filter_, static_cast<uint8_t>(_mip_filter));
  }
  slug::fbs::srtf::SamplerAddressMode address_u() const {
    return static_cast<slug::fbs::srtf::SamplerAddressMode>(::flatbuffers::EndianScalar(address_u_));
  }
  void mutate_address_u(slug::fbs::srtf::SamplerAddressMode _address_u) {
    ::flatbuffers::WriteScalar(&address_u_, static_cast<uint8_t>(_address_u));
  }
  slug::fbs::srtf::SamplerAddressMode address_v() const {
    return static_cast<slug::fbs::srtf::SamplerAddressMode>(::flatbuffers::EndianScalar(address_v_));
  }
  void mutate_address_v(slug::fbs::srtf::SamplerAddressMode _address_v) {
    ::flatbuffers::WriteScalar(&address_v_, static_cast<uint8_t>(_address_v));
  }
  slug::fbs::srtf::SamplerAddressMode address_w() const {
    return static_cast<slug::fbs::srtf::SamplerAddressMode>(::flatbuffers::EndianScalar(address_w_));
  }
  void mutate_address_w(slug::fbs::srtf::SamplerAddressMode _address_w) {
    ::flatbuffers::WriteScalar(&address_w_, static_cast<uint8_t>(_address_w));
  }
  slug::fbs::srtf::SamplerReductionType reduction_type() const {
    return static_cast<slug::fbs::srtf::SamplerReductionType>(::flatbuffers::EndianScalar(reduction_type_));
  }
  void mutate_reduction_type(slug::fbs::srtf::SamplerReductionType _reduction_type) {
    ::flatbuffers::WriteScalar(&reduction_type_, static_cast<uint8_t>(_reduction_type));
  }
};
FLATBUFFERS_STRUCT_END(Sampler, 32);

struct Texture FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TextureBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return TextureTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_SAMPLER = 6,
    VT_SOURCE = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const slug::fbs::srtf::Sampler *sampler() const {
    return GetStruct<const slug::fbs::srtf::Sampler *>(VT_SAMPLER);
  }
  slug::fbs::srtf::Sampler *mutable_sampler() {
    return GetStruct<slug::fbs::srtf::Sampler *>(VT_SAMPLER);
  }
  const ::flatbuffers::Vector<uint8_t> *source() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_SOURCE);
  }
  ::flatbuffers::Vector<uint8_t> *mutable_source() {
    return GetPointer<::flatbuffers::Vector<uint8_t> *>(VT_SOURCE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<slug::fbs::srtf::Sampler>(verifier, VT_SAMPLER, 4) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyVector(source()) &&
           verifier.EndTable();
  }
};

struct TextureBuilder {
  typedef Texture Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Texture::VT_NAME, name);
  }
  void add_sampler(const slug::fbs::srtf::Sampler *sampler) {
    fbb_.AddStruct(Texture::VT_SAMPLER, sampler);
  }
  void add_source(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> source) {
    fbb_.AddOffset(Texture::VT_SOURCE, source);
  }
  explicit TextureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Texture> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Texture>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Texture> CreateTexture(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const slug::fbs::srtf::Sampler *sampler = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> source = 0) {
  TextureBuilder builder_(_fbb);
  builder_.add_source(source);
  builder_.add_sampler(sampler);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Texture> CreateTextureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const slug::fbs::srtf::Sampler *sampler = nullptr,
    const std::vector<uint8_t> *source = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto source__ = source ? _fbb.CreateVector<uint8_t>(*source) : 0;
  return slug::fbs::srtf::CreateTexture(
      _fbb,
      name__,
      sampler,
      source__);
}

inline const ::flatbuffers::TypeTable *SamplerAddressModeTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::SamplerAddressModeTypeTable
  };
  static const char * const names[] = {
    "Clamp",
    "Wrap",
    "Border",
    "Mirror"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_ENUM, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *SamplerReductionTypeTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::SamplerReductionTypeTypeTable
  };
  static const char * const names[] = {
    "Standard",
    "Comparison",
    "Minimum",
    "Maximum"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_ENUM, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *SamplerTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_FLOAT, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 0, 1 },
    { ::flatbuffers::ET_UCHAR, 0, 1 },
    { ::flatbuffers::ET_UCHAR, 0, 1 },
    { ::flatbuffers::ET_UCHAR, 0, 2 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::Vector4TypeTable,
    slug::fbs::srtf::SamplerAddressModeTypeTable,
    slug::fbs::srtf::SamplerReductionTypeTypeTable
  };
  static const int64_t values[] = { 0, 16, 20, 24, 25, 26, 27, 28, 29, 30, 32 };
  static const char * const names[] = {
    "color",
    "max_anisotropy",
    "mip_bias",
    "min_filter",
    "mag_filter",
    "mip_filter",
    "address_u",
    "address_v",
    "address_w",
    "reduction_type"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_STRUCT, 10, type_codes, type_refs, nullptr, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *TextureTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 1, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    slug::fbs::srtf::SamplerTypeTable
  };
  static const char * const names[] = {
    "name",
    "sampler",
    "source"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const slug::fbs::srtf::Texture *GetTexture(const void *buf) {
  return ::flatbuffers::GetRoot<slug::fbs::srtf::Texture>(buf);
}

inline const slug::fbs::srtf::Texture *GetSizePrefixedTexture(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<slug::fbs::srtf::Texture>(buf);
}

inline Texture *GetMutableTexture(void *buf) {
  return ::flatbuffers::GetMutableRoot<Texture>(buf);
}

inline slug::fbs::srtf::Texture *GetMutableSizePrefixedTexture(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<slug::fbs::srtf::Texture>(buf);
}

inline const char *TextureIdentifier() {
  return "TEXT";
}

inline bool TextureBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, TextureIdentifier());
}

inline bool SizePrefixedTextureBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, TextureIdentifier(), true);
}

inline bool VerifyTextureBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<slug::fbs::srtf::Texture>(TextureIdentifier());
}

inline bool VerifySizePrefixedTextureBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<slug::fbs::srtf::Texture>(TextureIdentifier());
}

inline void FinishTextureBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::Texture> root) {
  fbb.Finish(root, TextureIdentifier());
}

inline void FinishSizePrefixedTextureBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<slug::fbs::srtf::Texture> root) {
  fbb.FinishSizePrefixed(root, TextureIdentifier());
}

}  // namespace srtf
}  // namespace fbs
}  // namespace slug

#endif  // FLATBUFFERS_GENERATED_TEXTURE_SLUG_FBS_SRTF_H_
